import type { Categoria, CategoriaId } from '@/games/mr-white/types';

export const CATEGORIAS: Record<CategoriaId, Categoria> = {
  comidas: {
    id: 'comidas',
    nome: 'Comidas',
    emoji: '🍕',
    descricao: 'Pratos brasileiros e clássicos da cozinha internacional',
    palavras: [
      { civis: 'Pizza', undercover: 'Lasanha' },
      { civis: 'Hambúrguer', undercover: 'Cachorro-quente' },
      { civis: 'Sushi', undercover: 'Temaki' },
      { civis: 'Brigadeiro', undercover: 'Beijinho' },
      { civis: 'Coxinha', undercover: 'Kibe' },
      { civis: 'Açaí', undercover: 'Sorvete' },
      { civis: 'Feijoada', undercover: 'Dobradinha' },
      { civis: 'Pastel', undercover: 'Empada' },
      { civis: 'Tapioca', undercover: 'Crepe' },
      { civis: 'Churrasco', undercover: 'Barbecue' },
      { civis: 'Pão de Queijo', undercover: 'Pão Francês' },
      { civis: 'Macarrão', undercover: 'Espaguete' },
      { civis: 'Strogonoff', undercover: 'Frango ao Molho' },
      { civis: 'Esfiha', undercover: 'Quibe' },
      { civis: 'Pamonha', undercover: 'Curau' },
      { civis: 'Moqueca', undercover: 'Bobó de Camarão' },
      { civis: 'Arroz', undercover: 'Risoto' },
      { civis: 'Pudim', undercover: 'Manjar Branco' },
      { civis: 'Bolo de Cenoura', undercover: 'Bolo de Fubá' },
      { civis: 'Quindim', undercover: 'Cocada' },
      { civis: 'Sanduíche', undercover: 'Wrap' },
      { civis: 'Picanha', undercover: 'Costela' },
      { civis: 'Salpicão', undercover: 'Maionese de Batata' },
      { civis: 'Farofa', undercover: 'Vinagrete' },
      { civis: 'Yakisoba', undercover: 'Lámen' },
      { civis: 'Doce de Leite', undercover: 'Goiabada' },
      { civis: 'Paçoca', undercover: 'Pé de Moleque' },
      { civis: 'Cuscuz', undercover: 'Polenta' },
      { civis: 'Acarajé', undercover: 'Vatapá' },
      { civis: 'Pavê', undercover: 'Torta Holandesa' },
      { civis: 'Bauru', undercover: 'Misto Quente' },
      { civis: 'Salada', undercover: 'Tabule' },
      { civis: 'Calzone', undercover: 'Pastel Assado' },
      { civis: 'Caldo Verde', undercover: 'Sopa de Legumes' },
      { civis: 'Empadão', undercover: 'Torta Salgada' },
      { civis: 'Frango Assado', undercover: 'Peru Assado' },
      { civis: 'Rondelli', undercover: 'Canelone' },
      { civis: 'Pão de Mel', undercover: 'Cuca' },
      { civis: 'Sopa de Cebola', undercover: 'Sopa de Tomate' },
      { civis: 'Burrito', undercover: 'Tortilla' },
      { civis: 'Nachos', undercover: 'Doritos' },
      { civis: 'Cookie', undercover: 'Biscoito Recheado' },
      { civis: 'Brownie', undercover: 'Petit Gateau' },
      { civis: 'Milkshake', undercover: 'Vitamina' },
    ],
  },
  lugares: {
    id: 'lugares',
    nome: 'Lugares',
    emoji: '🌍',
    descricao: 'Cidades, países e tipos de lugares pelo mundo',
    palavras: [
      { civis: 'Praia', undercover: 'Piscina' },
      { civis: 'Paris', undercover: 'Roma' },
      { civis: 'Rio de Janeiro', undercover: 'São Paulo' },
      { civis: 'Floresta', undercover: 'Parque' },
      { civis: 'Montanha', undercover: 'Colina' },
      { civis: 'Shopping', undercover: 'Supermercado' },
      { civis: 'Cinema', undercover: 'Teatro' },
      { civis: 'Escola', undercover: 'Faculdade' },
      { civis: 'Aeroporto', undercover: 'Rodoviária' },
      { civis: 'Hotel', undercover: 'Pousada' },
      { civis: 'Nova York', undercover: 'Londres' },
      { civis: 'Bahia', undercover: 'Pernambuco' },
      { civis: 'Tóquio', undercover: 'Pequim' },
      { civis: 'Salvador', undercover: 'Recife' },
      { civis: 'Florianópolis', undercover: 'Búzios' },
      { civis: 'Lisboa', undercover: 'Porto' },
      { civis: 'Buenos Aires', undercover: 'Santiago' },
      { civis: 'Cancún', undercover: 'Punta Cana' },
      { civis: 'Café', undercover: 'Padaria' },
      { civis: 'Restaurante', undercover: 'Lanchonete' },
      { civis: 'Bar', undercover: 'Boteco' },
      { civis: 'Praça', undercover: 'Calçadão' },
      { civis: 'Estádio', undercover: 'Ginásio' },
      { civis: 'Museu', undercover: 'Biblioteca' },
      { civis: 'Igreja', undercover: 'Templo' },
      { civis: 'Hospital', undercover: 'Clínica' },
      { civis: 'Farmácia', undercover: 'Drogaria' },
      { civis: 'Banco', undercover: 'Caixa Eletrônico' },
      { civis: 'Mercado', undercover: 'Feira Livre' },
      { civis: 'Parque Aquático', undercover: 'Clube' },
      { civis: 'Disney', undercover: 'Universal' },
      { civis: 'Veneza', undercover: 'Amsterdam' },
      { civis: 'Dubai', undercover: 'Cingapura' },
      { civis: 'Cachoeira', undercover: 'Lago' },
      { civis: 'Deserto', undercover: 'Caatinga' },
      { civis: 'Ilha', undercover: 'Península' },
      { civis: 'Vila', undercover: 'Cidade Pequena' },
      { civis: 'Academia', undercover: 'CrossFit Box' },
      { civis: 'Salão de Beleza', undercover: 'Barbearia' },
      { civis: 'Posto de Gasolina', undercover: 'Oficina' },
      { civis: 'Copacabana', undercover: 'Ipanema' },
      { civis: 'Pizzaria', undercover: 'Hamburgueria' },
    ],
  },
  animais: {
    id: 'animais',
    nome: 'Animais',
    emoji: '🦁',
    descricao: 'Bichos conhecidos do reino animal',
    palavras: [
      { civis: 'Cachorro', undercover: 'Gato' },
      { civis: 'Leão', undercover: 'Tigre' },
      { civis: 'Elefante', undercover: 'Hipopótamo' },
      { civis: 'Tubarão', undercover: 'Golfinho' },
      { civis: 'Galinha', undercover: 'Pato' },
      { civis: 'Cavalo', undercover: 'Burro' },
      { civis: 'Cobra', undercover: 'Lagarto' },
      { civis: 'Águia', undercover: 'Falcão' },
      { civis: 'Baleia', undercover: 'Orca' },
      { civis: 'Coelho', undercover: 'Hamster' },
      { civis: 'Vaca', undercover: 'Búfalo' },
      { civis: 'Porco', undercover: 'Javali' },
      { civis: 'Ovelha', undercover: 'Cabra' },
      { civis: 'Macaco', undercover: 'Chimpanzé' },
      { civis: 'Onça', undercover: 'Leopardo' },
      { civis: 'Camelo', undercover: 'Lhama' },
      { civis: 'Girafa', undercover: 'Avestruz' },
      { civis: 'Crocodilo', undercover: 'Jacaré' },
      { civis: 'Sapo', undercover: 'Rã' },
      { civis: 'Polvo', undercover: 'Lula' },
      { civis: 'Aranha', undercover: 'Escorpião' },
      { civis: 'Borboleta', undercover: 'Mariposa' },
      { civis: 'Abelha', undercover: 'Vespa' },
      { civis: 'Formiga', undercover: 'Cupim' },
      { civis: 'Beija-flor', undercover: 'Andorinha' },
      { civis: 'Pinguim', undercover: 'Foca' },
      { civis: 'Urso', undercover: 'Panda' },
      { civis: 'Veado', undercover: 'Alce' },
      { civis: 'Tartaruga', undercover: 'Jabuti' },
      { civis: 'Camaleão', undercover: 'Iguana' },
      { civis: 'Pavão', undercover: 'Galo' },
      { civis: 'Coruja', undercover: 'Morcego' },
      { civis: 'Tucano', undercover: 'Arara' },
      { civis: 'Peixe Dourado', undercover: 'Beta' },
      { civis: 'Cavalo-marinho', undercover: 'Estrela do Mar' },
      { civis: 'Lagosta', undercover: 'Camarão' },
      { civis: 'Rato', undercover: 'Esquilo' },
      { civis: 'Capivara', undercover: 'Paca' },
      { civis: 'Tatu', undercover: 'Tamanduá' },
      { civis: 'Lobo', undercover: 'Coiote' },
      { civis: 'Hiena', undercover: 'Chacal' },
      { civis: 'Canguru', undercover: 'Coala' },
    ],
  },
  esportes: {
    id: 'esportes',
    nome: 'Esportes',
    emoji: '⚽',
    descricao: 'Modalidades esportivas populares no Brasil e no mundo',
    palavras: [
      { civis: 'Futebol', undercover: 'Futsal' },
      { civis: 'Vôlei', undercover: 'Handebol' },
      { civis: 'Basquete', undercover: 'Queimada' },
      { civis: 'Tênis', undercover: 'Squash' },
      { civis: 'Natação', undercover: 'Hidroginástica' },
      { civis: 'Corrida', undercover: 'Caminhada' },
      { civis: 'Boxe', undercover: 'Muay Thai' },
      { civis: 'Surfe', undercover: 'Bodyboard' },
      { civis: 'Ciclismo', undercover: 'Mountain Bike' },
      { civis: 'Judô', undercover: 'Karatê' },
      { civis: 'Vôlei de Praia', undercover: 'Beach Tennis' },
      { civis: 'Skate', undercover: 'Patins' },
      { civis: 'Capoeira', undercover: 'Jiu-jitsu' },
      { civis: 'MMA', undercover: 'Luta Livre' },
      { civis: 'Fórmula 1', undercover: 'Stock Car' },
      { civis: 'BMX', undercover: 'Motocross' },
      { civis: 'Pingue-Pongue', undercover: 'Badminton' },
      { civis: 'Beisebol', undercover: 'Cricket' },
      { civis: 'Golfe', undercover: 'Mini Golfe' },
      { civis: 'Esgrima', undercover: 'Arco e Flecha' },
      { civis: 'Levantamento de Peso', undercover: 'CrossFit' },
      { civis: 'Maratona', undercover: 'Triatlo' },
      { civis: 'Ginástica Olímpica', undercover: 'Ginástica Rítmica' },
      { civis: 'Patinação no Gelo', undercover: 'Patinação Artística' },
      { civis: 'Snowboard', undercover: 'Esqui' },
      { civis: 'Mergulho', undercover: 'Snorkel' },
      { civis: 'Stand Up Paddle', undercover: 'Caiaque' },
      { civis: 'Hipismo', undercover: 'Polo' },
      { civis: 'Hóquei', undercover: 'Lacrosse' },
      { civis: 'Rugby', undercover: 'Futebol Americano' },
      { civis: 'Sinuca', undercover: 'Bilhar' },
      { civis: 'Boliche', undercover: 'Bocha' },
      { civis: 'Pesca', undercover: 'Caça Submarina' },
      { civis: 'Escalada', undercover: 'Rapel' },
      { civis: 'Parkour', undercover: 'Free Running' },
      { civis: 'Xadrez', undercover: 'Damas' },
      { civis: 'Pôquer', undercover: 'Truco' },
      { civis: 'Yoga', undercover: 'Pilates' },
      { civis: 'Dança', undercover: 'Zumba' },
      { civis: 'Karatê', undercover: 'Taekwondo' },
      { civis: 'Wrestling', undercover: 'Sumô' },
      { civis: 'Cross Country', undercover: 'Atletismo' },
    ],
  },
  filmes: {
    id: 'filmes',
    nome: 'Filmes e Séries',
    emoji: '🎬',
    descricao: 'Filmes e séries que todo mundo já ouviu falar',
    palavras: [
      { civis: 'Titanic', undercover: 'Avatar' },
      { civis: 'Vingadores', undercover: 'Liga da Justiça' },
      { civis: 'Toy Story', undercover: 'Procurando Nemo' },
      { civis: 'Senhor dos Anéis', undercover: 'Hobbit' },
      { civis: 'Velozes e Furiosos', undercover: 'Need for Speed' },
      { civis: 'Tropa de Elite', undercover: 'Cidade de Deus' },
      { civis: 'Harry Potter', undercover: 'Crepúsculo' },
      { civis: 'Matrix', undercover: 'Origem' },
      { civis: 'Star Wars', undercover: 'Star Trek' },
      { civis: 'Coringa', undercover: 'Batman' },
      { civis: 'Frozen', undercover: 'Moana' },
      { civis: 'Shrek', undercover: 'Madagascar' },
      { civis: 'Pantera Negra', undercover: 'Capitão América' },
      { civis: 'Os Incríveis', undercover: 'Up - Altas Aventuras' },
      { civis: 'Rei Leão', undercover: 'Tarzan' },
      { civis: 'Carros', undercover: 'Aviões' },
      { civis: 'Kung Fu Panda', undercover: 'Como Treinar Seu Dragão' },
      { civis: 'Forrest Gump', undercover: 'Náufrago' },
      { civis: 'Jurassic Park', undercover: 'King Kong' },
      { civis: 'O Iluminado', undercover: 'Psicose' },
      { civis: 'Truman Show', undercover: 'Pleasantville' },
      { civis: 'Click', undercover: 'De Repente 30' },
      { civis: 'Diabo Veste Prada', undercover: 'Legalmente Loira' },
      { civis: 'La La Land', undercover: 'Whiplash' },
      { civis: 'Pulp Fiction', undercover: 'Cães de Aluguel' },
      { civis: 'Gladiador', undercover: 'Coração Valente' },
      { civis: 'Round 6', undercover: 'La Casa de Papel' },
      { civis: 'Stranger Things', undercover: 'Dark' },
      { civis: 'Breaking Bad', undercover: 'Better Call Saul' },
      { civis: 'The Office', undercover: 'Brooklyn Nine-Nine' },
      { civis: 'Friends', undercover: 'How I Met Your Mother' },
      { civis: 'Game of Thrones', undercover: 'House of the Dragon' },
      { civis: 'The Walking Dead', undercover: 'Fear the Walking Dead' },
      { civis: 'Wandinha', undercover: 'Sabrina' },
      { civis: 'Sex Education', undercover: 'Heartstopper' },
      { civis: 'Bridgerton', undercover: 'The Crown' },
      { civis: 'Lupin', undercover: 'Mentes Criminosas' },
      { civis: 'Avatar 2', undercover: 'Aquaman' },
      { civis: 'Homem-Aranha', undercover: 'Demolidor' },
      { civis: 'Encanto', undercover: 'Vaiana' },
      { civis: 'Vingadores Ultimato', undercover: 'Guerra Infinita' },
      { civis: 'Pacificador', undercover: 'Esquadrão Suicida' },
    ],
  },
  festas: {
    id: 'festas',
    nome: 'Festas',
    emoji: '🎉',
    descricao: 'Celebrações, eventos e comemorações',
    palavras: [
      { civis: 'Carnaval', undercover: 'São João' },
      { civis: 'Réveillon', undercover: 'Aniversário' },
      { civis: 'Halloween', undercover: 'Festa à Fantasia' },
      { civis: 'Casamento', undercover: 'Noivado' },
      { civis: 'Festa Junina', undercover: 'Festa Julina' },
      { civis: 'Formatura', undercover: 'Despedida de Solteiro' },
      { civis: 'Show', undercover: 'Festival' },
      { civis: 'Churrasco', undercover: 'Luau' },
      { civis: 'Chá de Bebê', undercover: 'Chá Revelação' },
      { civis: 'Páscoa', undercover: 'Natal' },
      { civis: 'Open Bar', undercover: 'Open Food' },
      { civis: 'Festa de 15 Anos', undercover: 'Bodas de Prata' },
      { civis: 'Festa do Pijama', undercover: 'Sleepover' },
      { civis: 'Pré-Wedding', undercover: 'Save the Date' },
      { civis: 'Bloquinho de Rua', undercover: 'Camarote' },
      { civis: 'Rave', undercover: 'Balada' },
      { civis: 'Festa em Casa', undercover: 'Festa em Sítio' },
      { civis: 'Confraternização', undercover: 'Happy Hour' },
      { civis: 'Festa na Piscina', undercover: 'Festa na Cobertura' },
      { civis: 'Almoço de Domingo', undercover: 'Brunch' },
      { civis: 'Coquetel', undercover: 'Recepção' },
      { civis: 'Festa Temática', undercover: 'Festa Cosplay' },
      { civis: 'Festa Surpresa', undercover: 'Despedida' },
      { civis: 'Festa Infantil', undercover: 'Festa Adulta' },
      { civis: 'Amigo Secreto', undercover: 'Amigo da Onça' },
      { civis: 'Bingo', undercover: 'Karaokê' },
      { civis: 'Reveillon na Praia', undercover: 'Reveillon em Casa' },
      { civis: 'Halloween Adulto', undercover: 'Halloween Infantil' },
      { civis: 'Bar Mitzvah', undercover: 'Primeira Comunhão' },
      { civis: 'After Party', undercover: 'Esquenta' },
      { civis: 'Festa Hawaiana', undercover: 'Festa Mexicana' },
      { civis: 'Festa Anos 80', undercover: 'Festa Anos 90' },
      { civis: 'Festa do Vinho', undercover: 'Festa da Cerveja' },
      { civis: 'Festa Brega', undercover: 'Festa Funk' },
      { civis: 'Festa Eletrônica', undercover: 'Festa Sertaneja' },
      { civis: 'Despedida de Solteira', undercover: 'Despedida de Solteiro' },
      { civis: 'Casamento na Praia', undercover: 'Casamento no Campo' },
      { civis: 'Batizado', undercover: 'Crisma' },
      { civis: 'Formatura do Ensino Médio', undercover: 'Formatura da Faculdade' },
      { civis: 'Confraternização de Empresa', undercover: 'Festa do Trabalho' },
      { civis: 'Casamento Civil', undercover: 'Casamento Religioso' },
      { civis: 'Aniversário Infantil', undercover: 'Aniversário de 18 anos' },
    ],
  },
  bebidas: {
    id: 'bebidas',
    nome: 'Bebidas',
    emoji: '🍻',
    descricao: 'Bebidas geladas, quentes, alcoólicas e refrescos',
    palavras: [
      { civis: 'Caipirinha', undercover: 'Mojito' },
      { civis: 'Cerveja', undercover: 'Chopp' },
      { civis: 'Vinho', undercover: 'Champanhe' },
      { civis: 'Café', undercover: 'Cappuccino' },
      { civis: 'Suco', undercover: 'Refrigerante' },
      { civis: 'Água', undercover: 'Água com Gás' },
      { civis: 'Uísque', undercover: 'Vodka' },
      { civis: 'Coquetel', undercover: 'Drink' },
      { civis: 'Caldo de Cana', undercover: 'Água de Coco' },
      { civis: 'Chimarrão', undercover: 'Chá' },
      { civis: 'Coca-Cola', undercover: 'Guaraná' },
      { civis: 'Sprite', undercover: 'Fanta' },
      { civis: 'Suco de Laranja', undercover: 'Suco de Uva' },
      { civis: 'Vinho Tinto', undercover: 'Vinho Branco' },
      { civis: 'Caipiroska', undercover: 'Caipifruta' },
      { civis: 'Tequila', undercover: 'Mezcal' },
      { civis: 'Rum', undercover: 'Cachaça' },
      { civis: 'Espresso', undercover: 'Americano' },
      { civis: 'Latte', undercover: 'Macchiato' },
      { civis: 'Piña Colada', undercover: 'Daiquiri' },
      { civis: 'Margarita', undercover: 'Margarita Frozen' },
      { civis: 'Aperol Spritz', undercover: 'Hugo Spritz' },
      { civis: 'Gin Tônica', undercover: 'Gin Fizz' },
      { civis: 'Cuba Libre', undercover: 'Cuba Light' },
      { civis: 'Bloody Mary', undercover: 'Tom Collins' },
      { civis: 'Energético', undercover: 'Isotônico' },
      { civis: 'Chá Verde', undercover: 'Chá Preto' },
      { civis: 'Chá Mate', undercover: 'Chá Gelado' },
      { civis: 'Iced Coffee', undercover: 'Cold Brew' },
      { civis: 'Smoothie', undercover: 'Vitamina' },
      { civis: 'Suco Detox', undercover: 'Suco Verde' },
      { civis: 'Leite com Achocolatado', undercover: 'Leite com Café' },
      { civis: 'Caipirinha de Limão', undercover: 'Caipirinha de Morango' },
      { civis: 'Sake', undercover: 'Soju' },
      { civis: 'Licor', undercover: 'Aperitivo' },
      { civis: 'Champagne', undercover: 'Prosecco' },
      { civis: 'Cerveja Pilsen', undercover: 'Cerveja IPA' },
      { civis: 'Cerveja Artesanal', undercover: 'Cerveja Industrial' },
      { civis: 'Refrigerante de Cola', undercover: 'Refrigerante de Laranja' },
      { civis: 'Limonada', undercover: 'Suco de Maracujá' },
      { civis: 'Quentão', undercover: 'Vinho Quente' },
      { civis: 'Mate Leão', undercover: 'Chá de Camomila' },
    ],
  },
  celebridades: {
    id: 'celebridades',
    nome: 'Celebridades',
    emoji: '🌟',
    descricao: 'Famosos brasileiros e internacionais',
    palavras: [
      { civis: 'Anitta', undercover: 'Pabllo Vittar' },
      { civis: 'Neymar', undercover: 'Vinicius Júnior' },
      { civis: 'Ronaldo Fenômeno', undercover: 'Romário' },
      { civis: 'Pelé', undercover: 'Maradona' },
      { civis: 'Xuxa', undercover: 'Eliana' },
      { civis: 'Faustão', undercover: 'Silvio Santos' },
      { civis: 'Caetano Veloso', undercover: 'Gilberto Gil' },
      { civis: 'Roberto Carlos', undercover: 'Erasmo Carlos' },
      { civis: 'Luan Santana', undercover: 'Gusttavo Lima' },
      { civis: 'Marília Mendonça', undercover: 'Maiara e Maraisa' },
      { civis: 'Wesley Safadão', undercover: 'Henrique e Juliano' },
      { civis: 'Ivete Sangalo', undercover: 'Claudia Leitte' },
      { civis: 'Jô Soares', undercover: 'Pedro Bial' },
      { civis: 'Bruno Mars', undercover: 'Ed Sheeran' },
      { civis: 'Beyoncé', undercover: 'Rihanna' },
      { civis: 'Lady Gaga', undercover: 'Madonna' },
      { civis: 'Taylor Swift', undercover: 'Selena Gomez' },
      { civis: 'Justin Bieber', undercover: 'Shawn Mendes' },
      { civis: 'Kim Kardashian', undercover: 'Kylie Jenner' },
      { civis: 'Ariana Grande', undercover: 'Demi Lovato' },
      { civis: 'Cristiano Ronaldo', undercover: 'Lionel Messi' },
      { civis: 'LeBron James', undercover: 'Stephen Curry' },
      { civis: 'Drake', undercover: 'Kanye West' },
      { civis: 'Ryan Reynolds', undercover: 'Hugh Jackman' },
      { civis: 'Tom Cruise', undercover: 'Brad Pitt' },
      { civis: 'Leonardo DiCaprio', undercover: 'Matt Damon' },
      { civis: 'Will Smith', undercover: 'Denzel Washington' },
      { civis: 'Sandra Bullock', undercover: 'Jennifer Aniston' },
      { civis: 'Whindersson Nunes', undercover: 'Felipe Neto' },
      { civis: 'Casimiro', undercover: 'Cellbit' },
      { civis: 'Tata Werneck', undercover: 'Paolla Oliveira' },
      { civis: 'Sabrina Sato', undercover: 'Eliana' },
      { civis: 'Boninho', undercover: 'Tadeu Schmidt' },
      { civis: 'Gretchen', undercover: 'Inês Brasil' },
      { civis: 'Pedro Pascal', undercover: 'Oscar Isaac' },
    ],
  },
  musicas: {
    id: 'musicas',
    nome: 'Música',
    emoji: '🎵',
    descricao: 'Estilos musicais e artistas conhecidos',
    palavras: [
      { civis: 'Sertanejo', undercover: 'Pagode' },
      { civis: 'Funk Carioca', undercover: 'Funk Paulista' },
      { civis: 'Forró', undercover: 'Xote' },
      { civis: 'Bossa Nova', undercover: 'MPB' },
      { civis: 'Samba', undercover: 'Choro' },
      { civis: 'Rock', undercover: 'Pop Rock' },
      { civis: 'Pop', undercover: 'Indie Pop' },
      { civis: 'Reggae', undercover: 'Reggaeton' },
      { civis: 'Hip Hop', undercover: 'Trap' },
      { civis: 'Eletrônica', undercover: 'House' },
      { civis: 'K-Pop', undercover: 'J-Pop' },
      { civis: 'R&B', undercover: 'Soul' },
      { civis: 'Country', undercover: 'Folk' },
      { civis: 'Jazz', undercover: 'Blues' },
      { civis: 'Música Clássica', undercover: 'Música Erudita' },
      { civis: 'Axé', undercover: 'Pagode Baiano' },
      { civis: 'Brega Funk', undercover: 'Piseiro' },
      { civis: 'Tecno Brega', undercover: 'Tecno Forró' },
      { civis: 'Sertanejo Universitário', undercover: 'Sertanejo Raiz' },
      { civis: 'Samba Jazz', undercover: 'Samba Rock' },
      { civis: 'BTS', undercover: 'BLACKPINK' },
      { civis: 'Beatles', undercover: 'Rolling Stones' },
      { civis: 'Maroon 5', undercover: 'Imagine Dragons' },
      { civis: 'Coldplay', undercover: 'U2' },
      { civis: 'Queen', undercover: 'Led Zeppelin' },
      { civis: 'Michael Jackson', undercover: 'Prince' },
      { civis: 'Madonna', undercover: 'Cher' },
      { civis: 'Skank', undercover: 'Jota Quest' },
      { civis: 'Charlie Brown Jr', undercover: 'Cidade Negra' },
      { civis: 'Legião Urbana', undercover: 'Os Paralamas' },
      { civis: 'Cazuza', undercover: 'Renato Russo' },
      { civis: 'Tim Maia', undercover: 'Jorge Ben Jor' },
      { civis: 'Djavan', undercover: 'Lulu Santos' },
      { civis: 'Marisa Monte', undercover: 'Daniela Mercury' },
      { civis: 'Luísa Sonza', undercover: 'Lexa' },
    ],
  },
  memes: {
    id: 'memes',
    nome: 'Memes',
    emoji: '😂',
    descricao: 'Expressões e referências da internet brasileira',
    palavras: [
      { civis: 'Sextou', undercover: 'Quintou' },
      { civis: 'KKKKKK', undercover: 'AHAHAH' },
      { civis: 'Print disso', undercover: 'Stalker' },
      { civis: 'Bom dia, flor do dia', undercover: 'Boa noite, sonhe com os anjos' },
      { civis: 'Crush', undercover: 'Pessoa Especial' },
      { civis: 'Cancelado', undercover: 'Lacrado' },
      { civis: 'Surtei', undercover: 'Pirei' },
      { civis: 'Tô passada', undercover: 'Tô chocada' },
      { civis: 'Aff', undercover: 'Eita' },
      { civis: 'Vish', undercover: 'Ixi' },
      { civis: 'Para tudo', undercover: 'Calma lá' },
      { civis: 'Aham, sei', undercover: 'Tá certo, tá' },
      { civis: 'Bora?', undercover: 'Vamos?' },
      { civis: 'Tô fora', undercover: 'Tô dentro' },
      { civis: 'Vacilão', undercover: 'Otário' },
      { civis: 'Pisei na bola', undercover: 'Vacilei' },
      { civis: 'Slay', undercover: 'Arrasou' },
      { civis: 'POV', undercover: 'Imagine' },
      { civis: 'Trend do TikTok', undercover: 'Viral do Insta' },
      { civis: 'Story do Insta', undercover: 'Reels do Insta' },
      { civis: 'Tá ligado?', undercover: 'Sacou?' },
      { civis: 'Vai aprender', undercover: 'Vai estudar' },
      { civis: 'Tô morto', undercover: 'Tô morrendo' },
      { civis: 'Brilhou', undercover: 'Estourou' },
      { civis: 'Mano, tá doido', undercover: 'Bicho, tá maluco' },
      { civis: 'Não vou mentir', undercover: 'Pra ser sincero' },
      { civis: 'Acabou Jéssica', undercover: 'Acabou Mariazinha' },
      { civis: 'Galera', undercover: 'Turma' },
      { civis: 'Tá um arraso', undercover: 'Tá uma diva' },
      { civis: 'Maravilhosa', undercover: 'Estonteante' },
      { civis: 'Surreal', undercover: 'Inacreditável' },
      { civis: 'Tipo, sabe?', undercover: 'Tipo, assim' },
      { civis: 'Vrau', undercover: 'Tchau' },
      { civis: 'Foi mal', undercover: 'Desculpa aí' },
      { civis: 'Tá osso', undercover: 'Tá lascado' },
    ],
  },
  profissoes: {
    id: 'profissoes',
    nome: 'Profissões',
    emoji: '👔',
    descricao: 'Profissões e ofícios do dia a dia',
    palavras: [
      { civis: 'Médico', undercover: 'Enfermeiro' },
      { civis: 'Professor', undercover: 'Pedagogo' },
      { civis: 'Advogado', undercover: 'Juiz' },
      { civis: 'Engenheiro', undercover: 'Arquiteto' },
      { civis: 'Dentista', undercover: 'Ortodontista' },
      { civis: 'Bombeiro', undercover: 'Policial' },
      { civis: 'Cozinheiro', undercover: 'Chef de Cozinha' },
      { civis: 'Motorista de Ônibus', undercover: 'Motorista de Caminhão' },
      { civis: 'Padeiro', undercover: 'Confeiteiro' },
      { civis: 'Carpinteiro', undercover: 'Marceneiro' },
      { civis: 'Pintor', undercover: 'Decorador' },
      { civis: 'Eletricista', undercover: 'Encanador' },
      { civis: 'Mecânico', undercover: 'Funileiro' },
      { civis: 'Vendedor', undercover: 'Atendente' },
      { civis: 'Garçom', undercover: 'Recepcionista' },
      { civis: 'Programador', undercover: 'Designer' },
      { civis: 'Jornalista', undercover: 'Escritor' },
      { civis: 'Fotógrafo', undercover: 'Cinegrafista' },
      { civis: 'Cantor', undercover: 'Compositor' },
      { civis: 'Ator', undercover: 'Apresentador' },
      { civis: 'Maquiador', undercover: 'Cabeleireiro' },
      { civis: 'Estilista', undercover: 'Costureira' },
      { civis: 'Cientista', undercover: 'Pesquisador' },
      { civis: 'Veterinário', undercover: 'Biólogo' },
      { civis: 'Psicólogo', undercover: 'Psiquiatra' },
      { civis: 'Nutricionista', undercover: 'Dietista' },
      { civis: 'Fisioterapeuta', undercover: 'Massagista' },
      { civis: 'Salva-vidas', undercover: 'Mergulhador de Resgate' },
      { civis: 'Personal Trainer', undercover: 'Educador Físico' },
      { civis: 'Faxineiro', undercover: 'Zelador' },
      { civis: 'Babá', undercover: 'Cuidador de Idoso' },
      { civis: 'Piloto', undercover: 'Comissário de Voo' },
      { civis: 'Jardineiro', undercover: 'Paisagista' },
      { civis: 'Agricultor', undercover: 'Pecuarista' },
      { civis: 'Pescador', undercover: 'Marinheiro' },
    ],
  },
  objetos: {
    id: 'objetos',
    nome: 'Objetos',
    emoji: '📱',
    descricao: 'Objetos do cotidiano que todo mundo usa',
    palavras: [
      { civis: 'Celular', undercover: 'Tablet' },
      { civis: 'Computador', undercover: 'Notebook' },
      { civis: 'Televisão', undercover: 'Monitor' },
      { civis: 'Geladeira', undercover: 'Freezer' },
      { civis: 'Micro-ondas', undercover: 'Forno' },
      { civis: 'Sofá', undercover: 'Poltrona' },
      { civis: 'Cama', undercover: 'Beliche' },
      { civis: 'Mesa', undercover: 'Escrivaninha' },
      { civis: 'Cadeira', undercover: 'Banco' },
      { civis: 'Cobertor', undercover: 'Edredom' },
      { civis: 'Travesseiro', undercover: 'Almofada' },
      { civis: 'Caneta', undercover: 'Lápis' },
      { civis: 'Caderno', undercover: 'Agenda' },
      { civis: 'Livro', undercover: 'Revista' },
      { civis: 'Chave', undercover: 'Cadeado' },
      { civis: 'Carteira', undercover: 'Bolsa' },
      { civis: 'Mochila', undercover: 'Pasta' },
      { civis: 'Guarda-chuva', undercover: 'Sombrinha' },
      { civis: 'Óculos', undercover: 'Lentes de Contato' },
      { civis: 'Relógio', undercover: 'Cronômetro' },
      { civis: 'Carregador', undercover: 'Power Bank' },
      { civis: 'Fone de Ouvido', undercover: 'Caixa de Som' },
      { civis: 'Vassoura', undercover: 'Rodo' },
      { civis: 'Pano de Chão', undercover: 'Esfregão' },
      { civis: 'Aspirador', undercover: 'Pano de Pó' },
      { civis: 'Liquidificador', undercover: 'Mixer' },
      { civis: 'Panela', undercover: 'Frigideira' },
      { civis: 'Talher', undercover: 'Hashi' },
      { civis: 'Copo', undercover: 'Caneca' },
      { civis: 'Prato', undercover: 'Tigela' },
      { civis: 'Garrafa', undercover: 'Térmica' },
      { civis: 'Espelho', undercover: 'Lupa' },
      { civis: 'Escova de Dente', undercover: 'Fio Dental' },
      { civis: 'Sabonete', undercover: 'Shampoo' },
      { civis: 'Toalha', undercover: 'Roupão' },
    ],
  },
  sentimentos: {
    id: 'sentimentos',
    nome: 'Sentimentos',
    emoji: '💭',
    descricao: 'Emoções e estados de espírito',
    palavras: [
      { civis: 'Felicidade', undercover: 'Alegria' },
      { civis: 'Tristeza', undercover: 'Melancolia' },
      { civis: 'Raiva', undercover: 'Fúria' },
      { civis: 'Medo', undercover: 'Pavor' },
      { civis: 'Amor', undercover: 'Paixão' },
      { civis: 'Ódio', undercover: 'Antipatia' },
      { civis: 'Vergonha', undercover: 'Constrangimento' },
      { civis: 'Ciúme', undercover: 'Inveja' },
      { civis: 'Ansiedade', undercover: 'Nervosismo' },
      { civis: 'Calma', undercover: 'Tranquilidade' },
      { civis: 'Surpresa', undercover: 'Susto' },
      { civis: 'Empolgação', undercover: 'Animação' },
      { civis: 'Saudade', undercover: 'Nostalgia' },
      { civis: 'Frustração', undercover: 'Decepção' },
      { civis: 'Esperança', undercover: 'Fé' },
      { civis: 'Orgulho', undercover: 'Vaidade' },
      { civis: 'Gratidão', undercover: 'Reconhecimento' },
      { civis: 'Tédio', undercover: 'Cansaço' },
      { civis: 'Solidão', undercover: 'Isolamento' },
      { civis: 'Confusão', undercover: 'Incerteza' },
      { civis: 'Curiosidade', undercover: 'Interesse' },
      { civis: 'Carinho', undercover: 'Afeto' },
      { civis: 'Desprezo', undercover: 'Desdém' },
      { civis: 'Compaixão', undercover: 'Pena' },
      { civis: 'Coragem', undercover: 'Bravura' },
      { civis: 'Covardia', undercover: 'Receio' },
      { civis: 'Confiança', undercover: 'Autoestima' },
      { civis: 'Insegurança', undercover: 'Dúvida' },
      { civis: 'Empatia', undercover: 'Simpatia' },
      { civis: 'Indignação', undercover: 'Revolta' },
      { civis: 'Euforia', undercover: 'Êxtase' },
      { civis: 'Apatia', undercover: 'Desânimo' },
      { civis: 'Admiração', undercover: 'Inspiração' },
      { civis: 'Realização', undercover: 'Plenitude' },
      { civis: 'Angústia', undercover: 'Aflição' },
    ],
  },
  aplicativos: {
    id: 'aplicativos',
    nome: 'Aplicativos',
    emoji: '📲',
    descricao: 'Apps e redes sociais que todo mundo tem no celular',
    palavras: [
      { civis: 'Instagram', undercover: 'TikTok' },
      { civis: 'WhatsApp', undercover: 'Telegram' },
      { civis: 'Facebook', undercover: 'Twitter' },
      { civis: 'YouTube', undercover: 'Twitch' },
      { civis: 'Spotify', undercover: 'Deezer' },
      { civis: 'Netflix', undercover: 'Disney+' },
      { civis: 'iFood', undercover: 'Rappi' },
      { civis: 'Uber', undercover: '99' },
      { civis: 'Tinder', undercover: 'Bumble' },
      { civis: 'PicPay', undercover: 'Mercado Pago' },
      { civis: 'Nubank', undercover: 'Inter' },
      { civis: 'Globoplay', undercover: 'HBO Max' },
      { civis: 'Prime Video', undercover: 'Apple TV+' },
      { civis: 'Mercado Livre', undercover: 'Amazon' },
      { civis: 'Shopee', undercover: 'AliExpress' },
      { civis: 'Google Maps', undercover: 'Waze' },
      { civis: 'Discord', undercover: 'Slack' },
      { civis: 'Zoom', undercover: 'Google Meet' },
      { civis: 'Snapchat', undercover: 'BeReal' },
      { civis: 'Pinterest', undercover: 'Tumblr' },
      { civis: 'LinkedIn', undercover: 'InfoJobs' },
      { civis: 'Strava', undercover: 'Nike Run Club' },
      { civis: 'Duolingo', undercover: 'Babbel' },
      { civis: 'Notion', undercover: 'Trello' },
      { civis: 'Canva', undercover: 'Figma' },
      { civis: 'Audible', undercover: 'Storytel' },
      { civis: 'Steam', undercover: 'Epic Games' },
      { civis: 'Reddit', undercover: '9GAG' },
      { civis: 'Threads', undercover: 'Mastodon' },
      { civis: 'Enjoei', undercover: 'OLX' },
      { civis: 'Airbnb', undercover: 'Booking' },
      { civis: 'UberEats', undercover: 'iFood' },
      { civis: 'Google Drive', undercover: 'Dropbox' },
      { civis: 'Gmail', undercover: 'Outlook' },
      { civis: 'Apple Music', undercover: 'Tidal' },
    ],
  },
};

export const LISTA_CATEGORIAS: Categoria[] = Object.values(CATEGORIAS);
