import type { Carta } from '@/games/na-ponta-da-lingua/types';

/**
 * 228 cartas — Na Ponta da Língua.
 *
 * As palavras proibidas bloqueiam os CAMINHOS COGNITIVOS NATURAIS —
 * não apenas sinônimos óbvios, mas os atalhos mentais que você usaria
 * nos primeiros 5 segundos. O objetivo é travar o cérebro.
 *
 * Regra de ouro: se você fosse explicar a palavra em 5 segundos,
 * essas são as 5 primeiras rotas que seu cérebro tentaria.
 */
export const CARTAS: ReadonlyArray<Carta> = [

  // ══════════════════════════════════════════════════════════════════════
  // INTERNET BR — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'ib01',
    palavra: 'Meme',
    proibidas: ['viral', 'engraçado', 'internet', 'imagem', 'compartilhar'],
    categoria: 'internet_br',
    dificuldade: 'facil',
    tipo: 'brainrot',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'ib02',
    palavra: 'Print de tela',
    proibidas: ['captura', 'screenshot', 'tela', 'foto', 'celular'],
    categoria: 'internet_br',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'ib03',
    palavra: 'Stories',
    proibidas: ['Instagram', 'foto', 'vídeo', 'publicar', 'expirar'],
    categoria: 'internet_br',
    dificuldade: 'facil',
    tipo: 'meme_contemporaneo',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ib04',
    palavra: 'Figurinha do Zap',
    proibidas: ['sticker', 'WhatsApp', 'enviar', 'chat', 'emoji'],
    categoria: 'internet_br',
    dificuldade: 'facil',
    tipo: 'meme_contemporaneo',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ib05',
    palavra: 'Influencer',
    proibidas: ['seguidor', 'Instagram', 'marca', 'patrocínio', 'conteúdo'],
    categoria: 'internet_br',
    dificuldade: 'medio',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.70,
  },
  {
    id: 'ib06',
    palavra: 'Fake News',
    proibidas: ['mentira', 'notícia', 'falsa', 'WhatsApp', 'viral'],
    categoria: 'internet_br',
    dificuldade: 'facil',
    tipo: 'brainrot',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'ib07',
    palavra: 'Live',
    proibidas: ['ao vivo', 'transmissão', 'streaming', 'celular', 'redes'],
    categoria: 'internet_br',
    dificuldade: 'facil',
    tipo: 'meme_contemporaneo',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ib08',
    palavra: 'Cancelamento',
    proibidas: ['polêmica', 'internet', 'famoso', 'redes', 'boicote'],
    categoria: 'internet_br',
    dificuldade: 'medio',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'ib09',
    palavra: 'TBT',
    proibidas: ['passado', 'foto', 'antiga', 'nostalgia', 'postar'],
    categoria: 'internet_br',
    dificuldade: 'medio',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.70,
  },
  {
    id: 'ib10',
    palavra: 'Algoritmo',
    proibidas: ['sugestão', 'feed', 'vídeo', 'app', 'mostrar'],
    categoria: 'internet_br',
    dificuldade: 'dificil',
    tipo: 'caos_mental',
    energiaEmocional: 3,
    velocidadeCognitiva: 2,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.40,
  },
  {
    id: 'ib11',
    palavra: 'Reels',
    proibidas: ['vídeo', 'Instagram', 'curto', 'rolar', 'conteúdo'],
    categoria: 'internet_br',
    dificuldade: 'facil',
    tipo: 'meme_contemporaneo',
    energiaEmocional: 1,
    velocidadeCognitiva: 5,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ib12',
    palavra: 'Stalkar',
    proibidas: ['espreitar', 'perfil', 'foto', 'bisbilhotar', 'visualizar'],
    categoria: 'internet_br',
    dificuldade: 'medio',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.60,
  },

  // ══════════════════════════════════════════════════════════════════════
  // COTIDIANO — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'co01',
    palavra: 'Ressaca',
    proibidas: ['beber', 'dor', 'cabeça', 'álcool', 'manhã'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
    tipo: 'memoria_afetiva',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'co02',
    palavra: 'Delivery',
    proibidas: ['pedir', 'comida', 'motoboy', 'aplicativo', 'entregar'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'co03',
    palavra: 'Pix',
    proibidas: ['transferência', 'dinheiro', 'banco', 'celular', 'pagar'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 5,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'co04',
    palavra: 'Fila do banco',
    proibidas: ['esperar', 'lento', 'banco', 'vez', 'paciência'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 2,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'co05',
    palavra: 'Trânsito',
    proibidas: ['buzina', 'motorista', 'sinal', 'semáforo', 'pare'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
    tipo: 'caos_urbano',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'co06',
    palavra: 'Soneca',
    proibidas: ['dormir', 'breve', 'tarde', 'cama', 'descanso'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'co07',
    palavra: 'Promoção relâmpago',
    proibidas: ['desconto', 'barato', 'oferta', 'comprar', 'preço'],
    categoria: 'cotidiano',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.65,
  },
  {
    id: 'co08',
    palavra: 'Reunião inútil',
    proibidas: ['trabalho', 'zoom', 'empresa', 'perder', 'desnecessária'],
    categoria: 'cotidiano',
    dificuldade: 'medio',
    tipo: 'caos_corporativo',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.65,
  },
  {
    id: 'co09',
    palavra: 'Marmita',
    proibidas: ['comida', 'trabalho', 'pote', 'levar', 'almoço'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'co10',
    palavra: 'Procrastinar',
    proibidas: ['deixar', 'amanhã', 'postergar', 'preguiça', 'depois'],
    categoria: 'cotidiano',
    dificuldade: 'medio',
    tipo: 'caos_mental',
    energiaEmocional: 2,
    velocidadeCognitiva: 2,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'co11',
    palavra: 'Boleto vencido',
    proibidas: ['vencer', 'juros', 'segunda via', 'prazo', 'esqueceu'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'co12',
    palavra: 'Vizinho barulhento',
    proibidas: ['barulho', 'apartamento', 'noite', 'reclamar', 'prédio'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },

  // ══════════════════════════════════════════════════════════════════════
  // COMIDA — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'cm01',
    palavra: 'Coxinha',
    proibidas: ['frango', 'frito', 'massa', 'salgado', 'festa'],
    categoria: 'comida',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 5,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'cm02',
    palavra: 'Brigadeiro',
    proibidas: ['chocolate', 'bola', 'leite', 'doce', 'festa'],
    categoria: 'comida',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 5,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.90,
  },
  {
    id: 'cm03',
    palavra: 'Açaí',
    proibidas: ['roxo', 'gelado', 'frutas', 'tigela', 'norte'],
    categoria: 'comida',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 5,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'cm04',
    palavra: 'Churrasco',
    proibidas: ['domingo', 'carvão', 'cerveja', 'fumaça', 'assar'],
    categoria: 'comida',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cm05',
    palavra: 'Pão de queijo',
    proibidas: ['queijo', 'forno', 'mineiro', 'pequeno', 'massa'],
    categoria: 'comida',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 5,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'cm06',
    palavra: 'Pastel de feira',
    proibidas: ['fritar', 'feira', 'massa', 'recheio', 'quente'],
    categoria: 'comida',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cm07',
    palavra: 'Tapioca',
    proibidas: ['nordeste', 'mandioca', 'massa', 'café', 'fino'],
    categoria: 'comida',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cm08',
    palavra: 'Caipirinha',
    proibidas: ['limão', 'cachaça', 'açúcar', 'bebida', 'coquetel'],
    categoria: 'comida',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 5,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'cm09',
    palavra: 'Guaraná Antarctica',
    proibidas: ['refrigerante', 'bebida', 'verde', 'nacional', 'doce'],
    categoria: 'comida',
    dificuldade: 'medio',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.70,
  },
  {
    id: 'cm10',
    palavra: 'Pudim de leite',
    proibidas: ['doce', 'leite', 'forno', 'calda', 'gelatinoso'],
    categoria: 'comida',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cm11',
    palavra: 'Feijão tropeiro',
    proibidas: ['feijão', 'farinha', 'mineiro', 'bacon', 'misturar'],
    categoria: 'comida',
    dificuldade: 'medio',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'cm12',
    palavra: 'Galinha caipira',
    proibidas: ['frango', 'roça', 'carne', 'interior', 'cozinhar'],
    categoria: 'comida',
    dificuldade: 'medio',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.60,
  },

  // ══════════════════════════════════════════════════════════════════════
  // CULTURA POP — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'cp01',
    palavra: 'BBB',
    proibidas: ['reality', 'Globo', 'paredão', 'eliminação', 'confinamento'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cp02',
    palavra: 'Funk carioca',
    proibidas: ['baile', 'ritmo', 'dançar', 'favela', 'música'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'cp03',
    palavra: 'Carnaval',
    proibidas: ['fantasia', 'samba', 'confete', 'bloco', 'desfile'],
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
    categoria: 'cultura_pop',
    dificuldade: 'facil',
  },
  {
    id: 'cp04',
    palavra: 'Novela da Globo',
    proibidas: ['televisão', 'Globo', 'casal', 'capítulo', 'traição'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cp05',
    palavra: 'Pagode',
    proibidas: ['roda', 'violão', 'samba', 'cerveja', 'amigos'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cp06',
    palavra: 'TikToker',
    proibidas: ['vídeo', 'dança', 'jovem', 'viral', 'app'],
    categoria: 'cultura_pop',
    dificuldade: 'medio',
    tipo: 'meme_contemporaneo',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.65,
  },
  {
    id: 'cp07',
    palavra: 'Podcast',
    proibidas: ['áudio', 'episódio', 'ouvir', 'entrevista', 'microfone'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
    tipo: 'caos_corporativo',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cp08',
    palavra: 'Sertanejo universitário',
    proibidas: ['dupla', 'música', 'amor', 'chapéu', 'rodeio'],
    categoria: 'cultura_pop',
    dificuldade: 'medio',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.65,
  },
  {
    id: 'cp09',
    palavra: 'Forró',
    proibidas: ['dançar', 'nordeste', 'sanfona', 'par', 'ritmo'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cp10',
    palavra: 'Reality show',
    proibidas: ['televisão', 'programa', 'competição', 'câmera', 'eliminação'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cp11',
    palavra: 'Crossfit',
    proibidas: ['academia', 'treino', 'exercício', 'pesado', 'forte'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cp12',
    palavra: 'Ostentação',
    proibidas: ['rico', 'carro', 'dinheiro', 'exibir', 'luxo'],
    categoria: 'cultura_pop',
    dificuldade: 'medio',
    tipo: 'cultura_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },

  // ══════════════════════════════════════════════════════════════════════
  // OBJETOS — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'ob01',
    palavra: 'Chinelo',
    proibidas: ['pé', 'sandália', 'Havaianas', 'borracha', 'chinelada'],
    categoria: 'objetos',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 5,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.90,
  },
  {
    id: 'ob02',
    palavra: 'Isopor de cerveja',
    proibidas: ['caixa', 'bebida', 'branco', 'frio', 'praia'],
    categoria: 'objetos',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'ob03',
    palavra: 'Ventilador',
    proibidas: ['brisa', 'fresquinho', 'hélice', 'parede', 'pá'],
    categoria: 'objetos',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ob04',
    palavra: 'Botijão de gás',
    proibidas: ['gás', 'laranja', 'cozinha', 'fogão', 'trocar'],
    categoria: 'objetos',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ob05',
    palavra: 'Panela de pressão',
    proibidas: ['vapor', 'barulho', 'feijão', 'cozinhar', 'tampa'],
    categoria: 'objetos',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ob06',
    palavra: 'Chuveiro elétrico',
    proibidas: ['choque', 'pressão', 'morno', 'torneira', 'duchas'],
    categoria: 'objetos',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'ob07',
    palavra: 'Varal de roupa',
    proibidas: ['corda', 'prendedor', 'área', 'quintal', 'meia'],
    categoria: 'objetos',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ob08',
    palavra: 'Extintor de incêndio',
    proibidas: ['emergência', 'bombeiro', 'parede', 'extinguir', 'pressão'],
    categoria: 'objetos',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ob09',
    palavra: 'Máquina de lavar',
    proibidas: ['ciclo', 'centrifugar', 'programa', 'barulho', 'espuma'],
    categoria: 'objetos',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ob10',
    palavra: 'Mata-mosquito elétrico',
    proibidas: ['mosquito', 'matar', 'elétrico', 'luz', 'roxo'],
    categoria: 'objetos',
    dificuldade: 'medio',
    tipo: 'visual_imediata',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.65,
  },
  {
    id: 'ob11',
    palavra: 'Garrafa de cachaça',
    proibidas: ['cana', 'destilado', 'pinga', 'dose', 'rótulo'],
    categoria: 'objetos',
    dificuldade: 'medio',
    tipo: 'visual_imediata',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'ob12',
    palavra: 'Cadeado',
    proibidas: ['fechar', 'chave', 'travar', 'segurança', 'abrir'],
    categoria: 'objetos',
    dificuldade: 'medio',
    tipo: 'visual_imediata',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.60,
  },

  // ══════════════════════════════════════════════════════════════════════
  // PROFISSOES — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'pr01',
    palavra: 'Motorista de aplicativo',
    proibidas: ['carro', 'aplicativo', 'passageiro', 'corrida', 'avaliar'],
    categoria: 'profissoes',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'pr02',
    palavra: 'Motoboy',
    proibidas: ['moto', 'entrega', 'rua', 'rápido', 'chuva'],
    categoria: 'profissoes',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 5,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'pr03',
    palavra: 'Médico plantonista',
    proibidas: ['branco', 'cansado', 'horas', 'turno', 'serviço'],
    categoria: 'profissoes',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.65,
  },
  {
    id: 'pr04',
    palavra: 'Garçom',
    proibidas: ['mesa', 'pedido', 'servir', 'restaurante', 'prato'],
    categoria: 'profissoes',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'pr05',
    palavra: 'Gari',
    proibidas: ['laranja', 'bituca', 'vassoura', 'coletar', 'madrugada'],
    categoria: 'profissoes',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'pr06',
    palavra: 'Pastor evangélico',
    proibidas: ['microfone', 'púlpito', 'ovelhas', 'sermão', 'cura'],
    categoria: 'profissoes',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'pr07',
    palavra: 'Caixa de supermercado',
    proibidas: ['atendente', 'código', 'troco', 'embrulhar', 'sacola'],
    categoria: 'profissoes',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'pr08',
    palavra: 'Vendedor ambulante',
    proibidas: ['rua', 'produto', 'vender', 'gritar', 'carrinho'],
    categoria: 'profissoes',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'pr09',
    palavra: 'Personal trainer',
    proibidas: ['academia', 'treino', 'exercício', 'músculo', 'dieta'],
    categoria: 'profissoes',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'pr10',
    palavra: 'Nutricionista',
    proibidas: ['dieta', 'alimentação', 'saúde', 'comer', 'consulta'],
    categoria: 'profissoes',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'pr11',
    palavra: 'Corretor de imóveis',
    proibidas: ['casa', 'vender', 'comprar', 'imóvel', 'comissão'],
    categoria: 'profissoes',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'pr12',
    palavra: 'Dono de mercadinho',
    proibidas: ['loja', 'vender', 'produto', 'bairro', 'comprar'],
    categoria: 'profissoes',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.55,
  },

  // ══════════════════════════════════════════════════════════════════════
  // FESTAS — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'ft01',
    palavra: 'Aniversário surpresa',
    proibidas: ['parabéns', 'bolo', 'vela', 'presente', 'esconder'],
    categoria: 'festas',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ft02',
    palavra: 'Balada',
    proibidas: ['rave', 'catraca', 'fila', 'segurança', 'show'],
    categoria: 'festas',
    dificuldade: 'facil',
    tipo: 'memoria_afetiva',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ft03',
    palavra: 'Churrasco de domingo',
    proibidas: ['carne', 'cerveja', 'quintal', 'família', 'domingo'],
    categoria: 'festas',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ft04',
    palavra: 'Festa junina',
    proibidas: ['milho', 'chapéu', 'junho', 'fogueira', 'comemorar'],
    categoria: 'festas',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ft05',
    palavra: 'Happy hour',
    proibidas: ['trabalho', 'bar', 'amigos', 'cerveja', 'sair'],
    categoria: 'festas',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ft06',
    palavra: 'Formatura',
    proibidas: ['faculdade', 'baile', 'diploma', 'colação', 'conquista'],
    categoria: 'festas',
    dificuldade: 'facil',
    tipo: 'memoria_afetiva',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'ft07',
    palavra: 'Casamento',
    proibidas: ['votos', 'buquê', 'altar', 'convite', 'recepção'],
    categoria: 'festas',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'ft08',
    palavra: 'Pagode na laje',
    proibidas: ['samba', 'cerveja', 'laje', 'morro', 'violão'],
    categoria: 'festas',
    dificuldade: 'medio',
    tipo: 'cultura_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'ft09',
    palavra: 'Réveillon',
    proibidas: ['ano', 'virada', 'fogos', 'praia', 'meia-noite'],
    categoria: 'festas',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'ft10',
    palavra: 'Pré-balada',
    proibidas: ['roupa', 'espelho', 'maquiar', 'animado', 'sair'],
    categoria: 'festas',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'ft11',
    palavra: 'Rave',
    proibidas: ['eletrônica', 'noite', 'dança', 'festival', 'campo'],
    categoria: 'festas',
    dificuldade: 'medio',
    tipo: 'caos_urbano',
    energiaEmocional: 3,
    velocidadeCognitiva: 5,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'ft12',
    palavra: 'Ressaca de segunda',
    proibidas: ['cansado', 'dor', 'segunda', 'bebida', 'dormir'],
    categoria: 'festas',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },

  // ══════════════════════════════════════════════════════════════════════
  // RELACIONAMENTOS — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'rl01',
    palavra: 'Crush',
    proibidas: ['gostar', 'apaixonar', 'nervoso', 'coração', 'tremer'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
    tipo: 'memoria_afetiva',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'rl02',
    palavra: 'Ghosting',
    proibidas: ['sumir', 'ignorar', 'mensagem', 'desaparecer', 'responder'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
    tipo: 'meme_contemporaneo',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'rl03',
    palavra: 'Término',
    proibidas: ['acabar', 'chorar', 'separar', 'casal', 'fim'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'rl04',
    palavra: 'Amizade colorida',
    proibidas: ['amigo', 'íntimo', 'compromisso', 'relação', 'ficar'],
    categoria: 'relacionamentos',
    dificuldade: 'medio',
    tipo: 'contradicao',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'rl05',
    palavra: 'Tinder',
    proibidas: ['swipe', 'match', 'app', 'foto', 'encontrar'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
    tipo: 'meme_contemporaneo',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'rl06',
    palavra: 'Ciúme',
    proibidas: ['inseguro', 'bravo', 'sentir', 'relacionamento', 'olhar'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
    tipo: 'pressao_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'rl07',
    palavra: 'Pedido de namoro',
    proibidas: ['flores', 'jantar', 'vela', 'joelho', 'compromisso'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'rl08',
    palavra: 'Ex que some',
    proibidas: ['passado', 'sumir', 'lembrar', 'antigo', 'saudade'],
    categoria: 'relacionamentos',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'rl09',
    palavra: 'Declaração por mensagem',
    proibidas: ['mandar', 'texto', 'coração', 'mensagem', 'coragem'],
    categoria: 'relacionamentos',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'rl10',
    palavra: 'Briga de casal',
    proibidas: ['discutir', 'bravo', 'gritar', 'casal', 'resolver'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'rl11',
    palavra: 'Recaída',
    proibidas: ['voltar', 'ex', 'errar', 'repetir', 'fraqueza'],
    categoria: 'relacionamentos',
    dificuldade: 'medio',
    tipo: 'memoria_afetiva',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'rl12',
    palavra: 'Parceiro casual',
    proibidas: ['ficar', 'eventual', 'amizade', 'benefícios', 'casual'],
    categoria: 'relacionamentos',
    dificuldade: 'dificil',
    tipo: 'contradicao',
    energiaEmocional: 4,
    velocidadeCognitiva: 2,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.30,
  },

  // ══════════════════════════════════════════════════════════════════════
  // LUGARES — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'lg01',
    palavra: 'Centro de São Paulo',
    proibidas: ['metrô', 'grande', 'movimentado', 'prédio', 'barulho'],
    categoria: 'lugares',
    dificuldade: 'facil',
    tipo: 'caos_urbano',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'lg02',
    palavra: 'Favela',
    proibidas: ['morro', 'comunidade', 'Rio', 'laje', 'morador'],
    categoria: 'lugares',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'lg03',
    palavra: 'Posto de gasolina',
    proibidas: ['tanque', 'litro', 'bomba', 'etanol', 'frentista'],
    categoria: 'lugares',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'lg04',
    palavra: 'Padaria',
    proibidas: ['forno', 'trigo', 'cheiro', 'fatia', 'centeio'],
    categoria: 'lugares',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 5,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'lg05',
    palavra: 'Feira livre',
    proibidas: ['comprar', 'barato', 'cheiro', 'ambulante', 'frutas'],
    categoria: 'lugares',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'lg06',
    palavra: 'Interior do Brasil',
    proibidas: ['roça', 'pequeno', 'tranquilo', 'campo', 'longe'],
    categoria: 'lugares',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 1,
    velocidadeCognitiva: 3,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'lg07',
    palavra: 'Amazônia',
    proibidas: ['floresta', 'verde', 'rio', 'natureza', 'selva'],
    categoria: 'lugares',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 3,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'lg08',
    palavra: 'Aeroporto',
    proibidas: ['esteira', 'check-in', 'decolagem', 'alfândega', 'conexão'],
    categoria: 'lugares',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'lg09',
    palavra: 'Beco escuro',
    proibidas: ['rua', 'pequena', 'escuro', 'entrada', 'estreito'],
    categoria: 'lugares',
    dificuldade: 'medio',
    tipo: 'visual_imediata',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'lg10',
    palavra: 'Litoral nordestino',
    proibidas: ['praia', 'mar', 'nordeste', 'calor', 'sol'],
    categoria: 'lugares',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'lg11',
    palavra: 'Periferia',
    proibidas: ['bairro', 'longe', 'ônibus', 'subúrbio', 'quebrada'],
    categoria: 'lugares',
    dificuldade: 'medio',
    tipo: 'cultura_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'lg12',
    palavra: 'Orla de Copacabana',
    proibidas: ['praia', 'Rio', 'calçadão', 'mar', 'areia'],
    categoria: 'lugares',
    dificuldade: 'medio',
    tipo: 'visual_imediata',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.60,
  },

  // ══════════════════════════════════════════════════════════════════════
  // BRASIL — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'br01',
    palavra: 'Jeitinho brasileiro',
    proibidas: ['problema', 'solução', 'criativo', 'improviso', 'malandro'],
    categoria: 'brasil',
    dificuldade: 'dificil',
    tipo: 'cultura_br',
    energiaEmocional: 4,
    velocidadeCognitiva: 2,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.30,
  },
  {
    id: 'br02',
    palavra: 'Copa do Mundo',
    proibidas: ['futebol', 'seleção', 'mundial', 'torcer', 'gol'],
    categoria: 'brasil',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'br03',
    palavra: 'Décimo terceiro',
    proibidas: ['extra', 'dezembro', 'dinheiro', 'receber', 'trabalho'],
    categoria: 'brasil',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'br04',
    palavra: 'Burocracia',
    proibidas: ['carimbo', 'despachante', 'certidão', 'prazo', 'autenticar'],
    categoria: 'brasil',
    dificuldade: 'medio',
    tipo: 'caos_corporativo',
    energiaEmocional: 3,
    velocidadeCognitiva: 2,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'br05',
    palavra: 'Samba no pé',
    proibidas: ['dança', 'ritmo', 'carnaval', 'quadril', 'habilidade'],
    categoria: 'brasil',
    dificuldade: 'medio',
    tipo: 'cultura_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'br06',
    palavra: 'Reunião de condomínio',
    proibidas: ['vizinho', 'prédio', 'barulho', 'reclamar', 'ata'],
    categoria: 'brasil',
    dificuldade: 'medio',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 2,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'br07',
    palavra: 'Rachar a conta',
    proibidas: ['dividir', 'pagar', 'conta', 'restaurante', 'amigos'],
    categoria: 'brasil',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'br08',
    palavra: 'Apagão',
    proibidas: ['vela', 'lanterna', 'falta', 'improviso', 'surpresa'],
    categoria: 'brasil',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'br09',
    palavra: 'Malandragem',
    proibidas: ['jeitinho', 'esperteza', 'ginga', 'malícia', 'safadeza'],
    categoria: 'brasil',
    dificuldade: 'dificil',
    tipo: 'cultura_br',
    energiaEmocional: 4,
    velocidadeCognitiva: 2,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.30,
  },
  {
    id: 'br10',
    palavra: 'Salário mínimo',
    proibidas: ['piso', 'reajuste', 'CLT', 'renda', 'pobreza'],
    categoria: 'brasil',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 2,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'br11',
    palavra: 'Feriado nacional',
    proibidas: ['folga', 'trabalho', 'descanso', 'dia', 'comemorar'],
    categoria: 'brasil',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'br12',
    palavra: 'Nota fiscal',
    proibidas: ['compra', 'imposto', 'recibo', 'documento', 'loja'],
    categoria: 'brasil',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.55,
  },

  // ══════════════════════════════════════════════════════════════════════
  // TRAUMAS MILLENNIALS — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'tm01',
    palavra: 'Fotolog',
    proibidas: ['perfil', 'foto', 'internet', 'postar', 'scrap'],
    categoria: 'traumas_millennials',
    dificuldade: 'medio',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'tm02',
    palavra: 'MSN Messenger',
    proibidas: ['mensagem', 'online', 'chat', 'computador', 'emoticon'],
    categoria: 'traumas_millennials',
    dificuldade: 'medio',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.65,
  },
  {
    id: 'tm03',
    palavra: 'Disquete',
    proibidas: ['salvar', 'arquivo', 'computador', 'plástico', 'dados'],
    categoria: 'traumas_millennials',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'tm04',
    palavra: '"Você foi desconectado"',
    proibidas: ['internet', 'cair', 'conexão', 'online', 'discagem'],
    categoria: 'traumas_millennials',
    dificuldade: 'medio',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.65,
  },
  {
    id: 'tm05',
    palavra: 'Tamagotchi',
    proibidas: ['virtual', 'bicho', 'cuidar', 'morrer', 'tecla'],
    categoria: 'traumas_millennials',
    dificuldade: 'facil',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'tm06',
    palavra: 'Lan house',
    proibidas: ['computador', 'internet', 'jogar', 'hora', 'locação'],
    categoria: 'traumas_millennials',
    dificuldade: 'facil',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'tm07',
    palavra: 'Celular tijolão',
    proibidas: ['Nokia', 'pesado', 'antigo', 'botão', 'resistente'],
    categoria: 'traumas_millennials',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'tm08',
    palavra: 'CD riscado',
    proibidas: ['música', 'chiado', 'travar', 'disco', 'arranhado'],
    categoria: 'traumas_millennials',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'tm09',
    palavra: 'Esperar resultado do ENEM',
    proibidas: ['vestibular', 'nota', 'ansiedade', 'resultado', 'aprovado'],
    categoria: 'traumas_millennials',
    dificuldade: 'medio',
    tipo: 'pressao_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 2,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'tm10',
    palavra: 'Fita VHS',
    proibidas: ['vídeo', 'rebobinar', 'cassete', 'assistir', 'preto'],
    categoria: 'traumas_millennials',
    dificuldade: 'medio',
    tipo: 'visual_imediata',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.70,
  },
  {
    id: 'tm11',
    palavra: 'Disco de vinil',
    proibidas: ['música', 'girar', 'agulha', 'toca-discos', 'LP'],
    categoria: 'traumas_millennials',
    dificuldade: 'medio',
    tipo: 'visual_imediata',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.65,
  },
  {
    id: 'tm12',
    palavra: 'Orkut',
    proibidas: ['rede', 'perfil', 'social', 'Google', 'depoimento'],
    categoria: 'traumas_millennials',
    dificuldade: 'medio',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.60,
  },

  // ══════════════════════════════════════════════════════════════════════
  // MEMES BR — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'mb01',
    palavra: '"É nóis"',
    proibidas: ['nós', 'expressão', 'gíria', 'certo', 'acordo'],
    categoria: 'memes_br',
    dificuldade: 'medio',
    tipo: 'frase_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'mb02',
    palavra: '"Tô na correria"',
    proibidas: ['ocupado', 'correndo', 'pressa', 'tempo', 'desculpa'],
    categoria: 'memes_br',
    dificuldade: 'facil',
    tipo: 'frase_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'mb03',
    palavra: '"Partiu"',
    proibidas: ['vamos', 'ir', 'sair', 'embora', 'agora'],
    categoria: 'memes_br',
    dificuldade: 'facil',
    tipo: 'frase_br',
    energiaEmocional: 1,
    velocidadeCognitiva: 5,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'mb04',
    palavra: '"Falou e disse"',
    proibidas: ['certo', 'concordar', 'encerrar', 'assunto', 'combinado'],
    categoria: 'memes_br',
    dificuldade: 'medio',
    tipo: 'frase_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'mb05',
    palavra: '"Vai que cola"',
    proibidas: ['tentar', 'funcionar', 'esperança', 'tentativa', 'talvez'],
    categoria: 'memes_br',
    dificuldade: 'medio',
    tipo: 'frase_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'mb06',
    palavra: 'Saudade',
    proibidas: ['Portugal', 'longe', 'tempo', 'coração', 'morrer'],
    categoria: 'memes_br',
    dificuldade: 'facil',
    tipo: 'memoria_afetiva',
    energiaEmocional: 4,
    velocidadeCognitiva: 1,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.30,
  },
  {
    id: 'mb07',
    palavra: '"Bom dia família do WhatsApp"',
    proibidas: ['mensagem', 'grupo', 'manhã', 'compartilhar', 'corrente'],
    categoria: 'memes_br',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'mb08',
    palavra: '"Misericórdia"',
    proibidas: ['nordeste', 'exclamação', 'espanto', 'Deus', 'surpresa'],
    categoria: 'memes_br',
    dificuldade: 'facil',
    tipo: 'oralidade_pura',
    energiaEmocional: 2,
    velocidadeCognitiva: 5,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'mb09',
    palavra: '"Me poupa"',
    proibidas: ['cansar', 'parar', 'chato', 'deixar', 'suficiente'],
    categoria: 'memes_br',
    dificuldade: 'medio',
    tipo: 'frase_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'mb10',
    palavra: '"Eita"',
    proibidas: ['surpresa', 'nordestino', 'exclamação', 'caramba', 'espanto'],
    categoria: 'memes_br',
    dificuldade: 'facil',
    tipo: 'oralidade_pura',
    energiaEmocional: 1,
    velocidadeCognitiva: 5,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'mb11',
    palavra: '"Já ganhou"',
    proibidas: ['garantido', 'certo', 'vencer', 'automático', 'seguro'],
    categoria: 'memes_br',
    dificuldade: 'medio',
    tipo: 'frase_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'mb12',
    palavra: '"Péssimo dia para ser [X]"',
    proibidas: ['dia', 'azar', 'irônico', 'situação', 'frase'],
    categoria: 'memes_br',
    dificuldade: 'dificil',
    tipo: 'brainrot',
    energiaEmocional: 4,
    velocidadeCognitiva: 3,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.25,
  },

  // ══════════════════════════════════════════════════════════════════════
  // VIDA ADULTA — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'va01',
    palavra: 'Conta de luz cara',
    proibidas: ['energia', 'pagar', 'boleto', 'mês', 'choque'],
    categoria: 'vida_adulta',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'va02',
    palavra: 'Acordar com dor nas costas',
    proibidas: ['colchão', 'postura', 'manhã', 'esticar', 'região'],
    categoria: 'vida_adulta',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'va03',
    palavra: 'Imposto de renda',
    proibidas: ['declarar', 'governo', 'pagar', 'restituição', 'tributo'],
    categoria: 'vida_adulta',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'va04',
    palavra: 'Reunião às 8 da manhã',
    proibidas: ['cedo', 'trabalho', 'chefe', 'acordar', 'zoom'],
    categoria: 'vida_adulta',
    dificuldade: 'facil',
    tipo: 'caos_corporativo',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'va05',
    palavra: 'Plano de saúde que não cobre nada',
    proibidas: ['médico', 'consulta', 'negar', 'autorizar', 'cobrir'],
    categoria: 'vida_adulta',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'va06',
    palavra: 'Preço do aluguel',
    proibidas: ['caro', 'morar', 'mês', 'contrato', 'apartamento'],
    categoria: 'vida_adulta',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'va07',
    palavra: 'Dormir às 22h numa sexta',
    proibidas: ['cansado', 'cedo', 'sono', 'sexta', 'envelhelecer'],
    categoria: 'vida_adulta',
    dificuldade: 'medio',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'va08',
    palavra: '"Isso não é bom pro coração"',
    proibidas: ['saúde', 'médico', 'preocupar', 'estresse', 'coração'],
    categoria: 'vida_adulta',
    dificuldade: 'medio',
    tipo: 'frase_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'va09',
    palavra: 'Conserto de carro',
    proibidas: ['mecânico', 'caro', 'oficina', 'problema', 'quebrar'],
    categoria: 'vida_adulta',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'va10',
    palavra: 'Ligar pro SAC',
    proibidas: ['esperar', 'musiquinha', 'atendente', 'resolver', 'paciência'],
    categoria: 'vida_adulta',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 2,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'va11',
    palavra: '"Tenho que acordar cedo amanhã"',
    proibidas: ['sono', 'amanhã', 'trabalho', 'cedo', 'dormir'],
    categoria: 'vida_adulta',
    dificuldade: 'facil',
    tipo: 'frase_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'va12',
    palavra: 'Taxa de condomínio',
    proibidas: ['prédio', 'mensalidade', 'pagar', 'morar', 'síndico'],
    categoria: 'vida_adulta',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.55,
  },

  // ══════════════════════════════════════════════════════════════════════
  // DATE RUIM — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'dr01',
    palavra: 'Chegou uma hora atrasado',
    proibidas: ['esperar', 'atraso', 'horário', 'desrespeito', 'pontual'],
    categoria: 'date_ruim',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'dr02',
    palavra: 'Ficou no celular o tempo todo',
    proibidas: ['tela', 'ignorar', 'distraído', 'atenção', 'desligar'],
    categoria: 'date_ruim',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'dr03',
    palavra: 'Falou do ex durante o jantar',
    proibidas: ['ex', 'antigo', 'namorado', 'passado', 'saudade'],
    categoria: 'date_ruim',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'dr04',
    palavra: 'Foto do perfil enganosa',
    proibidas: ['foto', 'diferente', 'mentira', 'aparecer', 'real'],
    categoria: 'date_ruim',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'dr05',
    palavra: 'Conta separada no primeiro encontro',
    proibidas: ['pagar', 'dividir', 'dinheiro', 'metade', 'nota'],
    categoria: 'date_ruim',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'dr06',
    palavra: 'Não perguntou nada sobre você',
    proibidas: ['egoísta', 'falar', 'interesse', 'perguntar', 'ignorar'],
    categoria: 'date_ruim',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'dr07',
    palavra: 'Levou a mãe junto',
    proibidas: ['mãe', 'inesperado', 'familiar', 'acompanhar', 'terceiro'],
    categoria: 'date_ruim',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 4,
    velocidadeCognitiva: 4,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.30,
  },
  {
    id: 'dr08',
    palavra: 'Silêncio constrangedor',
    proibidas: ['calado', 'vazio', 'constrangimento', 'conversa', 'pausa'],
    categoria: 'date_ruim',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 1,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'dr09',
    palavra: 'Deu um selinho e foi embora',
    proibidas: ['beijo', 'tchau', 'rápido', 'sair', 'despedir'],
    categoria: 'date_ruim',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'dr10',
    palavra: '"Depois eu te mando mensagem"',
    proibidas: ['ghosting', 'sumir', 'mentira', 'esperar', 'promessa'],
    categoria: 'date_ruim',
    dificuldade: 'medio',
    tipo: 'meme_contemporaneo',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'dr11',
    palavra: 'Restaurante estava fechado',
    proibidas: ['fechado', 'lugar', 'planejar', 'frustração', 'plano'],
    categoria: 'date_ruim',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'dr12',
    palavra: 'Encontrou o ex no mesmo lugar',
    proibidas: ['ex', 'coincidência', 'azar', 'encontrar', 'local'],
    categoria: 'date_ruim',
    dificuldade: 'dificil',
    tipo: 'vergonha_social',
    energiaEmocional: 4,
    velocidadeCognitiva: 4,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.25,
  },

  // ══════════════════════════════════════════════════════════════════════
  // ESCRITÓRIO — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'es01',
    palavra: 'Planilha de Excel com 40 abas',
    proibidas: ['Excel', 'aba', 'célula', 'fórmula', 'organizar'],
    categoria: 'escritorio',
    dificuldade: 'facil',
    tipo: 'caos_corporativo',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'es02',
    palavra: 'E-mail marcado como urgente',
    proibidas: ['email', 'urgente', 'responder', 'prazo', 'prioridade'],
    categoria: 'escritorio',
    dificuldade: 'facil',
    tipo: 'caos_corporativo',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'es03',
    palavra: '"Podemos alinhar isso?"',
    proibidas: ['reunião', 'combinar', 'conversar', 'agenda', 'falar'],
    categoria: 'escritorio',
    dificuldade: 'medio',
    tipo: 'caos_corporativo',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'es04',
    palavra: 'Confraternização de fim de ano',
    proibidas: ['festa', 'empresa', 'natal', 'obrigatório', 'amigo'],
    categoria: 'escritorio',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'es05',
    palavra: 'Impressora travada',
    proibidas: ['imprimir', 'papel', 'travar', 'atolamento', 'erro'],
    categoria: 'escritorio',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'es06',
    palavra: 'Ar-condicionado no máximo',
    proibidas: ['frio', 'temperatura', 'reclamar', 'casaco', 'gelo'],
    categoria: 'escritorio',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'es07',
    palavra: '"Me copia nesse e-mail"',
    proibidas: ['incluir', 'cópia', 'ciente', 'CC', 'saber'],
    categoria: 'escritorio',
    dificuldade: 'medio',
    tipo: 'caos_corporativo',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'es08',
    palavra: 'Reunião que podia ser um e-mail',
    proibidas: ['inútil', 'tempo', 'desnecessário', 'zoom', 'pauta'],
    categoria: 'escritorio',
    dificuldade: 'facil',
    tipo: 'caos_corporativo',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'es09',
    palavra: 'Cafezinho das 10h',
    proibidas: ['café', 'pausa', 'conversa', 'rotina', 'manhã'],
    categoria: 'escritorio',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 1,
    velocidadeCognitiva: 4,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'es10',
    palavra: 'Hora extra não paga',
    proibidas: ['trabalhar', 'mais', 'receber', 'injusto', 'tarde'],
    categoria: 'escritorio',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'es11',
    palavra: 'Colega que aquece comida fedorenta',
    proibidas: ['cheiro', 'microondas', 'comida', 'incomoda', 'cozinha'],
    categoria: 'escritorio',
    dificuldade: 'medio',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'es12',
    palavra: 'Sistema caindo na hora da entrega',
    proibidas: ['sistema', 'travar', 'cair', 'prazo', 'servidor'],
    categoria: 'escritorio',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 4,
    velocidadeCognitiva: 4,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.35,
  },

  // ══════════════════════════════════════════════════════════════════════
  // UNIVERSIDADE — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'un01',
    palavra: 'Semana de provas',
    proibidas: ['estudar', 'cafeína', 'sono', 'nervoso', 'madrugada'],
    categoria: 'universidade',
    dificuldade: 'facil',
    tipo: 'pressao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'un02',
    palavra: 'Trabalho em grupo onde um faz tudo',
    proibidas: ['grupo', 'sozinho', 'injusto', 'apresentação', 'nota'],
    categoria: 'universidade',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'un03',
    palavra: 'RU',
    proibidas: ['comida', 'bandejão', 'fila', 'barato', 'almoço'],
    categoria: 'universidade',
    dificuldade: 'medio',
    tipo: 'visual_imediata',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'un04',
    palavra: 'Trote universitário',
    proibidas: ['calouro', 'novato', 'humilhar', 'primeiro', 'ritual'],
    categoria: 'universidade',
    dificuldade: 'facil',
    tipo: 'vergonha_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'un05',
    palavra: 'Professor que cancela na última hora',
    proibidas: ['cancelar', 'aula', 'falta', 'aviso', 'surpresa'],
    categoria: 'universidade',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'un06',
    palavra: 'TCC',
    proibidas: ['trabalho', 'conclusão', 'banca', 'faculdade', 'semestre'],
    categoria: 'universidade',
    dificuldade: 'facil',
    tipo: 'pressao_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 2,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'un07',
    palavra: 'Greve na faculdade',
    proibidas: ['parar', 'aula', 'protesto', 'sindicato', 'professor'],
    categoria: 'universidade',
    dificuldade: 'medio',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'un08',
    palavra: 'Crédito insuficiente para se formar',
    proibidas: ['crédito', 'disciplina', 'faltar', 'diploma', 'semestre'],
    categoria: 'universidade',
    dificuldade: 'dificil',
    tipo: 'micro_cena',
    energiaEmocional: 4,
    velocidadeCognitiva: 2,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.30,
  },
  {
    id: 'un09',
    palavra: 'Festa de república',
    proibidas: ['casa', 'estudante', 'noite', 'morar', 'bagunça'],
    categoria: 'universidade',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'un10',
    palavra: 'Estágio não remunerado',
    proibidas: ['trabalhar', 'grátis', 'experiência', 'empresa', 'aprender'],
    categoria: 'universidade',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'un11',
    palavra: 'Cursinho pré-vestibular',
    proibidas: ['preparar', 'intensivo', 'estudar', 'aprovação', 'redação'],
    categoria: 'universidade',
    dificuldade: 'facil',
    tipo: 'pressao_social',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'un12',
    palavra: 'Colar na prova',
    proibidas: ['trapaça', 'esconder', 'nota', 'cola', 'professor'],
    categoria: 'universidade',
    dificuldade: 'medio',
    tipo: 'vergonha_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },

  // ══════════════════════════════════════════════════════════════════════
  // CARNAVAL — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'cv01',
    palavra: 'Camarote',
    proibidas: ['VIP', 'famoso', 'cerveja', 'vista', 'espaço'],
    categoria: 'carnaval',
    dificuldade: 'medio',
    tipo: 'cultura_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.70,
  },
  {
    id: 'cv02',
    palavra: 'Abadá',
    proibidas: ['bloco', 'roupa', 'colorido', 'identificação', 'carnaval'],
    categoria: 'carnaval',
    dificuldade: 'medio',
    tipo: 'visual_imediata',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'cv03',
    palavra: 'Axé music',
    proibidas: ['baiana', 'ritmo', 'dançar', 'agitar', 'Salvador'],
    categoria: 'carnaval',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 5,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cv04',
    palavra: 'Escola de samba',
    proibidas: ['desfile', 'sambódromo', 'passarela', 'alas', 'Rio'],
    categoria: 'carnaval',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'cv05',
    palavra: 'Bloco de rua',
    proibidas: ['fantasia', 'multidão', 'rua', 'música', 'percussão'],
    categoria: 'carnaval',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cv06',
    palavra: 'Trio elétrico',
    proibidas: ['caminhão', 'cima', 'ao vivo', 'Bahia', 'multidão'],
    categoria: 'carnaval',
    dificuldade: 'medio',
    tipo: 'cultura_br',
    energiaEmocional: 4,
    velocidadeCognitiva: 4,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.65,
  },
  {
    id: 'cv07',
    palavra: 'Confete no cabelo',
    proibidas: ['colorido', 'festival', 'tirar', 'grudar', 'papel'],
    categoria: 'carnaval',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 2,
    velocidadeCognitiva: 5,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cv08',
    palavra: 'Pierrot',
    proibidas: ['pintado', 'triste', 'Colombina', 'punho', 'espetáculo'],
    categoria: 'carnaval',
    dificuldade: 'medio',
    tipo: 'visual_imediata',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.50,
  },
  {
    id: 'cv09',
    palavra: 'Ressaca de carnaval',
    proibidas: ['segunda', 'cansado', 'festa', 'exausto', 'retorno'],
    categoria: 'carnaval',
    dificuldade: 'facil',
    tipo: 'micro_cena',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cv10',
    palavra: 'Rei Momo',
    proibidas: ['coroar', 'tradição', 'personagem', 'rei', 'abertura'],
    categoria: 'carnaval',
    dificuldade: 'dificil',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 2,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.35,
  },
  {
    id: 'cv11',
    palavra: 'Passista',
    proibidas: ['samba', 'quadril', 'escola', 'dançar', 'sensual'],
    categoria: 'carnaval',
    dificuldade: 'medio',
    tipo: 'visual_imediata',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'cv12',
    palavra: 'Marchinhas de carnaval',
    proibidas: ['música', 'antiga', 'cantoria', 'letra', 'divertida'],
    categoria: 'carnaval',
    dificuldade: 'medio',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.65,
  },

  // ══════════════════════════════════════════════════════════════════════
  // REALITY SHOWS — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'rs01',
    palavra: 'Paredão do BBB',
    proibidas: ['votar', 'berlinda', 'eliminar', 'salvar', 'preferido'],
    categoria: 'reality_shows',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'rs02',
    palavra: 'A Fazenda',
    proibidas: ['peões', 'fazendeiro', 'roça', 'poder', 'Record'],
    categoria: 'reality_shows',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'rs03',
    palavra: 'MasterChef Brasil',
    proibidas: ['cozinhar', 'avental', 'eliminação', 'prato', 'avaliação'],
    categoria: 'reality_shows',
    dificuldade: 'facil',
    tipo: 'visual_imediata',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'rs04',
    palavra: 'Casamento às Cegas',
    proibidas: ['casar', 'desconhecido', 'pod', 'conhecer', 'amor'],
    categoria: 'reality_shows',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'rs05',
    palavra: 'No Limite',
    proibidas: ['sobrevivência', 'praia', 'tribo', 'fome', 'desafio'],
    categoria: 'reality_shows',
    dificuldade: 'medio',
    tipo: 'pressao_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.65,
  },
  {
    id: 'rs06',
    palavra: 'The Voice Brasil',
    proibidas: ['cantar', 'virar', 'talento', 'cadeira', 'audição'],
    categoria: 'reality_shows',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'rs07',
    palavra: 'Ilha Record',
    proibidas: ['ilha', 'casal', 'prova', 'prêmio', 'desafio'],
    categoria: 'reality_shows',
    dificuldade: 'medio',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'rs08',
    palavra: 'Shark Tank Brasil',
    proibidas: ['investidor', 'negócio', 'proposta', 'dinheiro', 'pitch'],
    categoria: 'reality_shows',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 3,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'rs09',
    palavra: 'Hell\'s Kitchen Brasil',
    proibidas: ['cozinha', 'gritar', 'serviço', 'brigada', 'chef'],
    categoria: 'reality_shows',
    dificuldade: 'medio',
    tipo: 'micro_cena',
    energiaEmocional: 4,
    velocidadeCognitiva: 3,
    potencialCaos: 4,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'rs10',
    palavra: 'Dancing Brasil',
    proibidas: ['dança', 'celebridade', 'eliminação', 'profissional', 'ritmo'],
    categoria: 'reality_shows',
    dificuldade: 'medio',
    tipo: 'cultura_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'rs11',
    palavra: 'Domingão do Huck',
    proibidas: ['domingo', 'Globo', 'apresentador', 'quadro', 'jogo'],
    categoria: 'reality_shows',
    dificuldade: 'facil',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'rs12',
    palavra: 'Programa do Ratinho',
    proibidas: ['SBT', 'polêmico', 'popular', 'auditório', 'apresentador'],
    categoria: 'reality_shows',
    dificuldade: 'medio',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 2,
    velocidadeCognitiva: 3,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.65,
  },

  // ══════════════════════════════════════════════════════════════════════
  // CELEBRIDADES BR — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'cb01',
    palavra: 'Xuxa Meneghel',
    proibidas: ['loura', 'apresentadora', 'baixinhos', 'dançarina', 'Globo'],
    categoria: 'celebridades_br',
    dificuldade: 'facil',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 2,
    velocidadeCognitiva: 5,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.90,
  },
  {
    id: 'cb02',
    palavra: 'Ivete Sangalo',
    proibidas: ['baiana', 'carnaval', 'cantora', 'animada', 'festival'],
    categoria: 'celebridades_br',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 5,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.90,
  },
  {
    id: 'cb03',
    palavra: 'Anitta',
    proibidas: ['funkeira', 'internacional', 'sensual', 'hit', 'clipe'],
    categoria: 'celebridades_br',
    dificuldade: 'facil',
    tipo: 'meme_contemporaneo',
    energiaEmocional: 3,
    velocidadeCognitiva: 5,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.90,
  },
  {
    id: 'cb04',
    palavra: 'Zeca Pagodinho',
    proibidas: ['samba', 'pagode', 'cerveja', 'tranquilo', 'Brahma'],
    categoria: 'celebridades_br',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'cb05',
    palavra: 'Roberto Carlos',
    proibidas: ['Rei', 'balada', 'eterno', 'cantor', 'imensidão'],
    categoria: 'celebridades_br',
    dificuldade: 'facil',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'cb06',
    palavra: 'Silvio Santos',
    proibidas: ['SBT', 'domingo', 'auditório', 'patrão', 'vendedor'],
    categoria: 'celebridades_br',
    dificuldade: 'facil',
    tipo: 'nostalgia_brasileira',
    energiaEmocional: 2,
    velocidadeCognitiva: 5,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'cb07',
    palavra: 'Paulo Gustavo',
    proibidas: ['humor', 'mãe', 'ator', 'engraçado', 'série'],
    categoria: 'celebridades_br',
    dificuldade: 'facil',
    tipo: 'memoria_afetiva',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cb08',
    palavra: 'Marília Mendonça',
    proibidas: ['sertanejo', 'sofrência', 'traição', 'voz', 'saudade'],
    categoria: 'celebridades_br',
    dificuldade: 'facil',
    tipo: 'memoria_afetiva',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'cb09',
    palavra: 'Luan Santana',
    proibidas: ['sertanejo', 'jovem', 'sucesso', 'show', 'fã'],
    categoria: 'celebridades_br',
    dificuldade: 'medio',
    tipo: 'cultura_br',
    energiaEmocional: 2,
    velocidadeCognitiva: 4,
    potencialCaos: 2,
    taxaAcertoEsperada: 0.70,
  },
  {
    id: 'cb10',
    palavra: 'Pabllo Vittar',
    proibidas: ['drag', 'LGBT', 'axé', 'transformação', 'artista'],
    categoria: 'celebridades_br',
    dificuldade: 'facil',
    tipo: 'cultura_br',
    energiaEmocional: 3,
    velocidadeCognitiva: 4,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'cb11',
    palavra: 'MC Kevinho',
    proibidas: ['funk', 'carioca', 'dança', 'hit', 'agito'],
    categoria: 'celebridades_br',
    dificuldade: 'medio',
    tipo: 'meme_contemporaneo',
    energiaEmocional: 3,
    velocidadeCognitiva: 5,
    potencialCaos: 3,
    taxaAcertoEsperada: 0.65,
  },
  {
    id: 'cb12',
    palavra: 'Fernanda Montenegro',
    proibidas: ['atriz', 'teatro', 'Globo', 'drama', 'clássica'],
    categoria: 'celebridades_br',
    dificuldade: 'dificil',
    tipo: 'memoria_coletiva',
    energiaEmocional: 1,
    velocidadeCognitiva: 3,
    potencialCaos: 1,
    taxaAcertoEsperada: 0.40,
  },
  // ══════════════════════════════════════════════════════════════════════
  // COLAPSO BR — 15 cartas (dificuldade: colapso)
  // Conceitos que o cérebro reconhece mas a boca se recusa a explicar.
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'cl01',
    palavra: 'Muxoxo',
    proibidas: ['boca', 'lábio', 'som', 'desgosto', 'tsé'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'colapso_verbal',
    energiaEmocional: 5,
    taxaAcertoEsperada: 0.10,
  },
  {
    id: 'cl02',
    palavra: 'FOMO',
    proibidas: ['medo', 'perder', 'evento', 'social', 'ansiedade'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'caos_mental',
    energiaEmocional: 5,
    taxaAcertoEsperada: 0.08,
  },
  {
    id: 'cl03',
    palavra: 'Burnout',
    proibidas: ['trabalho', 'cansado', 'exausto', 'esgotamento', 'estresse'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'caos_mental',
    energiaEmocional: 4,
    taxaAcertoEsperada: 0.15,
  },
  {
    id: 'cl04',
    palavra: 'Gaslighting',
    proibidas: ['manipular', 'enganar', 'psicológico', 'abuso', 'mentira'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'contradicao',
    energiaEmocional: 5,
    taxaAcertoEsperada: 0.08,
  },
  {
    id: 'cl05',
    palavra: 'Procrastinação produtiva',
    proibidas: ['adiar', 'preguiça', 'amanhã', 'postergar', 'deixar'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'contradicao',
    energiaEmocional: 5,
    taxaAcertoEsperada: 0.10,
  },
  {
    id: 'cl06',
    palavra: 'Carência',
    proibidas: ['solidão', 'falta', 'precisar', 'necessidade', 'vazio'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'caos_mental',
    energiaEmocional: 5,
    taxaAcertoEsperada: 0.12,
  },
  {
    id: 'cl07',
    palavra: 'Karma',
    proibidas: ['consequência', 'destino', 'colher', 'plantar', 'merecer'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'inferencia_indireta',
    energiaEmocional: 4,
    taxaAcertoEsperada: 0.15,
  },
  {
    id: 'cl08',
    palavra: 'Vibe ruim',
    proibidas: ['atmosfera', 'energia', 'presença', 'sentir', 'ambiente'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'caos_mental',
    energiaEmocional: 5,
    taxaAcertoEsperada: 0.10,
  },
  {
    id: 'cl09',
    palavra: 'Vergonha alheia',
    proibidas: ['constrangimento', 'outro', 'corar', 'situação', 'alheia'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'vergonha_social',
    energiaEmocional: 5,
    taxaAcertoEsperada: 0.12,
  },
  {
    id: 'cl10',
    palavra: 'Xodó',
    proibidas: ['amor', 'carinho', 'querer', 'preferido', 'querido'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'memoria_afetiva',
    energiaEmocional: 4,
    taxaAcertoEsperada: 0.15,
  },
  {
    id: 'cl11',
    palavra: 'Treta',
    proibidas: ['briga', 'confusão', 'barraco', 'discussão', 'polêmica'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'situacao_social',
    energiaEmocional: 4,
    taxaAcertoEsperada: 0.18,
  },
  {
    id: 'cl12',
    palavra: 'Deixa pra lá',
    proibidas: ['esquecer', 'desistir', 'ignorar', 'parar', 'superar'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'colapso_verbal',
    energiaEmocional: 5,
    taxaAcertoEsperada: 0.10,
  },
  {
    id: 'cl13',
    palavra: 'Calor humano',
    proibidas: ['abraço', 'carinho', 'amizade', 'aconchego', 'afeto'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'inferencia_indireta',
    energiaEmocional: 5,
    taxaAcertoEsperada: 0.08,
  },
  {
    id: 'cl14',
    palavra: 'Resiliência',
    proibidas: ['força', 'superar', 'dificuldade', 'aguentar', 'persistir'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'caos_mental',
    energiaEmocional: 5,
    taxaAcertoEsperada: 0.08,
  },
  {
    id: 'cl15',
    palavra: 'Intuição',
    proibidas: ['sentir', 'perceber', 'instinto', 'pressentir', 'palpite'],
    categoria: 'colapso_br',
    dificuldade: 'colapso',
    tipo: 'inferencia_indireta',
    energiaEmocional: 5,
    taxaAcertoEsperada: 0.10,
  },

  // ══════════════════════════════════════════════════════════════════════
  // VERGONHA SOCIAL — 10 cartas
  // Situações de constrangimento coletivo garantido.
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'vs01',
    palavra: 'Abrir a porta errada do banheiro',
    proibidas: ['banheiro', 'porta', 'ocupado', 'engano', 'bateu'],
    categoria: 'vergonha_social',
    dificuldade: 'dificil',
    tipo: 'vergonha_social',
    energiaEmocional: 4,
    taxaAcertoEsperada: 0.30,
  },
  {
    id: 'vs02',
    palavra: 'Rir na hora errada',
    proibidas: ['risada', 'inapropriado', 'gargalhar', 'situação', 'nervoso'],
    categoria: 'vergonha_social',
    dificuldade: 'medio',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'vs03',
    palavra: 'Esquecer o nome da pessoa',
    proibidas: ['nome', 'esqueceu', 'branco', 'lembrar', 'conhecer'],
    categoria: 'vergonha_social',
    dificuldade: 'medio',
    tipo: 'vergonha_social',
    energiaEmocional: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'vs04',
    palavra: 'Apertar a mão de quem queria dar beijo',
    proibidas: ['cumprimentar', 'abraço', 'beijo', 'mão', 'constrangimento'],
    categoria: 'vergonha_social',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 2,
    taxaAcertoEsperada: 0.75,
  },
  {
    id: 'vs05',
    palavra: 'Tropeçar na frente de todo mundo',
    proibidas: ['cair', 'frente', 'público', 'escorregar', 'pé'],
    categoria: 'vergonha_social',
    dificuldade: 'facil',
    tipo: 'vergonha_social',
    energiaEmocional: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'vs06',
    palavra: 'Deixar no visto',
    proibidas: ['ler', 'ignorar', 'responder', 'mensagem', 'azul'],
    categoria: 'vergonha_social',
    dificuldade: 'medio',
    tipo: 'meme_contemporaneo',
    energiaEmocional: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'vs07',
    palavra: 'Chamar o professor de mãe',
    proibidas: ['escola', 'aula', 'professor', 'envergonhar', 'chamar'],
    categoria: 'vergonha_social',
    dificuldade: 'facil',
    tipo: 'vergonha_social',
    energiaEmocional: 2,
    taxaAcertoEsperada: 0.80,
  },
  {
    id: 'vs08',
    palavra: 'Sair do elevador no andar errado',
    proibidas: ['elevador', 'andar', 'errado', 'porta', 'entrar'],
    categoria: 'vergonha_social',
    dificuldade: 'facil',
    tipo: 'situacao_social',
    energiaEmocional: 1,
    taxaAcertoEsperada: 0.85,
  },
  {
    id: 'vs09',
    palavra: 'Mandar mensagem para o contato errado',
    proibidas: ['mensagem', 'errado', 'chat', 'enviar', 'contato'],
    categoria: 'vergonha_social',
    dificuldade: 'dificil',
    tipo: 'vergonha_social',
    energiaEmocional: 4,
    taxaAcertoEsperada: 0.35,
  },
  {
    id: 'vs10',
    palavra: 'Stalkear o ex e dar like sem querer',
    proibidas: ['curtir', 'Instagram', 'ex', 'foto', 'acidente'],
    categoria: 'vergonha_social',
    dificuldade: 'dificil',
    tipo: 'vergonha_social',
    energiaEmocional: 4,
    taxaAcertoEsperada: 0.30,
  },

  // ══════════════════════════════════════════════════════════════════════
  // INTERNET BR — cartas adicionais (ib13–ib16)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'ib13',
    palavra: 'Deixou em delivered',
    proibidas: ['entregar', 'receber', 'ignorar', 'mensagem', 'azul'],
    categoria: 'internet_br',
    dificuldade: 'dificil',
    tipo: 'meme_contemporaneo',
    energiaEmocional: 4,
    taxaAcertoEsperada: 0.30,
  },
  {
    id: 'ib14',
    palavra: 'Mutar grupo do zap',
    proibidas: ['silenciar', 'grupo', 'WhatsApp', 'notificação', 'desligar'],
    categoria: 'internet_br',
    dificuldade: 'medio',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'ib15',
    palavra: 'Tweet deletado',
    proibidas: ['apagar', 'publicar', 'arrepender', 'Twitter', 'post'],
    categoria: 'internet_br',
    dificuldade: 'dificil',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    taxaAcertoEsperada: 0.35,
  },
  {
    id: 'ib16',
    palavra: 'Finsta',
    proibidas: ['conta', 'falso', 'Instagram', 'secreto', 'privado'],
    categoria: 'internet_br',
    dificuldade: 'dificil',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    taxaAcertoEsperada: 0.30,
  },

  // ══════════════════════════════════════════════════════════════════════
  // RELACIONAMENTOS — cartas adicionais (rl13–rl16)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'rl13',
    palavra: 'Stalkear o ex',
    proibidas: ['perfil', 'bisbilhotar', 'foto', 'passado', 'Instagram'],
    categoria: 'relacionamentos',
    dificuldade: 'medio',
    tipo: 'situacao_social',
    energiaEmocional: 3,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'rl14',
    palavra: 'Friendzone',
    proibidas: ['amigo', 'interesse', 'apenas', 'gostar', 'zona'],
    categoria: 'relacionamentos',
    dificuldade: 'dificil',
    tipo: 'contradicao',
    energiaEmocional: 4,
    taxaAcertoEsperada: 0.35,
  },
  {
    id: 'rl15',
    palavra: 'Relacionamento tóxico',
    proibidas: ['veneno', 'prejudicar', 'dependente', 'abusivo', 'mal'],
    categoria: 'relacionamentos',
    dificuldade: 'dificil',
    tipo: 'pressao_social',
    energiaEmocional: 4,
    taxaAcertoEsperada: 0.30,
  },
  {
    id: 'rl16',
    palavra: 'Gostar de alguém que já tem alguém',
    proibidas: ['comprometido', 'namorado', 'impossível', 'proibido', 'triângulo'],
    categoria: 'relacionamentos',
    dificuldade: 'dificil',
    tipo: 'micro_cena',
    energiaEmocional: 4,
    taxaAcertoEsperada: 0.25,
  },

  // ══════════════════════════════════════════════════════════════════════
  // MEMES BR — cartas adicionais (mb13–mb16)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'mb13',
    palavra: '"Não to bem não"',
    proibidas: ['mal', 'triste', 'resposta', 'frase', 'expressão'],
    categoria: 'memes_br',
    dificuldade: 'medio',
    tipo: 'oralidade_pura',
    energiaEmocional: 3,
    taxaAcertoEsperada: 0.55,
  },
  {
    id: 'mb14',
    palavra: '"Que isso mano"',
    proibidas: ['espanto', 'exclamação', 'gíria', 'expressão', 'absurdo'],
    categoria: 'memes_br',
    dificuldade: 'medio',
    tipo: 'frase_br',
    energiaEmocional: 2,
    taxaAcertoEsperada: 0.60,
  },
  {
    id: 'mb15',
    palavra: '"Imagina a cena"',
    proibidas: ['cenário', 'imagine', 'situação', 'hipotético', 'visualizar'],
    categoria: 'memes_br',
    dificuldade: 'dificil',
    tipo: 'micro_cena',
    energiaEmocional: 4,
    taxaAcertoEsperada: 0.28,
  },
  {
    id: 'mb16',
    palavra: '"Tô vivendo"',
    proibidas: ['animado', 'feliz', 'curtindo', 'viver', 'expressão'],
    categoria: 'memes_br',
    dificuldade: 'medio',
    tipo: 'oralidade_pura',
    energiaEmocional: 3,
    taxaAcertoEsperada: 0.50,
  },
];

export const TOTAL_CARTAS = CARTAS.length; // 263
