import type { Carta } from '@/games/na-ponta-da-lingua/types';

/**
 * 120 cartas — Na Ponta da Língua.
 *
 * As palavras proibidas são exatamente as mais óbvias e naturais
 * para descrever a palavra-alvo. Sem elas, o jogador precisa improvisar.
 *
 * Regra de ouro das proibidas: se você fosse explicar a palavra em 5
 * segundos, essas são as 5 primeiras que sairiam pela boca.
 */
export const CARTAS: ReadonlyArray<Carta> = [

  // ══════════════════════════════════════════════════════════════════════
  // INTERNET BR — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'ib01',
    palavra: 'Meme',
    proibidas: ['viral', 'engraçado', 'internet', 'imagem', 'compartilhar'],
    categoria: 'internet_br',
    dificuldade: 'facil',
  },
  {
    id: 'ib02',
    palavra: 'Print de tela',
    proibidas: ['captura', 'screenshot', 'tela', 'foto', 'celular'],
    categoria: 'internet_br',
    dificuldade: 'facil',
  },
  {
    id: 'ib03',
    palavra: 'Stories',
    proibidas: ['Instagram', 'foto', 'publicar', '24 horas', 'desaparecer'],
    categoria: 'internet_br',
    dificuldade: 'facil',
  },
  {
    id: 'ib04',
    palavra: 'Figurinha do Zap',
    proibidas: ['sticker', 'WhatsApp', 'enviar', 'chat', 'emoji'],
    categoria: 'internet_br',
    dificuldade: 'facil',
  },
  {
    id: 'ib05',
    palavra: 'Influencer',
    proibidas: ['seguidor', 'Instagram', 'marca', 'patrocínio', 'conteúdo'],
    categoria: 'internet_br',
    dificuldade: 'medio',
  },
  {
    id: 'ib06',
    palavra: 'Fake News',
    proibidas: ['mentira', 'notícia', 'falsa', 'WhatsApp', 'viral'],
    categoria: 'internet_br',
    dificuldade: 'facil',
  },
  {
    id: 'ib07',
    palavra: 'Live',
    proibidas: ['ao vivo', 'transmissão', 'streaming', 'celular', 'redes'],
    categoria: 'internet_br',
    dificuldade: 'facil',
  },
  {
    id: 'ib08',
    palavra: 'Cancelamento',
    proibidas: ['polêmica', 'internet', 'famoso', 'redes', 'boicote'],
    categoria: 'internet_br',
    dificuldade: 'medio',
  },
  {
    id: 'ib09',
    palavra: 'TBT',
    proibidas: ['passado', 'foto', 'antiga', 'nostalgia', 'postar'],
    categoria: 'internet_br',
    dificuldade: 'medio',
  },
  {
    id: 'ib10',
    palavra: 'Algoritmo',
    proibidas: ['sugestão', 'feed', 'vídeo', 'app', 'mostrar'],
    categoria: 'internet_br',
    dificuldade: 'dificil',
  },
  {
    id: 'ib11',
    palavra: 'Reels',
    proibidas: ['vídeo', 'Instagram', 'curto', 'rolar', 'conteúdo'],
    categoria: 'internet_br',
    dificuldade: 'facil',
  },
  {
    id: 'ib12',
    palavra: 'Stalkar',
    proibidas: ['ver', 'perfil', 'foto', 'olhar', 'redes'],
    categoria: 'internet_br',
    dificuldade: 'medio',
  },

  // ══════════════════════════════════════════════════════════════════════
  // COTIDIANO — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'co01',
    palavra: 'Ressaca',
    proibidas: ['beber', 'dor', 'cabeça', 'álcool', 'manhã'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
  },
  {
    id: 'co02',
    palavra: 'Delivery',
    proibidas: ['pedir', 'comida', 'motoboy', 'aplicativo', 'entregar'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
  },
  {
    id: 'co03',
    palavra: 'Pix',
    proibidas: ['transferência', 'dinheiro', 'banco', 'celular', 'pagar'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
  },
  {
    id: 'co04',
    palavra: 'Fila do banco',
    proibidas: ['esperar', 'lento', 'banco', 'vez', 'paciência'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
  },
  {
    id: 'co05',
    palavra: 'Trânsito',
    proibidas: ['carro', 'lento', 'rua', 'engarrafamento', 'hora'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
  },
  {
    id: 'co06',
    palavra: 'Soneca',
    proibidas: ['dormir', 'breve', 'tarde', 'cama', 'descanso'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
  },
  {
    id: 'co07',
    palavra: 'Promoção relâmpago',
    proibidas: ['desconto', 'barato', 'oferta', 'comprar', 'preço'],
    categoria: 'cotidiano',
    dificuldade: 'medio',
  },
  {
    id: 'co08',
    palavra: 'Reunião inútil',
    proibidas: ['trabalho', 'reunião', 'empresa', 'chato', 'conversa'],
    categoria: 'cotidiano',
    dificuldade: 'medio',
  },
  {
    id: 'co09',
    palavra: 'Marmita',
    proibidas: ['comida', 'trabalho', 'pote', 'levar', 'almoço'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
  },
  {
    id: 'co10',
    palavra: 'Procrastinar',
    proibidas: ['deixar', 'amanhã', 'atrasar', 'fazer', 'preguiça'],
    categoria: 'cotidiano',
    dificuldade: 'medio',
  },
  {
    id: 'co11',
    palavra: 'Boleto vencido',
    proibidas: ['pagar', 'conta', 'multa', 'banco', 'atraso'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
  },
  {
    id: 'co12',
    palavra: 'Vizinho barulhento',
    proibidas: ['barulho', 'apartamento', 'noite', 'reclamar', 'prédio'],
    categoria: 'cotidiano',
    dificuldade: 'facil',
  },

  // ══════════════════════════════════════════════════════════════════════
  // COMIDA — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'cm01',
    palavra: 'Coxinha',
    proibidas: ['frango', 'frito', 'massa', 'salgado', 'festa'],
    categoria: 'comida',
    dificuldade: 'facil',
  },
  {
    id: 'cm02',
    palavra: 'Brigadeiro',
    proibidas: ['chocolate', 'bola', 'leite', 'doce', 'festa'],
    categoria: 'comida',
    dificuldade: 'facil',
  },
  {
    id: 'cm03',
    palavra: 'Açaí',
    proibidas: ['roxo', 'gelado', 'frutas', 'tigela', 'norte'],
    categoria: 'comida',
    dificuldade: 'facil',
  },
  {
    id: 'cm04',
    palavra: 'Churrasco',
    proibidas: ['carne', 'fogo', 'espeto', 'grelha', 'churrasqueira'],
    categoria: 'comida',
    dificuldade: 'facil',
  },
  {
    id: 'cm05',
    palavra: 'Pão de queijo',
    proibidas: ['queijo', 'forno', 'mineiro', 'pequeno', 'massa'],
    categoria: 'comida',
    dificuldade: 'facil',
  },
  {
    id: 'cm06',
    palavra: 'Pastel de feira',
    proibidas: ['fritar', 'feira', 'massa', 'recheio', 'quente'],
    categoria: 'comida',
    dificuldade: 'facil',
  },
  {
    id: 'cm07',
    palavra: 'Tapioca',
    proibidas: ['nordeste', 'mandioca', 'massa', 'café', 'fino'],
    categoria: 'comida',
    dificuldade: 'facil',
  },
  {
    id: 'cm08',
    palavra: 'Caipirinha',
    proibidas: ['limão', 'cachaça', 'açúcar', 'bebida', 'coquetel'],
    categoria: 'comida',
    dificuldade: 'facil',
  },
  {
    id: 'cm09',
    palavra: 'Guaraná Antarctica',
    proibidas: ['refrigerante', 'bebida', 'verde', 'doce', 'gaseificado'],
    categoria: 'comida',
    dificuldade: 'medio',
  },
  {
    id: 'cm10',
    palavra: 'Pudim de leite',
    proibidas: ['doce', 'leite', 'forno', 'calda', 'gelatinoso'],
    categoria: 'comida',
    dificuldade: 'facil',
  },
  {
    id: 'cm11',
    palavra: 'Feijão tropeiro',
    proibidas: ['feijão', 'farinha', 'mineiro', 'bacon', 'misturar'],
    categoria: 'comida',
    dificuldade: 'medio',
  },
  {
    id: 'cm12',
    palavra: 'Galinha caipira',
    proibidas: ['frango', 'roça', 'carne', 'interior', 'cozinhar'],
    categoria: 'comida',
    dificuldade: 'medio',
  },

  // ══════════════════════════════════════════════════════════════════════
  // CULTURA POP — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'cp01',
    palavra: 'BBB',
    proibidas: ['reality', 'Globo', 'paredão', 'eliminação', 'confinamento'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
  },
  {
    id: 'cp02',
    palavra: 'Funk carioca',
    proibidas: ['baile', 'ritmo', 'dançar', 'favela', 'música'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
  },
  {
    id: 'cp03',
    palavra: 'Carnaval',
    proibidas: ['fantasia', 'samba', 'confete', 'bloco', 'desfile'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
  },
  {
    id: 'cp04',
    palavra: 'Novela da Globo',
    proibidas: ['televisão', 'Globo', 'casal', 'capítulo', 'traição'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
  },
  {
    id: 'cp05',
    palavra: 'Pagode',
    proibidas: ['roda', 'violão', 'samba', 'cerveja', 'amigos'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
  },
  {
    id: 'cp06',
    palavra: 'TikToker',
    proibidas: ['vídeo', 'dança', 'jovem', 'viral', 'app'],
    categoria: 'cultura_pop',
    dificuldade: 'medio',
  },
  {
    id: 'cp07',
    palavra: 'Podcast',
    proibidas: ['áudio', 'episódio', 'ouvir', 'entrevista', 'microfone'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
  },
  {
    id: 'cp08',
    palavra: 'Sertanejo universitário',
    proibidas: ['dupla', 'música', 'amor', 'chapéu', 'universidade'],
    categoria: 'cultura_pop',
    dificuldade: 'medio',
  },
  {
    id: 'cp09',
    palavra: 'Forró',
    proibidas: ['dançar', 'nordeste', 'sanfona', 'par', 'ritmo'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
  },
  {
    id: 'cp10',
    palavra: 'Reality show',
    proibidas: ['televisão', 'programa', 'competição', 'câmera', 'eliminação'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
  },
  {
    id: 'cp11',
    palavra: 'Crossfit',
    proibidas: ['academia', 'treino', 'exercício', 'pesado', 'forte'],
    categoria: 'cultura_pop',
    dificuldade: 'facil',
  },
  {
    id: 'cp12',
    palavra: 'Ostentação',
    proibidas: ['rico', 'carro', 'dinheiro', 'exibir', 'luxo'],
    categoria: 'cultura_pop',
    dificuldade: 'medio',
  },

  // ══════════════════════════════════════════════════════════════════════
  // OBJETOS — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'ob01',
    palavra: 'Chinelo',
    proibidas: ['pé', 'sandália', 'borracha', 'usar', 'calçado'],
    categoria: 'objetos',
    dificuldade: 'facil',
  },
  {
    id: 'ob02',
    palavra: 'Isopor de cerveja',
    proibidas: ['caixa', 'bebida', 'branco', 'frio', 'praia'],
    categoria: 'objetos',
    dificuldade: 'facil',
  },
  {
    id: 'ob03',
    palavra: 'Ventilador',
    proibidas: ['vento', 'calor', 'girar', 'elétrico', 'ar'],
    categoria: 'objetos',
    dificuldade: 'facil',
  },
  {
    id: 'ob04',
    palavra: 'Botijão de gás',
    proibidas: ['gás', 'laranja', 'cozinha', 'fogão', 'trocar'],
    categoria: 'objetos',
    dificuldade: 'facil',
  },
  {
    id: 'ob05',
    palavra: 'Panela de pressão',
    proibidas: ['vapor', 'barulho', 'feijão', 'cozinhar', 'tampa'],
    categoria: 'objetos',
    dificuldade: 'facil',
  },
  {
    id: 'ob06',
    palavra: 'Chuveiro elétrico',
    proibidas: ['banho', 'água', 'quente', 'fio', 'tomada'],
    categoria: 'objetos',
    dificuldade: 'facil',
  },
  {
    id: 'ob07',
    palavra: 'Varal de roupa',
    proibidas: ['roupa', 'secar', 'sol', 'pendurar', 'varanda'],
    categoria: 'objetos',
    dificuldade: 'facil',
  },
  {
    id: 'ob08',
    palavra: 'Extintor de incêndio',
    proibidas: ['fogo', 'vermelho', 'cilindro', 'apagar', 'espuma'],
    categoria: 'objetos',
    dificuldade: 'facil',
  },
  {
    id: 'ob09',
    palavra: 'Máquina de lavar',
    proibidas: ['roupa', 'lavar', 'tambor', 'girar', 'detergente'],
    categoria: 'objetos',
    dificuldade: 'facil',
  },
  {
    id: 'ob10',
    palavra: 'Mata-mosquito elétrico',
    proibidas: ['mosquito', 'matar', 'elétrico', 'luz', 'roxo'],
    categoria: 'objetos',
    dificuldade: 'medio',
  },
  {
    id: 'ob11',
    palavra: 'Garrafa de cachaça',
    proibidas: ['cachaça', 'bebida', 'vidro', 'garrafa', 'álcool'],
    categoria: 'objetos',
    dificuldade: 'medio',
  },
  {
    id: 'ob12',
    palavra: 'Cadeado',
    proibidas: ['fechar', 'chave', 'travar', 'segurança', 'abrir'],
    categoria: 'objetos',
    dificuldade: 'medio',
  },

  // ══════════════════════════════════════════════════════════════════════
  // PROFISSOES — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'pr01',
    palavra: 'Motorista de aplicativo',
    proibidas: ['carro', 'aplicativo', 'passageiro', 'corrida', 'avaliar'],
    categoria: 'profissoes',
    dificuldade: 'facil',
  },
  {
    id: 'pr02',
    palavra: 'Motoboy',
    proibidas: ['moto', 'entrega', 'rua', 'rápido', 'chuva'],
    categoria: 'profissoes',
    dificuldade: 'facil',
  },
  {
    id: 'pr03',
    palavra: 'Médico plantonista',
    proibidas: ['hospital', 'plantão', 'noite', 'emergência', 'médico'],
    categoria: 'profissoes',
    dificuldade: 'medio',
  },
  {
    id: 'pr04',
    palavra: 'Garçom',
    proibidas: ['mesa', 'pedido', 'servir', 'restaurante', 'prato'],
    categoria: 'profissoes',
    dificuldade: 'facil',
  },
  {
    id: 'pr05',
    palavra: 'Gari',
    proibidas: ['lixo', 'rua', 'vassoura', 'limpeza', 'uniforme'],
    categoria: 'profissoes',
    dificuldade: 'facil',
  },
  {
    id: 'pr06',
    palavra: 'Pastor evangélico',
    proibidas: ['Deus', 'igreja', 'pregação', 'bíblia', 'congregação'],
    categoria: 'profissoes',
    dificuldade: 'facil',
  },
  {
    id: 'pr07',
    palavra: 'Caixa de supermercado',
    proibidas: ['fila', 'compras', 'registrar', 'mercado', 'passar'],
    categoria: 'profissoes',
    dificuldade: 'facil',
  },
  {
    id: 'pr08',
    palavra: 'Vendedor ambulante',
    proibidas: ['rua', 'produto', 'vender', 'gritar', 'carrinho'],
    categoria: 'profissoes',
    dificuldade: 'facil',
  },
  {
    id: 'pr09',
    palavra: 'Personal trainer',
    proibidas: ['academia', 'treino', 'exercício', 'músculo', 'dieta'],
    categoria: 'profissoes',
    dificuldade: 'facil',
  },
  {
    id: 'pr10',
    palavra: 'Nutricionista',
    proibidas: ['dieta', 'alimentação', 'saúde', 'comer', 'consulta'],
    categoria: 'profissoes',
    dificuldade: 'facil',
  },
  {
    id: 'pr11',
    palavra: 'Corretor de imóveis',
    proibidas: ['casa', 'vender', 'comprar', 'imóvel', 'comissão'],
    categoria: 'profissoes',
    dificuldade: 'medio',
  },
  {
    id: 'pr12',
    palavra: 'Dono de mercadinho',
    proibidas: ['loja', 'vender', 'produto', 'bairro', 'comprar'],
    categoria: 'profissoes',
    dificuldade: 'medio',
  },

  // ══════════════════════════════════════════════════════════════════════
  // FESTAS — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'ft01',
    palavra: 'Aniversário surpresa',
    proibidas: ['parabéns', 'bolo', 'vela', 'presente', 'surpresa'],
    categoria: 'festas',
    dificuldade: 'facil',
  },
  {
    id: 'ft02',
    palavra: 'Balada',
    proibidas: ['noite', 'boate', 'dançar', 'bebida', 'clube'],
    categoria: 'festas',
    dificuldade: 'facil',
  },
  {
    id: 'ft03',
    palavra: 'Churrasco de domingo',
    proibidas: ['carne', 'cerveja', 'quintal', 'família', 'domingo'],
    categoria: 'festas',
    dificuldade: 'facil',
  },
  {
    id: 'ft04',
    palavra: 'Festa junina',
    proibidas: ['forró', 'bandeirinha', 'arraial', 'nordeste', 'quadrilha'],
    categoria: 'festas',
    dificuldade: 'facil',
  },
  {
    id: 'ft05',
    palavra: 'Happy hour',
    proibidas: ['trabalho', 'bar', 'amigos', 'cerveja', 'sair'],
    categoria: 'festas',
    dificuldade: 'facil',
  },
  {
    id: 'ft06',
    palavra: 'Formatura',
    proibidas: ['faculdade', 'baile', 'diploma', 'colação', 'conquista'],
    categoria: 'festas',
    dificuldade: 'facil',
  },
  {
    id: 'ft07',
    palavra: 'Casamento',
    proibidas: ['noiva', 'noivo', 'cerimônia', 'aliança', 'festa'],
    categoria: 'festas',
    dificuldade: 'facil',
  },
  {
    id: 'ft08',
    palavra: 'Pagode na laje',
    proibidas: ['samba', 'cerveja', 'laje', 'morro', 'violão'],
    categoria: 'festas',
    dificuldade: 'medio',
  },
  {
    id: 'ft09',
    palavra: 'Réveillon',
    proibidas: ['ano', 'virada', 'fogos', 'praia', 'meia-noite'],
    categoria: 'festas',
    dificuldade: 'facil',
  },
  {
    id: 'ft10',
    palavra: 'Pré-balada',
    proibidas: ['preparar', 'arranjar', 'roupa', 'espelho', 'sair'],
    categoria: 'festas',
    dificuldade: 'medio',
  },
  {
    id: 'ft11',
    palavra: 'Rave',
    proibidas: ['eletrônica', 'noite', 'dança', 'festival', 'campo'],
    categoria: 'festas',
    dificuldade: 'medio',
  },
  {
    id: 'ft12',
    palavra: 'Ressaca de segunda',
    proibidas: ['cansado', 'dor', 'segunda', 'bebida', 'dormir'],
    categoria: 'festas',
    dificuldade: 'facil',
  },

  // ══════════════════════════════════════════════════════════════════════
  // RELACIONAMENTOS — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'rl01',
    palavra: 'Crush',
    proibidas: ['gostar', 'nervoso', 'sentir', 'pessoa', 'olhar'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
  },
  {
    id: 'rl02',
    palavra: 'Ghosting',
    proibidas: ['sumir', 'ignorar', 'mensagem', 'desaparecer', 'responder'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
  },
  {
    id: 'rl03',
    palavra: 'Término',
    proibidas: ['acabar', 'chorar', 'separar', 'casal', 'fim'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
  },
  {
    id: 'rl04',
    palavra: 'Amizade colorida',
    proibidas: ['amigo', 'íntimo', 'compromisso', 'relação', 'ficar'],
    categoria: 'relacionamentos',
    dificuldade: 'medio',
  },
  {
    id: 'rl05',
    palavra: 'Tinder',
    proibidas: ['swipe', 'match', 'app', 'foto', 'encontrar'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
  },
  {
    id: 'rl06',
    palavra: 'Ciúme',
    proibidas: ['inseguro', 'bravo', 'sentir', 'relacionamento', 'olhar'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
  },
  {
    id: 'rl07',
    palavra: 'Pedido de namoro',
    proibidas: ['querer', 'namorar', 'surpresa', 'coração', 'sim'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
  },
  {
    id: 'rl08',
    palavra: 'Ex que some',
    proibidas: ['passado', 'sumir', 'lembrar', 'antigo', 'saudade'],
    categoria: 'relacionamentos',
    dificuldade: 'medio',
  },
  {
    id: 'rl09',
    palavra: 'Declaração por mensagem',
    proibidas: ['mandar', 'texto', 'coração', 'mensagem', 'sentir'],
    categoria: 'relacionamentos',
    dificuldade: 'medio',
  },
  {
    id: 'rl10',
    palavra: 'Briga de casal',
    proibidas: ['discutir', 'bravo', 'gritar', 'casal', 'resolver'],
    categoria: 'relacionamentos',
    dificuldade: 'facil',
  },
  {
    id: 'rl11',
    palavra: 'Recaída',
    proibidas: ['voltar', 'ex', 'errar', 'repetir', 'fraqueza'],
    categoria: 'relacionamentos',
    dificuldade: 'medio',
  },
  {
    id: 'rl12',
    palavra: 'Parceiro casual',
    proibidas: ['ficar', 'íntimo', 'sem', 'comprometimento', 'relação'],
    categoria: 'relacionamentos',
    dificuldade: 'dificil',
  },

  // ══════════════════════════════════════════════════════════════════════
  // LUGARES — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'lg01',
    palavra: 'Centro de São Paulo',
    proibidas: ['metrô', 'grande', 'movimentado', 'prédio', 'barulho'],
    categoria: 'lugares',
    dificuldade: 'facil',
  },
  {
    id: 'lg02',
    palavra: 'Favela',
    proibidas: ['morro', 'comunidade', 'Rio', 'laje', 'morador'],
    categoria: 'lugares',
    dificuldade: 'facil',
  },
  {
    id: 'lg03',
    palavra: 'Posto de gasolina',
    proibidas: ['carro', 'abastecer', 'combustível', 'parar', 'estrada'],
    categoria: 'lugares',
    dificuldade: 'facil',
  },
  {
    id: 'lg04',
    palavra: 'Padaria',
    proibidas: ['pão', 'fresco', 'manhã', 'balcão', 'café'],
    categoria: 'lugares',
    dificuldade: 'facil',
  },
  {
    id: 'lg05',
    palavra: 'Feira livre',
    proibidas: ['comprar', 'barato', 'cheiro', 'ambulante', 'frutas'],
    categoria: 'lugares',
    dificuldade: 'facil',
  },
  {
    id: 'lg06',
    palavra: 'Interior do Brasil',
    proibidas: ['roça', 'pequeno', 'tranquilo', 'campo', 'longe'],
    categoria: 'lugares',
    dificuldade: 'facil',
  },
  {
    id: 'lg07',
    palavra: 'Amazônia',
    proibidas: ['floresta', 'verde', 'rio', 'natureza', 'selva'],
    categoria: 'lugares',
    dificuldade: 'facil',
  },
  {
    id: 'lg08',
    palavra: 'Aeroporto',
    proibidas: ['avião', 'voo', 'embarque', 'passagem', 'portão'],
    categoria: 'lugares',
    dificuldade: 'facil',
  },
  {
    id: 'lg09',
    palavra: 'Beco escuro',
    proibidas: ['rua', 'pequena', 'escuro', 'entrada', 'estreito'],
    categoria: 'lugares',
    dificuldade: 'medio',
  },
  {
    id: 'lg10',
    palavra: 'Litoral nordestino',
    proibidas: ['praia', 'mar', 'nordeste', 'calor', 'sol'],
    categoria: 'lugares',
    dificuldade: 'facil',
  },
  {
    id: 'lg11',
    palavra: 'Periferia',
    proibidas: ['bairro', 'longe', 'ônibus', 'subúrbio', 'cidade'],
    categoria: 'lugares',
    dificuldade: 'medio',
  },
  {
    id: 'lg12',
    palavra: 'Orla de Copacabana',
    proibidas: ['praia', 'Rio', 'calçadão', 'mar', 'areia'],
    categoria: 'lugares',
    dificuldade: 'medio',
  },

  // ══════════════════════════════════════════════════════════════════════
  // BRASIL — 12 cartas
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'br01',
    palavra: 'Jeitinho brasileiro',
    proibidas: ['problema', 'solução', 'criativo', 'jeito', 'improviso'],
    categoria: 'brasil',
    dificuldade: 'dificil',
  },
  {
    id: 'br02',
    palavra: 'Copa do Mundo',
    proibidas: ['futebol', 'seleção', 'mundial', 'torcer', 'gol'],
    categoria: 'brasil',
    dificuldade: 'facil',
  },
  {
    id: 'br03',
    palavra: 'Décimo terceiro',
    proibidas: ['extra', 'dezembro', 'dinheiro', 'receber', 'trabalho'],
    categoria: 'brasil',
    dificuldade: 'medio',
  },
  {
    id: 'br04',
    palavra: 'Burocracia',
    proibidas: ['documento', 'governo', 'fila', 'papel', 'esperar'],
    categoria: 'brasil',
    dificuldade: 'medio',
  },
  {
    id: 'br05',
    palavra: 'Samba no pé',
    proibidas: ['dança', 'ritmo', 'carnaval', 'quadril', 'habilidade'],
    categoria: 'brasil',
    dificuldade: 'medio',
  },
  {
    id: 'br06',
    palavra: 'Reunião de condomínio',
    proibidas: ['vizinho', 'prédio', 'barulho', 'reclamar', 'reunir'],
    categoria: 'brasil',
    dificuldade: 'medio',
  },
  {
    id: 'br07',
    palavra: 'Rachar a conta',
    proibidas: ['dividir', 'pagar', 'conta', 'restaurante', 'amigos'],
    categoria: 'brasil',
    dificuldade: 'facil',
  },
  {
    id: 'br08',
    palavra: 'Apagão',
    proibidas: ['luz', 'energia', 'escuro', 'cortar', 'noite'],
    categoria: 'brasil',
    dificuldade: 'facil',
  },
  {
    id: 'br09',
    palavra: 'Malandragem',
    proibidas: ['esperto', 'enganar', 'rua', 'charme', 'viver'],
    categoria: 'brasil',
    dificuldade: 'dificil',
  },
  {
    id: 'br10',
    palavra: 'Salário mínimo',
    proibidas: ['salário', 'mínimo', 'governo', 'trabalho', 'pagar'],
    categoria: 'brasil',
    dificuldade: 'medio',
  },
  {
    id: 'br11',
    palavra: 'Feriado nacional',
    proibidas: ['folga', 'trabalho', 'descanso', 'dia', 'comemorar'],
    categoria: 'brasil',
    dificuldade: 'facil',
  },
  {
    id: 'br12',
    palavra: 'Nota fiscal',
    proibidas: ['compra', 'imposto', 'recibo', 'documento', 'loja'],
    categoria: 'brasil',
    dificuldade: 'medio',
  },
];

export const TOTAL_CARTAS = CARTAS.length; // 120
