import type { Prompt } from '@/games/most-likely-to/types';

/**
 * Banco de prompts do Most Likely To — sistema premium de revelação social.
 *
 * Energia:
 *  leve    → seguro para qualquer grupo; primeiras rodadas; humor sem risco
 *  medio   → requer conhecimento mútuo; alguma exposição; caos controlado
 *  intenso → vulnerabilidade real; modo Sincero; silêncio antes da risada
 *
 * O engine consome apenas `texto` e `energia`.
 * Os campos de metadata (tags, potencialUnanimidade, vulnerabilidade, caos,
 * intensidadeSocial, categoria) são ignorados pelo engine e existem
 * para curadoria, decks temáticos e recommendation engine futuros.
 *
 * Sequenciamento:
 *  Rodada 1 → apenas leve
 *  Rodadas 2–3 → leve + medio
 *  Rodadas 4+ → leve + medio (+ intenso em modo Sincero)
 */
export const PROMPTS: ReadonlyArray<Prompt> = [

  // ══════════════════════════════════════════════════════════════════════════
  // LEVE — comportamento sem risco, humor imediato, alta unanimidade
  // ══════════════════════════════════════════════════════════════════════════

  // ── Comportamento cotidiano ────────────────────────────────────────────
  {
    id: 'l01',
    texto: 'quem mais provavelmente diria "tô chegando" ainda dentro de casa?',
    energia: 'leve',
    tags: ['comportamento', 'unanimidade'],
    potencialUnanimidade: 9,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'cotidiano',
  },
  {
    id: 'l02',
    texto: 'quem mais provavelmente pediria "5 minutinhos" e apareceria 40 depois?',
    energia: 'leve',
    tags: ['comportamento', 'unanimidade'],
    potencialUnanimidade: 9,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'cotidiano',
  },
  {
    id: 'l03',
    texto: 'quem mais provavelmente chegaria atrasado a um casamento?',
    energia: 'leve',
    tags: ['comportamento', 'unanimidade'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'cotidiano',
  },
  {
    id: 'l04',
    texto: 'quem mais provavelmente tentaria negociar o preço de tudo?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l05',
    texto: 'quem mais provavelmente assistiria uma série inteira num fim de semana?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },
  {
    id: 'l06',
    texto: 'quem mais provavelmente esqueceria o nome de alguém que acabou de conhecer?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l07',
    texto: 'quem mais provavelmente mandaria mensagem para a pessoa errada?',
    energia: 'leve',
    tags: ['comportamento', 'digital', 'humor'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'cotidiano',
  },
  {
    id: 'l08',
    texto: 'quem mais provavelmente compraria algo que nunca vai usar?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },
  {
    id: 'l09',
    texto: 'quem mais provavelmente se perderia mesmo com GPS ligado?',
    energia: 'leve',
    tags: ['comportamento', 'humor', 'unanimidade'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l10',
    texto: 'quem mais provavelmente trocaria de roupa três vezes antes de sair?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l11',
    texto: 'quem mais provavelmente ia esquecer o carregador em toda viagem?',
    energia: 'leve',
    tags: ['comportamento', 'viagem', 'unanimidade'],
    potencialUnanimidade: 8,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },
  {
    id: 'l12',
    texto: 'quem mais provavelmente mandaria áudio de cinco minutos?',
    energia: 'leve',
    tags: ['comportamento', 'digital', 'humor'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'cotidiano',
  },
  {
    id: 'l13',
    texto: 'quem mais provavelmente teria um apelido constrangedor que a família ainda usa?',
    energia: 'leve',
    tags: ['familia', 'humor'],
    potencialUnanimidade: 6,
    caos: 7,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l14',
    texto: 'quem mais provavelmente comeria a parte de todo mundo?',
    energia: 'leve',
    tags: ['comida', 'humor', 'unanimidade'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l15',
    texto: 'quem mais provavelmente viajaria sem planejar absolutamente nada?',
    energia: 'leve',
    tags: ['viagem', 'comportamento'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'viagem',
  },
  {
    id: 'l16',
    texto: 'quem mais provavelmente falaria sem parar numa viagem de carro?',
    energia: 'leve',
    tags: ['viagem', 'comportamento', 'humor'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l17',
    texto: 'quem mais provavelmente dormia antes da meia-noite numa festa?',
    energia: 'leve',
    tags: ['festa', 'humor'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'festa',
  },
  {
    id: 'l18',
    texto: 'quem mais provavelmente chegaria na casa do outro sem avisar?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l19',
    texto: 'quem mais provavelmente ficaria falando de uma série que ninguém mais assistiu?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },
  {
    id: 'l20',
    texto: 'quem mais provavelmente colocaria alarme às 5h e desligaria sem nem acordar?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },

  // ── Digital e redes sociais ────────────────────────────────────────────
  {
    id: 'l21',
    texto: 'quem mais provavelmente apagaria um story porque ninguém respondeu?',
    energia: 'leve',
    tags: ['digital', 'social_media', 'caos_social'],
    potencialUnanimidade: 8,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'digital_life',
  },
  {
    id: 'l22',
    texto: 'quem mais provavelmente gostaria de foto do crush de três anos atrás e descurtiria em pânico?',
    energia: 'leve',
    tags: ['digital', 'dating', 'humor'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'digital_life',
  },
  {
    id: 'l23',
    texto: 'quem mais provavelmente mandaria "oi" e nada mais?',
    energia: 'leve',
    tags: ['digital', 'comportamento', 'humor'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'digital_life',
  },
  {
    id: 'l24',
    texto: 'quem mais provavelmente tem mais de dez conversas abertas sem responder?',
    energia: 'leve',
    tags: ['digital', 'comportamento'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 5,
    categoria: 'digital_life',
  },
  {
    id: 'l25',
    texto: 'quem mais provavelmente teria o celular cheio de capturas de tela que nunca vai usar?',
    energia: 'leve',
    tags: ['digital', 'comportamento'],
    potencialUnanimidade: 6,
    caos: 4,
    intensidadeSocial: 4,
    categoria: 'digital_life',
  },
  {
    id: 'l26',
    texto: 'quem mais provavelmente fotografaria a comida por três ângulos antes de comer?',
    energia: 'leve',
    tags: ['digital', 'comida', 'unanimidade'],
    potencialUnanimidade: 9,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'digital_life',
  },
  {
    id: 'l27',
    texto: 'quem mais provavelmente passaria horas vendo vídeo curto sem perceber o tempo?',
    energia: 'leve',
    tags: ['digital', 'comportamento'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'digital_life',
  },
  {
    id: 'l28',
    texto: 'quem mais provavelmente ficaria esperando a bolinha de "digitando..." parar?',
    energia: 'leve',
    tags: ['digital', 'relacionamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'digital_life',
  },
  {
    id: 'l29',
    texto: 'quem mais provavelmente entraria no Instagram quarenta vezes num dia sem motivo?',
    energia: 'leve',
    tags: ['digital', 'social_media', 'humor'],
    potencialUnanimidade: 6,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'digital_life',
  },
  {
    id: 'l30',
    texto: 'quem mais provavelmente teria notificação de LinkedIn que nunca respondeu?',
    energia: 'leve',
    tags: ['digital', 'trabalho', 'brasil'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'digital_life',
  },

  // ── Brasil contemporâneo ───────────────────────────────────────────────
  {
    id: 'l31',
    texto: 'quem mais provavelmente teria uma saga épica com Uber cancelando?',
    energia: 'leve',
    tags: ['brasil', 'humor', 'unanimidade'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l32',
    texto: 'quem mais provavelmente mandaria PIX errado e ficaria esperando a outra pessoa perceber?',
    energia: 'leve',
    tags: ['brasil', 'caos_social', 'humor'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l33',
    texto: 'quem mais provavelmente pagaria academia e não ia por três meses?',
    energia: 'leve',
    tags: ['brasil', 'humor', 'unanimidade'],
    potencialUnanimidade: 9,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l34',
    texto: 'quem mais provavelmente chegaria ao churrasco sem trazer nada?',
    energia: 'leve',
    tags: ['brasil', 'comida', 'humor'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l35',
    texto: 'quem mais provavelmente chegaria ao rolê perguntando "já tem comida"?',
    energia: 'leve',
    tags: ['brasil', 'comida', 'humor'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l36',
    texto: 'quem mais provavelmente assumiria o papel de DJ da viagem sem ninguém pedir?',
    energia: 'leve',
    tags: ['brasil', 'viagem', 'humor'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 5,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l37',
    texto: 'quem mais provavelmente tentaria parcelar tudo em doze vezes?',
    energia: 'leve',
    tags: ['brasil', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l38',
    texto: 'quem mais provavelmente mandaria áudio passivo-agressivo e diria que não foi assim?',
    energia: 'leve',
    tags: ['brasil', 'relacionamento', 'caos_social'],
    potencialUnanimidade: 8,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l39',
    texto: 'quem mais provavelmente ia registrar a viagem inteira no Instagram antes de curtir ela?',
    energia: 'leve',
    tags: ['brasil', 'digital', 'viagem'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'digital_life',
  },
  {
    id: 'l40',
    texto: 'quem mais provavelmente montaria um IKEA e sobraria peça?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },

  // ── Comida e festas ────────────────────────────────────────────────────
  {
    id: 'l41',
    texto: 'quem mais provavelmente pediria a sobremesa mais cara do cardápio?',
    energia: 'leve',
    tags: ['comida', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },
  {
    id: 'l42',
    texto: 'quem mais provavelmente trocaria o pedido depois que o garçom foi embora?',
    energia: 'leve',
    tags: ['comida', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },
  {
    id: 'l43',
    texto: 'quem mais provavelmente provaria a comida de todo mundo sem pedir?',
    energia: 'leve',
    tags: ['comida', 'humor'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l44',
    texto: 'quem mais provavelmente escolheria o restaurante olhando só o preço mais baixo?',
    energia: 'leve',
    tags: ['comida', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },
  {
    id: 'l45',
    texto: 'quem mais provavelmente levaria mala enorme para viagem de dois dias?',
    energia: 'leve',
    tags: ['viagem', 'humor'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'viagem',
  },
  {
    id: 'l46',
    texto: 'quem mais provavelmente repetiria a mesma piada até funcionar?',
    energia: 'leve',
    tags: ['humor', 'comportamento'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l47',
    texto: 'quem mais provavelmente passaria horas escolhendo o que assistir e não assistiria nada?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },
  {
    id: 'l48',
    texto: 'quem mais provavelmente compraria ingresso para show e não iria?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },
  {
    id: 'l49',
    texto: 'quem mais provavelmente esqueceria onde estacionou?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },
  {
    id: 'l50',
    texto: 'quem mais provavelmente usaria o mesmo meme há mais de dois anos?',
    energia: 'leve',
    tags: ['digital', 'humor'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 5,
    categoria: 'digital_life',
  },

  // ── Mais comportamentos (continuação leve) ────────────────────────────
  {
    id: 'l51',
    texto: 'quem mais provavelmente faria amizade com o motorista do Uber?',
    energia: 'leve',
    tags: ['brasil', 'comportamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l52',
    texto: 'quem mais provavelmente esqueceria metade das coisas numa viagem?',
    energia: 'leve',
    tags: ['viagem', 'unanimidade'],
    potencialUnanimidade: 9,
    caos: 7,
    intensidadeSocial: 5,
    categoria: 'viagem',
  },
  {
    id: 'l53',
    texto: 'quem mais provavelmente dormiria na primeira hora de uma viagem longa?',
    energia: 'leve',
    tags: ['viagem', 'humor'],
    potencialUnanimidade: 8,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'viagem',
  },
  {
    id: 'l54',
    texto: 'quem mais provavelmente nunca terminaria o livro que começou?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 4,
    intensidadeSocial: 3,
    categoria: 'cotidiano',
  },
  {
    id: 'l55',
    texto: 'quem mais provavelmente pediria para tirar foto do grupo toda vez?',
    energia: 'leve',
    tags: ['social_media', 'humor'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'digital_life',
  },
  {
    id: 'l56',
    texto: 'quem mais provavelmente colocaria notificação em silêncio e nunca voltaria a ativar?',
    energia: 'leve',
    tags: ['digital', 'comportamento'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'digital_life',
  },
  {
    id: 'l57',
    texto: 'quem mais provavelmente nunca sairia sem colocar protetor solar?',
    energia: 'leve',
    tags: ['brasil', 'humor'],
    potencialUnanimidade: 7,
    caos: 4,
    intensidadeSocial: 3,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l58',
    texto: 'quem mais provavelmente chegaria antes de todo mundo no ponto combinado?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 8,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },
  {
    id: 'l59',
    texto: 'quem mais provavelmente manda meme de bom dia no grupo da família?',
    energia: 'leve',
    tags: ['familia', 'brasil', 'humor'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l60',
    texto: 'quem mais provavelmente viraria para o garçom e pediria "sem cebola" em tudo?',
    energia: 'leve',
    tags: ['comida', 'humor', 'unanimidade'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l61',
    texto: 'quem mais provavelmente apareceria na foto antes de estar pronto?',
    energia: 'leve',
    tags: ['humor', 'digital'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l62',
    texto: 'quem mais provavelmente precisaria de mais de uma hora pra escolher roupa num dia comum?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },
  {
    id: 'l63',
    texto: 'quem mais provavelmente colocaria a música no volume máximo antes de consultar o grupo?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l64',
    texto: 'quem mais provavelmente reclamaria do restaurante mas não diria nada para o garçom?',
    energia: 'leve',
    tags: ['brasil', 'caos_social', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l65',
    texto: 'quem mais provavelmente seguiria dieta na segunda e abandonaria na terça?',
    energia: 'leve',
    tags: ['brasil', 'humor', 'unanimidade'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l66',
    texto: 'quem mais provavelmente prometeria mudar de hábito na virada do ano e mudaria nada?',
    energia: 'leve',
    tags: ['comportamento', 'humor'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l67',
    texto: 'quem mais provavelmente compraria curso online e nunca terminaria?',
    energia: 'leve',
    tags: ['trabalho', 'brasil', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'vida_adulta',
  },
  {
    id: 'l68',
    texto: 'quem mais provavelmente roubar o descanso de braço inteiro no avião?',
    energia: 'leve',
    tags: ['viagem', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'viagem',
  },
  {
    id: 'l69',
    texto: 'quem mais provavelmente teria uma história inacreditável de última hora?',
    energia: 'leve',
    tags: ['humor', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'cotidiano',
  },
  {
    id: 'l70',
    texto: 'quem mais provavelmente perderia os óculos de sol dentro da própria mochila?',
    energia: 'leve',
    tags: ['humor', 'viagem'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'cotidiano',
  },
  {
    id: 'l71',
    texto: 'quem mais provavelmente usaria o cupom errado e ficaria argumentando no caixa?',
    energia: 'leve',
    tags: ['brasil', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l72',
    texto: 'quem mais provavelmente faria planilha de férias com três meses de antecedência?',
    energia: 'leve',
    tags: ['viagem', 'trabalho', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'vida_adulta',
  },
  {
    id: 'l73',
    texto: 'quem mais provavelmente entraria em grupo de WhatsApp e sairia cinco minutos depois?',
    energia: 'leve',
    tags: ['brasil', 'digital', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l74',
    texto: 'quem mais provavelmente ficaria contando ponto de fidelidade por anos sem usar?',
    energia: 'leve',
    tags: ['brasil', 'humor'],
    potencialUnanimidade: 6,
    caos: 4,
    intensidadeSocial: 3,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l75',
    texto: 'quem mais provavelmente compraria roupa de academia e usaria três vezes?',
    energia: 'leve',
    tags: ['brasil', 'humor', 'unanimidade'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l76',
    texto: 'quem mais provavelmente esqueceria a carteira mas teria o PIX?',
    energia: 'leve',
    tags: ['brasil', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l77',
    texto: 'quem mais provavelmente criaria grupo de WhatsApp para assunto que não precisa de grupo?',
    energia: 'leve',
    tags: ['brasil', 'digital', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l78',
    texto: 'quem mais provavelmente tropeçaria do nada no meio da rua?',
    energia: 'leve',
    tags: ['humor'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'l79',
    texto: 'quem mais provavelmente gritaria sozinho no trânsito?',
    energia: 'leve',
    tags: ['brasil', 'humor'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 5,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'l80',
    texto: 'quem mais provavelmente faria a mesma pergunta três vezes na mesma reunião?',
    energia: 'leve',
    tags: ['trabalho', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'vida_adulta',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // MÉDIO — exposição social, leitura de caráter, caos controlado
  // ══════════════════════════════════════════════════════════════════════════

  // ── Comportamento social revelador ────────────────────────────────────
  {
    id: 'm01',
    texto: 'quem mais provavelmente responderia "kkkk" quando claramente ficou chateado?',
    energia: 'medio',
    tags: ['caos_social', 'relacionamento', 'brasil'],
    potencialUnanimidade: 9,
    caos: 9,
    intensidadeSocial: 8,
    categoria: 'caos_social',
  },
  {
    id: 'm02',
    texto: 'quem mais provavelmente sumiria por dias e voltaria como se nada tivesse acontecido?',
    energia: 'medio',
    tags: ['relacionamento', 'caos_social'],
    potencialUnanimidade: 8,
    caos: 8,
    intensidadeSocial: 8,
    categoria: 'relacionamentos',
  },
  {
    id: 'm03',
    texto: 'quem mais provavelmente diria "tanto faz" e ficaria magoado com a decisão?',
    energia: 'medio',
    tags: ['caos_social', 'relacionamento'],
    potencialUnanimidade: 8,
    caos: 9,
    intensidadeSocial: 8,
    categoria: 'caos_social',
  },
  {
    id: 'm04',
    texto: 'quem mais provavelmente combinaria algo e cancelaria na última hora com desculpa convincente?',
    energia: 'medio',
    tags: ['caos_social', 'comportamento'],
    potencialUnanimidade: 8,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'caos_social',
  },
  {
    id: 'm05',
    texto: 'quem mais provavelmente diria "estou bem" quando claramente não está?',
    energia: 'medio',
    tags: ['psicologia', 'vulnerabilidade'],
    vulnerabilidade: 6,
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },
  {
    id: 'm06',
    texto: 'quem mais provavelmente mentiria para não comparecer a um compromisso?',
    energia: 'medio',
    tags: ['caos_social', 'comportamento'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'cotidiano',
  },
  {
    id: 'm07',
    texto: 'quem mais provavelmente nunca admite que errou primeiro?',
    energia: 'medio',
    tags: ['caos_social', 'psicologia'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },
  {
    id: 'm08',
    texto: 'quem mais provavelmente guardaria rancor em silêncio por meses?',
    energia: 'medio',
    tags: ['relacionamento', 'psicologia'],
    vulnerabilidade: 6,
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },
  {
    id: 'm09',
    texto: 'quem mais provavelmente tomaria uma decisão enorme por impulso?',
    energia: 'medio',
    tags: ['comportamento', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'caos_social',
  },
  {
    id: 'm10',
    texto: 'quem mais provavelmente mudaria o plano inteiro na última hora?',
    energia: 'medio',
    tags: ['caos_social', 'comportamento'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 6,
    categoria: 'caos_social',
  },
  {
    id: 'm11',
    texto: 'quem mais provavelmente fingiria não ter visto a mensagem?',
    energia: 'medio',
    tags: ['digital', 'caos_social', 'relacionamento'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'digital_life',
  },
  {
    id: 'm12',
    texto: 'quem mais provavelmente seria o primeiro a ir embora de uma festa?',
    energia: 'medio',
    tags: ['festa', 'comportamento'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'festa',
  },
  {
    id: 'm13',
    texto: 'quem mais provavelmente seria o último a ir embora de uma festa?',
    energia: 'medio',
    tags: ['festa', 'comportamento'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'festa',
  },
  {
    id: 'm14',
    texto: 'quem mais provavelmente entraria em silêncio total depois de brigar?',
    energia: 'medio',
    tags: ['relacionamento', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'relacionamentos',
  },
  {
    id: 'm15',
    texto: 'quem mais provavelmente nunca retornaria uma ligação?',
    energia: 'medio',
    tags: ['comportamento', 'caos_social'],
    potencialUnanimidade: 8,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'm16',
    texto: 'quem mais provavelmente faria amizade nova e ignoraria todo mundo do grupo por semanas?',
    energia: 'medio',
    tags: ['relacionamento', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'relacionamentos',
  },
  {
    id: 'm17',
    texto: 'quem mais provavelmente tentaria resolver tudo sozinho antes de pedir ajuda?',
    energia: 'medio',
    tags: ['psicologia', 'comportamento'],
    vulnerabilidade: 5,
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 6,
    categoria: 'psicologia_social',
  },
  {
    id: 'm18',
    texto: 'quem mais provavelmente passaria a noite inteira conversando com um desconhecido?',
    energia: 'medio',
    tags: ['dating', 'comportamento'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 6,
    categoria: 'cotidiano',
  },
  {
    id: 'm19',
    texto: 'quem mais provavelmente choraria num filme de ação?',
    energia: 'medio',
    tags: ['humor', 'caos_social'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'cotidiano',
  },
  {
    id: 'm20',
    texto: 'quem mais provavelmente guardaria um segredo de todo mundo por anos?',
    energia: 'medio',
    tags: ['relacionamento', 'psicologia'],
    vulnerabilidade: 6,
    potencialUnanimidade: 6,
    caos: 6,
    intensidadeSocial: 6,
    categoria: 'psicologia_social',
  },

  // ── Comportamento digital revelador ───────────────────────────────────
  {
    id: 'm21',
    texto: 'quem mais provavelmente mandaria indireta no story e negaria para todo mundo?',
    energia: 'medio',
    tags: ['digital', 'caos_social', 'brasil', 'social_media'],
    potencialUnanimidade: 8,
    caos: 9,
    intensidadeSocial: 8,
    categoria: 'digital_life',
  },
  {
    id: 'm22',
    texto: 'quem mais provavelmente escreveria uma mensagem longa e apagaria tudo antes de enviar?',
    energia: 'medio',
    tags: ['digital', 'cinematografico', 'relacionamento'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 7,
    categoria: 'cinematografico',
  },
  {
    id: 'm23',
    texto: 'quem mais provavelmente publicaria uma foto do outro sem pedir permissão?',
    energia: 'medio',
    tags: ['digital', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'digital_life',
  },
  {
    id: 'm24',
    texto: 'quem mais provavelmente apagaria a foto porque não teve curtidas suficientes?',
    energia: 'medio',
    tags: ['digital', 'caos_social', 'social_media'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'digital_life',
  },
  {
    id: 'm25',
    texto: 'quem mais provavelmente bloquearia e desbloquearia alguém dependendo do humor?',
    energia: 'medio',
    tags: ['digital', 'relacionamento', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'relacionamentos',
  },
  {
    id: 'm26',
    texto: 'quem mais provavelmente mutaria o perfil do ex mas continuaria verificando?',
    energia: 'medio',
    tags: ['dating', 'digital', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'relacionamentos',
  },
  {
    id: 'm27',
    texto: 'quem mais provavelmente ficaria online mas não responderia?',
    energia: 'medio',
    tags: ['digital', 'caos_social'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'digital_life',
  },
  {
    id: 'm28',
    texto: 'quem mais provavelmente postaria algo de madrugada e deletaria de manhã?',
    energia: 'medio',
    tags: ['digital', 'caos_social', 'social_media'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'cinematografico',
  },
  {
    id: 'm29',
    texto: 'quem mais provavelmente terminaría um relacionamento por mensagem?',
    energia: 'medio',
    tags: ['dating', 'caos_social', 'relacionamento'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'relacionamentos',
  },
  {
    id: 'm30',
    texto: 'quem mais provavelmente teria o LinkedIn com "aberto para oportunidades" há mais de um ano?',
    energia: 'medio',
    tags: ['trabalho', 'brasil', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 6,
    categoria: 'vida_adulta',
  },

  // ── Relacionamentos e dating ───────────────────────────────────────────
  {
    id: 'm31',
    texto: 'quem mais provavelmente faria um soft launch antes de assumir alguém?',
    energia: 'medio',
    tags: ['dating', 'brasil', 'genz', 'social_media'],
    potencialUnanimidade: 8,
    caos: 8,
    intensidadeSocial: 8,
    categoria: 'dating',
  },
  {
    id: 'm32',
    texto: 'quem mais provavelmente voltaria com o ex que todo mundo disse para não voltar?',
    energia: 'medio',
    tags: ['dating', 'caos_social', 'relacionamento'],
    potencialUnanimidade: 7,
    caos: 9,
    intensidadeSocial: 8,
    categoria: 'relacionamentos',
  },
  {
    id: 'm33',
    texto: 'quem mais provavelmente mandaria mensagem pro ex às duas da manhã?',
    energia: 'medio',
    tags: ['dating', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 9,
    intensidadeSocial: 8,
    categoria: 'relacionamentos',
  },
  {
    id: 'm34',
    texto: 'quem mais provavelmente nunca tomaria a iniciativa mas reclamaria quando nada acontece?',
    energia: 'medio',
    tags: ['relacionamento', 'caos_social', 'psicologia'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },
  {
    id: 'm35',
    texto: 'quem mais provavelmente apagaria o histórico de conversa antes de mostrar o celular?',
    energia: 'medio',
    tags: ['dating', 'caos_social', 'digital'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'caos_social',
  },
  {
    id: 'm36',
    texto: 'quem mais provavelmente nunca dissesse o que quer mas esperasse que adivinhassem?',
    energia: 'medio',
    tags: ['relacionamento', 'caos_social', 'psicologia'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },
  {
    id: 'm37',
    texto: 'quem mais provavelmente faria ciúme sem parecer que está fazendo ciúme?',
    energia: 'medio',
    tags: ['relacionamento', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'relacionamentos',
  },
  {
    id: 'm38',
    texto: 'quem mais provavelmente fingisse estar superado quando claramente não está?',
    energia: 'medio',
    tags: ['dating', 'psicologia', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'relacionamentos',
  },
  {
    id: 'm39',
    texto: 'quem mais provavelmente começaria a seguir a nova pessoa do ex imediatamente?',
    energia: 'medio',
    tags: ['dating', 'digital', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'dating',
  },
  {
    id: 'm40',
    texto: 'quem mais provavelmente nunca dissesse "eu te amo" primeiro?',
    energia: 'medio',
    tags: ['relacionamento', 'vulnerabilidade'],
    vulnerabilidade: 7,
    potencialUnanimidade: 6,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'relacionamentos',
  },

  // ── Dating contemporâneo ──────────────────────────────────────────────
  {
    id: 'm41',
    texto: 'quem mais provavelmente olharia pela janela do Uber pensando na própria vida depois de um date?',
    energia: 'medio',
    tags: ['dating', 'cinematografico', 'brasil'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 8,
    categoria: 'cinematografico',
  },
  {
    id: 'm42',
    texto: 'quem mais provavelmente mandaria análise completa do date para o grupo às 2h da manhã?',
    energia: 'medio',
    tags: ['dating', 'caos_social', 'humor'],
    potencialUnanimidade: 8,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'dating',
  },
  {
    id: 'm43',
    texto: 'quem mais provavelmente cancelaria um date no mesmo dia com desculpa razoável?',
    energia: 'medio',
    tags: ['dating', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'dating',
  },
  {
    id: 'm44',
    texto: 'quem mais provavelmente faria stalk completo antes do primeiro encontro?',
    energia: 'medio',
    tags: ['dating', 'digital', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'dating',
  },
  {
    id: 'm45',
    texto: 'quem mais provavelmente fingisse que nunca usou app de relacionamento?',
    energia: 'medio',
    tags: ['dating', 'caos_social', 'brasil'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'dating',
  },
  {
    id: 'm46',
    texto: 'quem mais provavelmente mandaria áudio passivo-agressivo e depois diria que foi mal-interpretado?',
    energia: 'medio',
    tags: ['caos_social', 'brasil', 'relacionamento'],
    potencialUnanimidade: 8,
    caos: 9,
    intensidadeSocial: 8,
    categoria: 'caos_social',
  },
  {
    id: 'm47',
    texto: 'quem mais provavelmente precisaria de horas para decidir o que vestir para um encontro de trinta minutos?',
    energia: 'medio',
    tags: ['dating', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 5,
    categoria: 'dating',
  },
  {
    id: 'm48',
    texto: 'quem mais provavelmente conferia o horóscopo antes de decidir se a pessoa vale a pena?',
    energia: 'medio',
    tags: ['dating', 'humor', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'dating',
  },
  {
    id: 'm49',
    texto: 'quem mais provavelmente teria um "tipo" e sempre ficaria com alguém completamente oposto?',
    energia: 'medio',
    tags: ['dating', 'psicologia', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'dating',
  },
  {
    id: 'm50',
    texto: 'quem mais provavelmente apareceria no local onde sabia que o ex estaria "por coincidência"?',
    energia: 'medio',
    tags: ['dating', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 9,
    intensidadeSocial: 8,
    categoria: 'caos_social',
  },

  // ── Vida adulta e trabalho ─────────────────────────────────────────────
  {
    id: 'm51',
    texto: 'quem mais provavelmente estaria reclamando do emprego mas mandando zero currículos?',
    energia: 'medio',
    tags: ['trabalho', 'brasil', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 6,
    categoria: 'vida_adulta',
  },
  {
    id: 'm52',
    texto: 'quem mais provavelmente faria lista de tarefas elaborada e não faria nada da lista?',
    energia: 'medio',
    tags: ['trabalho', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 5,
    categoria: 'vida_adulta',
  },
  {
    id: 'm53',
    texto: 'quem mais provavelmente teria a reunião transformada em e-mail depois de uma hora?',
    energia: 'medio',
    tags: ['trabalho', 'humor', 'brasil'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 5,
    categoria: 'vida_adulta',
  },
  {
    id: 'm54',
    texto: 'quem mais provavelmente estaria saindo do emprego toda semana na cabeça mas lá há três anos?',
    energia: 'medio',
    tags: ['trabalho', 'brasil', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 6,
    categoria: 'vida_adulta',
  },
  {
    id: 'm55',
    texto: 'quem mais provavelmente falaria de fazer freela por meses sem começar?',
    energia: 'medio',
    tags: ['trabalho', 'brasil', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 5,
    categoria: 'vida_adulta',
  },
  {
    id: 'm56',
    texto: 'quem mais provavelmente compraria livro de produtividade e não terminaria?',
    energia: 'medio',
    tags: ['trabalho', 'humor'],
    potencialUnanimidade: 7,
    caos: 4,
    intensidadeSocial: 4,
    categoria: 'vida_adulta',
  },
  {
    id: 'm57',
    texto: 'quem mais provavelmente planejaria as férias perfeitas e cancelaria tudo?',
    energia: 'medio',
    tags: ['viagem', 'trabalho', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'vida_adulta',
  },
  {
    id: 'm58',
    texto: 'quem mais provavelmente estaria "fazendo terapia" há seis meses sem contar pra família?',
    energia: 'medio',
    tags: ['brasil', 'psicologia', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'vida_adulta',
  },
  {
    id: 'm59',
    texto: 'quem mais provavelmente só pediria ajuda quando o problema já virou uma crise?',
    energia: 'medio',
    tags: ['psicologia', 'comportamento'],
    vulnerabilidade: 6,
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 6,
    categoria: 'psicologia_social',
  },
  {
    id: 'm60',
    texto: 'quem mais provavelmente daria o melhor conselho para os outros e não seguiria nenhum?',
    energia: 'medio',
    tags: ['psicologia', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },

  // ── Psicologia social leve ────────────────────────────────────────────
  {
    id: 'm61',
    texto: 'quem mais provavelmente perceberia tudo sobre as pessoas mas nunca falaria?',
    energia: 'medio',
    tags: ['psicologia', 'vulnerabilidade'],
    vulnerabilidade: 6,
    potencialUnanimidade: 6,
    caos: 6,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },
  {
    id: 'm62',
    texto: 'quem mais provavelmente resolveria um conflito inteiro na própria cabeça sem avisar a outra pessoa?',
    energia: 'medio',
    tags: ['psicologia', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },
  {
    id: 'm63',
    texto: 'quem mais provavelmente concordaria na hora e discordaria depois de ir embora?',
    energia: 'medio',
    tags: ['psicologia', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'psicologia_social',
  },
  {
    id: 'm64',
    texto: 'quem mais provavelmente precisaria de dias para responder algo delicado?',
    energia: 'medio',
    tags: ['comportamento', 'relacionamento'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'm65',
    texto: 'quem mais provavelmente estaria superado mas checaria o perfil do ex toda semana?',
    energia: 'medio',
    tags: ['dating', 'caos_social', 'digital'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'relacionamentos',
  },
  {
    id: 'm66',
    texto: 'quem mais provavelmente se tornaria o pai ou mãe do grupo sem ninguém pedir?',
    energia: 'medio',
    tags: ['psicologia', 'comportamento'],
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'psicologia_social',
  },
  {
    id: 'm67',
    texto: 'quem mais provavelmente ouviria música triste fingindo que está tudo bem?',
    energia: 'medio',
    tags: ['cinematografico', 'vulnerabilidade', 'psicologia'],
    vulnerabilidade: 6,
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 8,
    categoria: 'cinematografico',
  },
  {
    id: 'm68',
    texto: 'quem mais provavelmente faria uma cena dramática em particular mas pareceria calmo em público?',
    energia: 'medio',
    tags: ['psicologia', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },
  {
    id: 'm69',
    texto: 'quem mais provavelmente leria a mensagem, fecharia o app, e responderia dois dias depois como se nada fosse?',
    energia: 'medio',
    tags: ['digital', 'caos_social', 'relacionamento'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'digital_life',
  },
  {
    id: 'm70',
    texto: 'quem mais provavelmente chamaria a atenção de um estranho na rua?',
    energia: 'medio',
    tags: ['comportamento', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'caos_social',
  },

  // ── Mais médio — culturais e sociais ──────────────────────────────────
  {
    id: 'm71',
    texto: 'quem mais provavelmente defenderia o time mesmo perdendo todo campeonato?',
    energia: 'medio',
    tags: ['brasil', 'caos_social', 'humor'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'm72',
    texto: 'quem mais provavelmente teria história inacreditável que ninguém do grupo sabe?',
    energia: 'medio',
    tags: ['caos_social', 'comportamento'],
    potencialUnanimidade: 6,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'caos_social',
  },
  {
    id: 'm73',
    texto: 'quem mais provavelmente conheceria o nome do segurança do lugar onde vai com frequência?',
    energia: 'medio',
    tags: ['comportamento', 'brasil'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'm74',
    texto: 'quem mais provavelmente apareceria onde sabia que o ex estaria "sem querer"?',
    energia: 'medio',
    tags: ['dating', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 9,
    intensidadeSocial: 8,
    categoria: 'caos_social',
  },
  {
    id: 'm75',
    texto: 'quem mais provavelmente criaria drama invisível e nunca explicaria o motivo?',
    energia: 'medio',
    tags: ['caos_social', 'relacionamento'],
    potencialUnanimidade: 7,
    caos: 9,
    intensidadeSocial: 7,
    categoria: 'caos_social',
  },
  {
    id: 'm76',
    texto: 'quem mais provavelmente nunca retornaria uma ligação mas estaria online no Instagram?',
    energia: 'medio',
    tags: ['digital', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'digital_life',
  },
  {
    id: 'm77',
    texto: 'quem mais provavelmente chegasse com um plano B antes de o plano A começar?',
    energia: 'medio',
    tags: ['comportamento', 'psicologia'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'm78',
    texto: 'quem mais provavelmente precisaria de aprovação do grupo antes de qualquer decisão pequena?',
    energia: 'medio',
    tags: ['psicologia', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 6,
    categoria: 'psicologia_social',
  },
  {
    id: 'm79',
    texto: 'quem mais provavelmente organizaria festa para metade do grupo e avisaria a outra metade de última hora?',
    energia: 'medio',
    tags: ['festa', 'caos_social'],
    potencialUnanimidade: 6,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'caos_social',
  },
  {
    id: 'm80',
    texto: 'quem mais provavelmente teria uma opinião forte sobre tudo mas hesitaria quando precisasse defender em público?',
    energia: 'medio',
    tags: ['psicologia', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'psicologia_social',
  },

  // ── Cinematográfico e revelação social ────────────────────────────────
  {
    id: 'm81',
    texto: 'quem mais provavelmente mandaria boa noite e ficaria acordado até as 3h?',
    energia: 'medio',
    tags: ['cinematografico', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 6,
    categoria: 'cinematografico',
  },
  {
    id: 'm82',
    texto: 'quem mais provavelmente compraria passagem por impulso e cancelaria depois?',
    energia: 'medio',
    tags: ['caos_social', 'viagem'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'caos_social',
  },
  {
    id: 'm83',
    texto: 'quem mais provavelmente ficaria em silêncio durante uma briga mas mandaria mensagem no dia seguinte explicando tudo?',
    energia: 'medio',
    tags: ['relacionamento', 'caos_social', 'cinematografico'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'cinematografico',
  },
  {
    id: 'm84',
    texto: 'quem mais provavelmente teria uma playlist de "estou bem" que claramente é de quem não está bem?',
    energia: 'medio',
    tags: ['cinematografico', 'vulnerabilidade'],
    vulnerabilidade: 6,
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 8,
    categoria: 'cinematografico',
  },
  {
    id: 'm85',
    texto: 'quem mais provavelmente ficaria olhando para o teto às 2h da manhã com algo na cabeça?',
    energia: 'medio',
    tags: ['cinematografico', 'vulnerabilidade'],
    vulnerabilidade: 6,
    potencialUnanimidade: 6,
    caos: 5,
    intensidadeSocial: 7,
    categoria: 'cinematografico',
  },
  {
    id: 'm86',
    texto: 'quem mais provavelmente passaria horas pensando em algo que os outros esqueceram em cinco minutos?',
    energia: 'medio',
    tags: ['psicologia', 'vulnerabilidade', 'cinematografico'],
    vulnerabilidade: 6,
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },
  {
    id: 'm87',
    texto: 'quem mais provavelmente transformaria tudo em piada quando está desconfortável?',
    energia: 'medio',
    tags: ['psicologia', 'caos_social', 'vulnerabilidade'],
    vulnerabilidade: 6,
    potencialUnanimidade: 8,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },
  {
    id: 'm88',
    texto: 'quem mais provavelmente trataria melhor estranhos do que as pessoas que mais ama?',
    energia: 'medio',
    tags: ['psicologia', 'relacionamento'],
    vulnerabilidade: 7,
    potencialUnanimidade: 6,
    caos: 6,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },
  {
    id: 'm89',
    texto: 'quem mais provavelmente faria uma grande mudança e só avisaria depois de feita?',
    energia: 'medio',
    tags: ['comportamento', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'caos_social',
  },
  {
    id: 'm90',
    texto: 'quem mais provavelmente queria ser convencido a fazer algo que já havia decidido fazer?',
    energia: 'medio',
    tags: ['psicologia', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 6,
    categoria: 'psicologia_social',
  },

  // ── Mais médio ─────────────────────────────────────────────────────────
  {
    id: 'm91',
    texto: 'quem mais provavelmente teria uma razão bem específica para não gostar de uma pessoa mas nunca falaria?',
    energia: 'medio',
    tags: ['caos_social', 'psicologia'],
    potencialUnanimidade: 6,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },
  {
    id: 'm92',
    texto: 'quem mais provavelmente chegaria na casa de alguém, pegaria o Wi-Fi, e ficaria no celular a tarde toda?',
    energia: 'medio',
    tags: ['digital', 'caos_social', 'humor'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'digital_life',
  },
  {
    id: 'm93',
    texto: 'quem mais provavelmente choraria escutando música no fone sem contar pra ninguém?',
    energia: 'medio',
    tags: ['cinematografico', 'vulnerabilidade'],
    vulnerabilidade: 6,
    potencialUnanimidade: 6,
    caos: 5,
    intensidadeSocial: 7,
    categoria: 'cinematografico',
  },
  {
    id: 'm94',
    texto: 'quem mais provavelmente mudaria de opinião completamente depois de dormir?',
    energia: 'medio',
    tags: ['comportamento', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'm95',
    texto: 'quem mais provavelmente ficaria inventando desculpa para evitar exercício físico?',
    energia: 'medio',
    tags: ['brasil', 'humor'],
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 4,
    categoria: 'brasil_contemporaneo',
  },
  {
    id: 'm96',
    texto: 'quem mais provavelmente chegaria ao after com disposição que não tinha na festa?',
    energia: 'medio',
    tags: ['festa', 'brasil', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'festa',
  },
  {
    id: 'm97',
    texto: 'quem mais provavelmente enviaria áudio no horário errado para o chat errado?',
    energia: 'medio',
    tags: ['caos_social', 'digital'],
    potencialUnanimidade: 7,
    caos: 8,
    intensidadeSocial: 7,
    categoria: 'caos_social',
  },
  {
    id: 'm98',
    texto: 'quem mais provavelmente precisaria de validação mas recusaria quando ela chegasse?',
    energia: 'medio',
    tags: ['psicologia', 'vulnerabilidade'],
    vulnerabilidade: 6,
    potencialUnanimidade: 6,
    caos: 5,
    intensidadeSocial: 6,
    categoria: 'psicologia_social',
  },
  {
    id: 'm99',
    texto: 'quem mais provavelmente repetiria a história de quando era mais novo todo rolê?',
    energia: 'medio',
    tags: ['caos_social', 'humor', 'role'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 5,
    categoria: 'cotidiano',
  },
  {
    id: 'm100',
    texto: 'quem mais provavelmente faria algo impressionante e ficaria esperando alguém perceber?',
    energia: 'medio',
    tags: ['psicologia', 'caos_social'],
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 6,
    categoria: 'psicologia_social',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // INTENSO — vulnerabilidade real, silêncio antes da risada
  // ══════════════════════════════════════════════════════════════════════════

  // ── Exposição emocional ────────────────────────────────────────────────
  {
    id: 'i01',
    texto: 'quem mais provavelmente parece mais bem do que realmente está?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'psicologia', 'cinematografico'],
    vulnerabilidade: 8,
    potencialUnanimidade: 7,
    caos: 6,
    intensidadeSocial: 9,
    categoria: 'psicologia_social',
  },
  {
    id: 'i02',
    texto: 'quem mais provavelmente aceita menos do que merece para não ficar sozinho?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'relacionamento', 'psicologia'],
    vulnerabilidade: 9,
    potencialUnanimidade: 6,
    caos: 6,
    intensidadeSocial: 9,
    categoria: 'psicologia_social',
  },
  {
    id: 'i03',
    texto: 'quem mais provavelmente cuida de todo mundo mas nunca pede cuidado de ninguém?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'psicologia', 'relacionamento'],
    vulnerabilidade: 8,
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 9,
    categoria: 'psicologia_social',
  },
  {
    id: 'i04',
    texto: 'quem mais provavelmente está mais perdido do que aparenta?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'psicologia', 'cinematografico'],
    vulnerabilidade: 8,
    potencialUnanimidade: 6,
    caos: 5,
    intensidadeSocial: 9,
    categoria: 'cinematografico',
  },
  {
    id: 'i05',
    texto: 'quem mais provavelmente sente muito mais do que demonstra?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'psicologia'],
    vulnerabilidade: 8,
    potencialUnanimidade: 6,
    caos: 5,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i06',
    texto: 'quem mais provavelmente precisaria de uma conversa que não sabe como começar?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'relacionamento', 'cinematografico'],
    vulnerabilidade: 8,
    potencialUnanimidade: 6,
    caos: 5,
    intensidadeSocial: 9,
    categoria: 'cinematografico',
  },
  {
    id: 'i07',
    texto: 'quem mais provavelmente nunca pede ajuda mesmo quando está precisando muito?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'psicologia'],
    vulnerabilidade: 8,
    potencialUnanimidade: 7,
    caos: 5,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i08',
    texto: 'quem mais provavelmente se apaixona pela pessoa mais complicada possível?',
    energia: 'intenso',
    tags: ['relacionamento', 'psicologia', 'caos_social'],
    vulnerabilidade: 7,
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 8,
    categoria: 'relacionamentos',
  },
  {
    id: 'i09',
    texto: 'quem mais provavelmente sabota algo bom antes que dê certo?',
    energia: 'intenso',
    tags: ['psicologia', 'vulnerabilidade'],
    vulnerabilidade: 8,
    potencialUnanimidade: 6,
    caos: 6,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i10',
    texto: 'quem mais provavelmente tem mais medo de ser feliz do que de falhar?',
    energia: 'intenso',
    tags: ['psicologia', 'vulnerabilidade', 'cinematografico'],
    vulnerabilidade: 9,
    potencialUnanimidade: 5,
    caos: 5,
    intensidadeSocial: 9,
    categoria: 'cinematografico',
  },
  {
    id: 'i11',
    texto: 'quem mais provavelmente nunca esquece uma mágoa mesmo depois de dizer que esqueceu?',
    energia: 'intenso',
    tags: ['relacionamento', 'psicologia'],
    vulnerabilidade: 7,
    potencialUnanimidade: 7,
    caos: 7,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i12',
    texto: 'quem mais provavelmente está se sentindo mais sozinho do que aparenta?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'cinematografico'],
    vulnerabilidade: 9,
    potencialUnanimidade: 5,
    caos: 4,
    intensidadeSocial: 9,
    categoria: 'cinematografico',
  },
  {
    id: 'i13',
    texto: 'quem mais provavelmente vai mudar completamente de vida nos próximos dois anos?',
    energia: 'intenso',
    tags: ['psicologia', 'cinematografico'],
    vulnerabilidade: 6,
    potencialUnanimidade: 6,
    caos: 6,
    intensidadeSocial: 8,
    categoria: 'cinematografico',
  },
  {
    id: 'i14',
    texto: 'quem mais provavelmente faria uma grande mudança de vida sem contar para ninguém?',
    energia: 'intenso',
    tags: ['psicologia', 'caos_social'],
    vulnerabilidade: 6,
    potencialUnanimidade: 6,
    caos: 7,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i15',
    texto: 'quem mais provavelmente está pensando em algo completamente diferente agora?',
    energia: 'intenso',
    tags: ['psicologia', 'caos_social'],
    vulnerabilidade: 5,
    potencialUnanimidade: 5,
    caos: 7,
    intensidadeSocial: 7,
    categoria: 'psicologia_social',
  },

  // ── Vulnerabilidade psicológica profunda ──────────────────────────────
  {
    id: 'i16',
    texto: 'quem mais provavelmente nunca conseguiu dizer o que precisava dizer na hora certa?',
    energia: 'intenso',
    tags: ['relacionamento', 'vulnerabilidade', 'cinematografico'],
    vulnerabilidade: 8,
    potencialUnanimidade: 5,
    caos: 5,
    intensidadeSocial: 9,
    categoria: 'cinematografico',
  },
  {
    id: 'i17',
    texto: 'quem mais provavelmente carregaria um "e se" que nunca vai saber a resposta?',
    energia: 'intenso',
    tags: ['relacionamento', 'vulnerabilidade', 'cinematografico'],
    vulnerabilidade: 8,
    potencialUnanimidade: 5,
    caos: 4,
    intensidadeSocial: 9,
    categoria: 'cinematografico',
  },
  {
    id: 'i18',
    texto: 'quem mais provavelmente colocaria todo mundo antes de si mesmo e chamaria isso de generosidade?',
    energia: 'intenso',
    tags: ['psicologia', 'vulnerabilidade'],
    vulnerabilidade: 8,
    potencialUnanimidade: 6,
    caos: 5,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i19',
    texto: 'quem mais provavelmente tem um medo que nunca admitiu em voz alta?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'psicologia'],
    vulnerabilidade: 8,
    potencialUnanimidade: 5,
    caos: 5,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i20',
    texto: 'quem mais provavelmente pega mais pesado em si mesmo do que em qualquer outra pessoa?',
    energia: 'intenso',
    tags: ['psicologia', 'vulnerabilidade'],
    vulnerabilidade: 8,
    potencialUnanimidade: 6,
    caos: 5,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i21',
    texto: 'quem mais provavelmente carregaria culpa de algo que não foi culpa sua?',
    energia: 'intenso',
    tags: ['psicologia', 'vulnerabilidade'],
    vulnerabilidade: 8,
    potencialUnanimidade: 5,
    caos: 4,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i22',
    texto: 'quem mais provavelmente teria raiva de si mesmo mas projetaria em outra coisa?',
    energia: 'intenso',
    tags: ['psicologia', 'vulnerabilidade'],
    vulnerabilidade: 8,
    potencialUnanimidade: 6,
    caos: 6,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i23',
    texto: 'quem mais provavelmente revelaria um segredo do grupo sem querer?',
    energia: 'intenso',
    tags: ['caos_social', 'relacionamento'],
    potencialUnanimidade: 6,
    caos: 9,
    intensidadeSocial: 8,
    categoria: 'caos_social',
  },
  {
    id: 'i24',
    texto: 'quem mais provavelmente tem uma versão da própria história que prefere acreditar?',
    energia: 'intenso',
    tags: ['psicologia', 'vulnerabilidade'],
    vulnerabilidade: 7,
    potencialUnanimidade: 5,
    caos: 5,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i25',
    texto: 'quem mais provavelmente nunca se sente suficiente mesmo quando deveria?',
    energia: 'intenso',
    tags: ['psicologia', 'vulnerabilidade'],
    vulnerabilidade: 9,
    potencialUnanimidade: 5,
    caos: 4,
    intensidadeSocial: 9,
    categoria: 'psicologia_social',
  },

  // ── Relacionamentos e amor ─────────────────────────────────────────────
  {
    id: 'i26',
    texto: 'quem mais provavelmente ainda pensa em alguém que fingiu ter esquecido?',
    energia: 'intenso',
    tags: ['relacionamento', 'vulnerabilidade', 'cinematografico'],
    vulnerabilidade: 8,
    potencialUnanimidade: 6,
    caos: 6,
    intensidadeSocial: 9,
    categoria: 'relacionamentos',
  },
  {
    id: 'i27',
    texto: 'quem mais provavelmente terminou algo que ainda não terminou de dentro?',
    energia: 'intenso',
    tags: ['relacionamento', 'vulnerabilidade'],
    vulnerabilidade: 8,
    potencialUnanimidade: 6,
    caos: 5,
    intensidadeSocial: 9,
    categoria: 'relacionamentos',
  },
  {
    id: 'i28',
    texto: 'quem mais provavelmente nunca disse que amava de verdade para a pessoa que mais amou?',
    energia: 'intenso',
    tags: ['relacionamento', 'vulnerabilidade', 'cinematografico'],
    vulnerabilidade: 9,
    potencialUnanimidade: 5,
    caos: 5,
    intensidadeSocial: 10,
    categoria: 'cinematografico',
  },
  {
    id: 'i29',
    texto: 'quem mais provavelmente escolheu a estabilidade quando queria outra coisa?',
    energia: 'intenso',
    tags: ['relacionamento', 'vulnerabilidade', 'vida_adulta'],
    vulnerabilidade: 8,
    potencialUnanimidade: 5,
    caos: 5,
    intensidadeSocial: 9,
    categoria: 'relacionamentos',
  },
  {
    id: 'i30',
    texto: 'quem mais provavelmente tem medo de se apaixonar de verdade?',
    energia: 'intenso',
    tags: ['relacionamento', 'vulnerabilidade'],
    vulnerabilidade: 9,
    potencialUnanimidade: 5,
    caos: 5,
    intensidadeSocial: 9,
    categoria: 'relacionamentos',
  },

  // ── Cinematográfico e estado atual ────────────────────────────────────
  {
    id: 'i31',
    texto: 'quem mais provavelmente passaria por algo muito difícil sem contar para ninguém aqui?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'cinematografico'],
    vulnerabilidade: 9,
    potencialUnanimidade: 5,
    caos: 4,
    intensidadeSocial: 9,
    categoria: 'cinematografico',
  },
  {
    id: 'i32',
    texto: 'quem mais provavelmente está bem, mas não tão bem quanto parece?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'cinematografico'],
    vulnerabilidade: 8,
    potencialUnanimidade: 6,
    caos: 5,
    intensidadeSocial: 9,
    categoria: 'cinematografico',
  },
  {
    id: 'i33',
    texto: 'quem mais provavelmente guardaria o melhor conselho para si mesmo e nunca seguiria?',
    energia: 'intenso',
    tags: ['psicologia', 'vulnerabilidade'],
    vulnerabilidade: 7,
    potencialUnanimidade: 6,
    caos: 5,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i34',
    texto: 'quem mais provavelmente está esperando permissão para fazer algo que já sabe que quer?',
    energia: 'intenso',
    tags: ['psicologia', 'vulnerabilidade', 'cinematografico'],
    vulnerabilidade: 7,
    potencialUnanimidade: 5,
    caos: 5,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i35',
    texto: 'quem mais provavelmente vai se lembrar desse grupo por muito tempo?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'cinematografico', 'unanimidade'],
    vulnerabilidade: 7,
    potencialUnanimidade: 5,
    caos: 6,
    intensidadeSocial: 9,
    categoria: 'cinematografico',
  },
  {
    id: 'i36',
    texto: 'quem mais provavelmente precisaria ouvir "vai dar certo" de verdade agora?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'cinematografico'],
    vulnerabilidade: 9,
    potencialUnanimidade: 5,
    caos: 4,
    intensidadeSocial: 9,
    categoria: 'cinematografico',
  },
  {
    id: 'i37',
    texto: 'quem mais provavelmente estaria em paz com a vida mas sentiria falta de algo que não sabe nomear?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'cinematografico'],
    vulnerabilidade: 8,
    potencialUnanimidade: 5,
    caos: 4,
    intensidadeSocial: 9,
    categoria: 'cinematografico',
  },
  {
    id: 'i38',
    texto: 'quem mais provavelmente nunca se permitiria depender de alguém de verdade?',
    energia: 'intenso',
    tags: ['psicologia', 'vulnerabilidade', 'relacionamento'],
    vulnerabilidade: 8,
    potencialUnanimidade: 6,
    caos: 5,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i39',
    texto: 'quem mais provavelmente fez algo pelos outros esperando algo de volta que nunca admitiu?',
    energia: 'intenso',
    tags: ['psicologia', 'relacionamento', 'caos_social'],
    vulnerabilidade: 7,
    potencialUnanimidade: 5,
    caos: 6,
    intensidadeSocial: 8,
    categoria: 'psicologia_social',
  },
  {
    id: 'i40',
    texto: 'quem mais provavelmente já esteve no ponto mais baixo sem contar pra ninguém aqui?',
    energia: 'intenso',
    tags: ['vulnerabilidade', 'cinematografico'],
    vulnerabilidade: 9,
    potencialUnanimidade: 4,
    caos: 4,
    intensidadeSocial: 9,
    categoria: 'cinematografico',
  },

];

export const TOTAL_PROMPTS = PROMPTS.length;
