export type {
  ArquivosCase,
  ArquivosCaseConfig,
  ArquivosCaseId,
  ArquivosCaseIntro,
  ArquivosCaseTone,
  ArquivosCharacter,
  ArquivosCharacterId,
  ArquivosEvidence,
  ArquivosEvidenceId,
  ArquivosEvidenceKind,
  ArquivosFileId,
  ArquivosIncidentType,
  ArquivosPrivateFile,
  ArquivosSecretAction,
  ArquivosSecretActionId,
  ArquivosTimelineEvent,
  ArquivosTruth,
  ArquivosVerdictQuestion,
} from '@/games/arquivos/types';
