// ─── Eu Nunca — Editorial de Cartas ──────────────────────────────────────────
//
// 134 cartas distribuídas em 8 categorias.
// Curadoria editorial: evitar genérico, adolescente, chocante sem graça.
// Cada carta é um gatilho de conversa real — não um questionário.
//
// Intensidades: leve → social → pessoal → caotico
// Fases: aquecimento → subida → pico → release

import type {
  CartaEuNunca,
  CategoriaEuNunca,
  CategoriaEuNuncaId,
  IntensidadeEuNunca,
} from './types';

export const CATEGORIAS_EU_NUNCA: CategoriaEuNunca[] = [
  {
    id: 'vergonha',
    nome: 'Vergonha Alheia',
    descricao: 'momentos em que o chão não abriu',
    emoji: '😬',
    temMais18: false,
  },
  {
    id: 'internet',
    nome: 'Internet',
    descricao: 'comportamento digital que ninguém admite',
    emoji: '📱',
    temMais18: false,
  },
  {
    id: 'relacionamentos',
    nome: 'Relacionamentos',
    descricao: 'ficadas, namoros e histórias que ficaram pelo caminho',
    emoji: '💔',
    temMais18: true,
  },
  {
    id: 'ego',
    nome: 'Ego',
    descricao: 'vaidade, status e a imagem que tentamos preservar',
    emoji: '🪞',
    temMais18: false,
  },
  {
    id: 'vida_adulta',
    nome: 'Vida Adulta',
    descricao: 'responsabilidades que a gente inventa que tem',
    emoji: '📋',
    temMais18: false,
  },
  {
    id: 'segredos',
    nome: 'Segredos',
    descricao: 'coisas que ficaram escondidas por tempo demais',
    emoji: '🤫',
    temMais18: false,
  },
  {
    id: 'hipocrisia',
    nome: 'Hipocrisia',
    descricao: 'quando o discurso e a prática não se encontram',
    emoji: '🎭',
    temMais18: false,
  },
  {
    id: 'exposed',
    nome: 'Exposed',
    descricao: 'quando alguém foi pego em flagrante',
    emoji: '👀',
    temMais18: false,
  },
];

export const CARTAS_EU_NUNCA: CartaEuNunca[] = [
  // ─── VERGONHA (17 cartas) ───────────────────────────────────────────────────
  {
    id: 'v01',
    complemento: 'tropecei em público e fiz que estava testando o chão',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'v02',
    complemento: 'chamei meu professor de mãe ou pai',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'v03',
    complemento: 'dei tchau pra alguém e ela continuou andando do meu lado por mais 3 minutos',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'v04',
    complemento: 'cumprimentei alguém estendendo a mão e fui abraçar ao mesmo tempo — travei e não fiz nenhum dos dois',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'v05',
    complemento: 'dancei pensando que estava sozinho e alguém apareceu no meio',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'v06',
    complemento: 'devolvi "igualmente" quando o garçom disse "bom apetite"',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'v07',
    complemento: 'fui embora de um lugar e voltei pra buscar algo que estava no meu bolso',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'v08',
    complemento: 'pedi a conta num restaurante e ela já estava na mesa há minutos',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'v09',
    complemento: 'ri de algo muito constrangedor em silêncio e tentei fingir que não ouvi',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'v10',
    complemento: 'me apresentei com nome errado porque travei na hora',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'v11',
    complemento: 'fingi receber uma ligação pra sair de uma conversa',
    categoria: 'vergonha',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'v12',
    complemento: 'enviei mensagem pro grupo errado e tive que fingir que foi intencional',
    categoria: 'vergonha',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'v13',
    complemento: 'discordei firmemente de algo que eu mesmo tinha dito 5 minutos antes',
    categoria: 'vergonha',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'v14',
    complemento: 'falei amém numa situação que não era religiosa',
    categoria: 'vergonha',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'v15',
    complemento: 'fui mal compreendido de um jeito que não consegui explicar depois',
    categoria: 'vergonha',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'v16',
    complemento: 'falei mal de alguém e descobri que a pessoa era parente de quem estava ouvindo',
    categoria: 'vergonha',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'v17',
    complemento: 'me perdi de cara dentro de um prédio conhecido e entrei em pânico silencioso',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'release',
  },

  // ─── INTERNET (17 cartas) ───────────────────────────────────────────────────
  {
    id: 'i01',
    complemento: 'mandei um áudio e imediatamente me arrependi',
    categoria: 'internet',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'i02',
    complemento: 'procurei a mim mesmo no Google',
    categoria: 'internet',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'i03',
    complemento: 'fiquei verificando os likes a cada 5 minutos por uma hora depois de postar',
    categoria: 'internet',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'i04',
    complemento: 'me perdi no perfil de um desconhecido por mais de 30 minutos',
    categoria: 'internet',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'i05',
    complemento: 'repostei algo sem checar se era verdade',
    categoria: 'internet',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'i06',
    complemento: 'vi que a pessoa havia lido minha mensagem e entrei no avião imediatamente',
    categoria: 'internet',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'i07',
    complemento: 'deletei foto minha que não bateu a expectativa de curtidas',
    categoria: 'internet',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'i08',
    complemento: 'fingi não ter visto uma mensagem por dias para não ter que responder',
    categoria: 'internet',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'i09',
    complemento: 'segui e dessegui alguém três vezes no mesmo dia com medo de ser notado',
    categoria: 'internet',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'i10',
    complemento: 'pesquisei o perfil de alguém que mal conheço mais de 20 vezes em uma semana',
    categoria: 'internet',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'i11',
    complemento: 'fiquei em modo fantasma nas redes mas vi story de todo mundo',
    categoria: 'internet',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'i12',
    complemento: 'mandei print de uma conversa sem tirar a outra pessoa da janela antes',
    categoria: 'internet',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'i13',
    complemento: 'bloqueei e desbloqueei alguém sem razão específica',
    categoria: 'internet',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'i14',
    complemento: 'li a conversa inteira com outra pessoa antes de responder porque não sabia o que dizer',
    categoria: 'internet',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'i15',
    complemento: 'respondi mensagem de alguém após dias como se tivesse esquecido — mas não tinha',
    categoria: 'internet',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'i16',
    complemento: 'fingi estar offline enquanto estava ativo',
    categoria: 'internet',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'i17',
    complemento: 'estalei o dedo no story de alguém por acidente e entrei em colapso silencioso',
    categoria: 'internet',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },

  // ─── RELACIONAMENTOS (18 cartas) ────────────────────────────────────────────
  {
    id: 'r01',
    complemento: 'fiz de conta que não reconheci um ex no mercado',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'r02',
    complemento: 'chequei o status de um ex mais de uma vez num dia',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'r03',
    complemento: 'terminei um relacionamento por mensagem',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'r04',
    complemento: 'bloqueei alguém sem dar nenhuma satisfação e nunca me arrependi',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'r05',
    complemento: 'mandei indireta pública claramente direcionada a uma pessoa específica',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'r06',
    complemento: 'terminei um relacionamento e me arrependi imediatamente — mas não voltei',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'r07',
    complemento: 'me apaixonei por alguém que nunca soube',
    categoria: 'relacionamentos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'r08',
    complemento: 'entrei num relacionamento só por não saber como dizer não',
    categoria: 'relacionamentos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'r09',
    complemento: 'inventei um compromisso pra não encontrar com alguém que estava ficando',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'r10',
    complemento: 'ignorei completamente alguém após uma ficada',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'r11',
    complemento: 'fiz algo específico só pra deixar alguém com ciúmes',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'r12',
    complemento: 'menti sobre onde estava pra alguém com quem estava ficando',
    categoria: 'relacionamentos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'r13',
    complemento: 'xinguei um ex com vocabulário criativo — em voz alta, sozinho',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'r14',
    complemento: 'fiquei com duas pessoas no mesmo final de semana',
    categoria: 'relacionamentos',
    intensidade: 'pessoal',
    mais18: true,
    fase: 'pico',
  },
  {
    id: 'r15',
    complemento: 'descobri tarde demais que a pessoa com quem eu estava ficando tinha outra história mal resolvida',
    categoria: 'relacionamentos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'r16',
    complemento: 'falei o nome errado num momento muito inoportuno',
    categoria: 'relacionamentos',
    intensidade: 'caotico',
    mais18: true,
    fase: 'pico',
  },
  {
    id: 'r17',
    complemento: 'enviei foto que era claramente pra outra pessoa',
    categoria: 'relacionamentos',
    intensidade: 'caotico',
    mais18: true,
    fase: 'pico',
  },
  {
    id: 'r18',
    complemento: 'fui mais honesto com alguém depois de terminar do que durante o relacionamento',
    categoria: 'relacionamentos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'release',
  },

  // ─── EGO (16 cartas) ────────────────────────────────────────────────────────
  {
    id: 'e01',
    complemento: 'passei mais de 5 minutos escolhendo a foto perfeita pro perfil',
    categoria: 'ego',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'e02',
    complemento: 'me elogiei na minha cabeça depois de uma frase boa que disse',
    categoria: 'ego',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'e03',
    complemento: 'checei meu próprio perfil pra ver como eu aparecia pra outras pessoas',
    categoria: 'ego',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'e04',
    complemento: 'parei em frente ao espelho e fiquei olhando pra mim mesmo por tempo demais',
    categoria: 'ego',
    intensidade: 'social',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'e05',
    complemento: 'fingi não saber fazer algo pra parecer humilde',
    categoria: 'ego',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'e06',
    complemento: 'me gabei de algo que na verdade eu tinha só participado marginalmente',
    categoria: 'ego',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'e07',
    complemento: 'deixei alguém esperando pra parecer mais ocupado do que estava',
    categoria: 'ego',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'e08',
    complemento: 'falei sobre um título, prêmio ou conquista num contexto que ninguém tinha pedido',
    categoria: 'ego',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'e09',
    complemento: 'comprei algo além das minhas posses só pra aparentar',
    categoria: 'ego',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'e10',
    complemento: 'inventei ou exagerei habilidade num momento que precisava impressionar',
    categoria: 'ego',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'e11',
    complemento: 'me ofendi internamente por não ser reconhecido num grupo',
    categoria: 'ego',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'e12',
    complemento: 'não admiti que errei pra não quebrar a imagem que as pessoas têm de mim',
    categoria: 'ego',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'e13',
    complemento: 'superestimei o impacto que eu tinha numa situação',
    categoria: 'ego',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'e14',
    complemento: 'me achei mais bonito do que a pessoa que me ignorou',
    categoria: 'ego',
    intensidade: 'leve',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'e15',
    complemento: 'pesquisei salário da minha profissão só pra me confirmar que estou bem',
    categoria: 'ego',
    intensidade: 'leve',
    mais18: false,
    fase: 'release',
  },
  {
    id: 'e16',
    complemento: 'ensaiei uma frase de efeito antes de uma conversa que era banal',
    categoria: 'ego',
    intensidade: 'social',
    mais18: false,
    fase: 'release',
  },

  // ─── VIDA ADULTA (17 cartas) ─────────────────────────────────────────────────
  {
    id: 'va01',
    complemento: 'comi o jantar de ontem no café da manhã sem a menor culpa',
    categoria: 'vida_adulta',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'va02',
    complemento: 'me atrasei em algo importante porque estava no celular',
    categoria: 'vida_adulta',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'va03',
    complemento: 'comi direto da panela pra não sujar prato',
    categoria: 'vida_adulta',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'va04',
    complemento: 'planejei uma viagem em detalhes e nunca fui',
    categoria: 'vida_adulta',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'va05',
    complemento: 'fiquei acordado tão tarde que virou manhã cedo',
    categoria: 'vida_adulta',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'va06',
    complemento: 'procurei sintoma no Google e me convenci de doença grave',
    categoria: 'vida_adulta',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'va07',
    complemento: 'cancelei um compromisso e me senti genuinamente aliviado',
    categoria: 'vida_adulta',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'va08',
    complemento: 'paguei uma conta atrasada usando outra conta',
    categoria: 'vida_adulta',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'va09',
    complemento: 'tive uma epifania às 3 da manhã e não executei nada disso no dia seguinte',
    categoria: 'vida_adulta',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'va10',
    complemento: 'demorei mais pra responder mensagem de trabalho do que de entretenimento',
    categoria: 'vida_adulta',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'va11',
    complemento: 'fingi não ver o e-mail importante e deixei o prazo vencer',
    categoria: 'vida_adulta',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'va12',
    complemento: 'evitei situação adulta que deveria ter resolvido há meses',
    categoria: 'vida_adulta',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'va13',
    complemento: 'comprei algo num impulso e guardei a embalagem pra não ser julgado',
    categoria: 'vida_adulta',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'va14',
    complemento: 'menti na entrevista de emprego sobre habilidade que aprendi na noite anterior',
    categoria: 'vida_adulta',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'va15',
    complemento: 'fingi entender um contrato ou formulário e assinei com confiança',
    categoria: 'vida_adulta',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'va16',
    complemento: 'guardei dinheiro em reserva de emergência e usei em outra coisa',
    categoria: 'vida_adulta',
    intensidade: 'social',
    mais18: false,
    fase: 'release',
  },
  {
    id: 'va17',
    complemento: 'tomei decisão financeira importante sem consultar ninguém e não me arrependo',
    categoria: 'vida_adulta',
    intensidade: 'social',
    mais18: false,
    fase: 'release',
  },

  // ─── SEGREDOS (16 cartas) ────────────────────────────────────────────────────
  {
    id: 's01',
    complemento: 'gostei secretamente de uma música que publicamente digo odiar',
    categoria: 'segredos',
    intensidade: 'social',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 's02',
    complemento: 'guardo conversas antigas só pra reler quando fico saudoso',
    categoria: 'segredos',
    intensidade: 'social',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 's03',
    complemento: 'assisti algo que nunca vou admitir em voz alta',
    categoria: 'segredos',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 's04',
    complemento: 'me impressionei com algo que finjo achar ridículo',
    categoria: 'segredos',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 's05',
    complemento: 'disse que estava ocupado quando na verdade só queria ficar sozinho',
    categoria: 'segredos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 's06',
    complemento: 'preparei uma desculpa antes de aceitar um convite',
    categoria: 'segredos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 's07',
    complemento: 'mudei de opinião e demorei a admitir porque eu tinha defendido demais a antiga',
    categoria: 'segredos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 's08',
    complemento: 'lembro de uma pequena injustiça muito mais do que gostaria',
    categoria: 'segredos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 's09',
    complemento: 'deixei parecer que uma ideia tinha sido minha sem corrigir na hora',
    categoria: 'segredos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 's10',
    complemento: 'guardei uma fofoca boa por semanas esperando a hora certa de contar',
    categoria: 'segredos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 's11',
    complemento: 'soube antes de todo mundo de uma novidade e adorei ter essa vantagem',
    categoria: 'segredos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 's12',
    complemento: 'tenho um gosto muito fora da minha imagem que quase ninguém conhece',
    categoria: 'segredos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 's13',
    complemento: 'escondi uma compra da família porque sabia que renderia comentário',
    categoria: 'segredos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 's14',
    complemento: 'mudei de ideia sobre um conselho que segui e nunca contei a quem deu',
    categoria: 'segredos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'release',
  },
  {
    id: 's15',
    complemento: 'tenho uma versão diferente de uma história que sempre conto da mesma forma',
    categoria: 'segredos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'release',
  },
  {
    id: 's16',
    complemento: 'guardo uma história excelente porque ainda não achei o grupo certo pra contar',
    categoria: 'segredos',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'release',
  },

  // ─── HIPOCRISIA (16 cartas) ─────────────────────────────────────────────────
  {
    id: 'h01',
    complemento: 'dei conselho que eu mesmo não seguia',
    categoria: 'hipocrisia',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'h02',
    complemento: 'disse que não tenho favoritos — e claramente tenho',
    categoria: 'hipocrisia',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'h03',
    complemento: 'reclamei de fila no supermercado e entrei na fila errada em seguida',
    categoria: 'hipocrisia',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'h04',
    complemento: 'fiz piada sobre não entender tecnologia e usei o Google pra checar depois',
    categoria: 'hipocrisia',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'h05',
    complemento: 'elogiei algo que secretamente achava ruim',
    categoria: 'hipocrisia',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'h06',
    complemento: 'discordei de algo só pra parecer crítico',
    categoria: 'hipocrisia',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'h07',
    complemento: 'reclamei de barulho e logo depois fiz barulho',
    categoria: 'hipocrisia',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'h08',
    complemento: 'critiquei exibicionismo nas redes e postei foto bem produzida logo depois',
    categoria: 'hipocrisia',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'h09',
    complemento: 'julguei alguém por não saber algo que eu também não sabia há pouco tempo',
    categoria: 'hipocrisia',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'h10',
    complemento: 'defendi privacidade e fui stalkar alguém no mesmo dia',
    categoria: 'hipocrisia',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'h11',
    complemento: 'critiquei bebedeira e acordei com ressaca no final de semana seguinte',
    categoria: 'hipocrisia',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'h12',
    complemento: 'defendi ideia firmemente sem ter certeza se a entendia',
    categoria: 'hipocrisia',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'h13',
    complemento: 'falei que é importante ser honesto e menti naquele mesmo dia',
    categoria: 'hipocrisia',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'h14',
    complemento: 'reclamei de alguém que age exatamente como eu ajo',
    categoria: 'hipocrisia',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'h15',
    complemento: 'disse que não me importo com o que as pessoas pensam e mudei de comportamento por causa de um olhar',
    categoria: 'hipocrisia',
    intensidade: 'pessoal',
    mais18: false,
    fase: 'release',
  },
  {
    id: 'h16',
    complemento: 'falei que dinheiro não é tudo e tomei decisão puramente financeira em seguida',
    categoria: 'hipocrisia',
    intensidade: 'social',
    mais18: false,
    fase: 'release',
  },

  // ─── EXPOSED (17 cartas) ────────────────────────────────────────────────────
  {
    id: 'x01',
    complemento: 'disse "não fui eu" com cara de quem foi',
    categoria: 'exposed',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'x02',
    complemento: 'minha expressão entregou minha reação antes de eu conseguir disfarçar',
    categoria: 'exposed',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'x03',
    complemento: 'ri de algo que deveria ter ficado sério',
    categoria: 'exposed',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'x04',
    complemento: 'entrei numa sala com cara de saber o que estava acontecendo — e não sabia nada',
    categoria: 'exposed',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'x05',
    complemento: 'tentei entrar numa conversa achando que conhecia o assunto e errei o contexto inteiro',
    categoria: 'exposed',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'x06',
    complemento: 'achei que estava sendo discreto e mais tarde soube que todo mundo sabia',
    categoria: 'exposed',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'x07',
    complemento: 'dei uma desculpa elaborada e a outra parte já sabia a verdade antes de eu terminar',
    categoria: 'exposed',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'x08',
    complemento: 'reclamei de alguém e essa pessoa estava do outro lado da porta',
    categoria: 'exposed',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'x09',
    complemento: 'tentei ajudar uma situação e a piorei de forma irreversível',
    categoria: 'exposed',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'x10',
    complemento: 'fui culpado por algo que eu realmente fiz mas continuei negando',
    categoria: 'exposed',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'x11',
    complemento: 'tinha álibi que desabou porque alguém postou uma foto no momento errado',
    categoria: 'exposed',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'x12',
    complemento: 'enviei exatamente o que estava falando da pessoa — pra ela mesma',
    categoria: 'exposed',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'x13',
    complemento: 'fui pego numa situação que só piora quanto mais você tenta explicar',
    categoria: 'exposed',
    intensidade: 'caotico',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'x14',
    complemento: 'fingi não gostar de algo e fui pego desfrutando às escondidas',
    categoria: 'exposed',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'x15',
    complemento: 'fui pego numa situação constrangedora em câmera que não sabia que estava ligada',
    categoria: 'exposed',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'x16',
    complemento: 'fui exposto num grupo por algo que achei que era segredo',
    categoria: 'exposed',
    intensidade: 'caotico',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'x17',
    complemento: 'fui pego mentindo numa situação em que todo mundo ainda acreditava na mentira',
    categoria: 'exposed',
    intensidade: 'caotico',
    mais18: false,
    fase: 'release',
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getCategoria(id: CategoriaEuNuncaId): CategoriaEuNunca {
  return CATEGORIAS_EU_NUNCA.find((c) => c.id === id) ?? CATEGORIAS_EU_NUNCA[0]!;
}

export function getCategoriasPorIds(
  ids: CategoriaEuNuncaId[] | 'todas',
): CategoriaEuNunca[] {
  if (ids === 'todas') return CATEGORIAS_EU_NUNCA;
  return CATEGORIAS_EU_NUNCA.filter((c) => ids.includes(c.id));
}

export function pesoIntensidade(i: IntensidadeEuNunca): number {
  const pesos: Record<IntensidadeEuNunca, number> = {
    leve: 1,
    social: 2,
    pessoal: 3,
    caotico: 4,
  };
  return pesos[i];
}
