// ─── Verdade ou Desafio — Editorial de Cartas ────────────────────────────────
//
// 121 cartas: 55 verdades + 66 desafios.
// Curadoria: não genérico, não adolescente, não chocante sem graça.
// Cada carta deve disparar conversa real — não apenas a ação em si.
//
// Verdades: perguntas que revelam história, caráter ou vulnerabilidade.
// Desafios: missões que geram momento memorável no grupo.

import type {
  CartaVD,
  CategoriaVD,
  CategoriaVDId,
  IntensidadeVD,
} from './types';

export const CATEGORIAS_VD: CategoriaVD[] = [
  {
    id: 'autoconhecimento',
    nome: 'Autoconhecimento',
    descricao: 'quem você é por dentro',
    emoji: '🧠',
    tipo: 'verdade',
    temMais18: false,
  },
  {
    id: 'relacionamentos',
    nome: 'Relacionamentos',
    descricao: 'namoro, ficada, ex e paixão',
    emoji: '💔',
    tipo: 'verdade',
    temMais18: true,
  },
  {
    id: 'grupo',
    nome: 'Sobre o Grupo',
    descricao: 'opiniões honestas sobre quem está aqui',
    emoji: '👥',
    tipo: 'verdade',
    temMais18: false,
  },
  {
    id: 'vergonha',
    nome: 'Vergonha',
    descricao: 'momentos constrangedores que você guarda',
    emoji: '😬',
    tipo: 'verdade',
    temMais18: false,
  },
  {
    id: 'coragem',
    nome: 'Coragem',
    descricao: 'medos, limites e o que te trava',
    emoji: '🔥',
    tipo: 'verdade',
    temMais18: false,
  },
  {
    id: 'desafio_social',
    nome: 'Desafio Social',
    descricao: 'improviso e interação ao vivo',
    emoji: '📲',
    tipo: 'desafio',
    temMais18: false,
  },
  {
    id: 'desafio_fisico',
    nome: 'Desafio Físico',
    descricao: 'ação corporal e performance',
    emoji: '🎭',
    tipo: 'desafio',
    temMais18: false,
  },
  {
    id: 'desafio_caotico',
    nome: 'Desafio Caótico',
    descricao: 'missões que envolvem o grupo todo',
    emoji: '💥',
    tipo: 'desafio',
    temMais18: false,
  },
];

export const CARTAS_VD: CartaVD[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // VERDADES (55 cartas)
  // ═══════════════════════════════════════════════════════════════════════════

  // ─── AUTOCONHECIMENTO (11 cartas) ─────────────────────────────────────────
  {
    id: 'au01',
    tipo: 'verdade',
    texto: 'Qual mania sua sempre rende comentário de quem convive com você?',
    categoria: 'autoconhecimento',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'au02',
    tipo: 'verdade',
    texto: 'Qual é a habilidade secreta que você tem e que ninguém imagina?',
    categoria: 'autoconhecimento',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'au03',
    tipo: 'verdade',
    texto: 'Qual é o hábito seu que te envergonha mas você continua fazendo?',
    categoria: 'autoconhecimento',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'au04',
    tipo: 'verdade',
    texto: 'O que você nunca admitiria publicamente que te dá orgulho?',
    categoria: 'autoconhecimento',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'au05',
    tipo: 'verdade',
    texto: 'O que te deixa com ciúmes que você nunca admitiria?',
    categoria: 'autoconhecimento',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'au06',
    tipo: 'verdade',
    texto: 'Qual é a coisa mais egoísta que você já fez — e não se arrependeu completamente?',
    categoria: 'autoconhecimento',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'au07',
    tipo: 'verdade',
    texto: 'Qual foi a decisão mais difícil que você já tomou — e você tomaria de novo?',
    categoria: 'autoconhecimento',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'au08',
    tipo: 'verdade',
    texto: 'Qual opinião boba você defende com convicção, mesmo sabendo que o grupo vai discordar?',
    categoria: 'autoconhecimento',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'au09',
    tipo: 'verdade',
    texto: 'Qual escolha sua parecia uma péssima ideia e acabou virando uma boa história?',
    categoria: 'autoconhecimento',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'au10',
    tipo: 'verdade',
    texto: 'Qual elogio específico alguém desta roda merece ouvir hoje?',
    categoria: 'autoconhecimento',
    intensidade: 'caotico',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'au11',
    tipo: 'verdade',
    texto: 'O que as pessoas erram completamente na percepção que têm de você?',
    categoria: 'autoconhecimento',
    intensidade: 'social',
    mais18: false,
    fase: 'release',
  },

  // ─── RELACIONAMENTOS (13 cartas) ──────────────────────────────────────────
  {
    id: 're01',
    tipo: 'verdade',
    texto: 'Qual é o motivo mais ridículo pelo qual você já terminou ou foi terminado?',
    categoria: 'relacionamentos',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 're02',
    tipo: 'verdade',
    texto: 'Qual foi a coisa mais exagerada que você já fez por alguém que gostava?',
    categoria: 'relacionamentos',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 're03',
    tipo: 'verdade',
    texto: 'Qual foi a ficada mais estranha ou inesperada que você já teve?',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 're04',
    tipo: 'verdade',
    texto: 'Você já fingiu curtir algo só por causa de uma pessoa e acabou gostando de verdade?',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 're05',
    tipo: 'verdade',
    texto: 'Você já terminou e voltou com a mesma pessoa mais de uma vez? Valeu a pena?',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 're06',
    tipo: 'verdade',
    texto: 'Qual foi o crush mais improvável que você já teve?',
    categoria: 'relacionamentos',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 're07',
    tipo: 'verdade',
    texto: 'Você já se apaixonou por alguém que nunca soube?',
    categoria: 'relacionamentos',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 're08',
    tipo: 'verdade',
    texto: 'Qual costume de relacionamento você demorou mais para entender?',
    categoria: 'relacionamentos',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 're09',
    tipo: 'verdade',
    texto: 'Você já prolongou uma ficada por não saber como encerrar a conversa?',
    categoria: 'relacionamentos',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 're10',
    tipo: 'verdade',
    texto: 'Você já teve um crush claramente inviável e demorou para aceitar?',
    categoria: 'relacionamentos',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 're11',
    tipo: 'verdade',
    texto: 'Você já disse "te amo" sem sentir — ou sentiu mas nunca disse?',
    categoria: 'relacionamentos',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 're12',
    tipo: 'verdade',
    texto: 'Você já ficou com duas pessoas no mesmo período — e elas sabiam uma da outra?',
    categoria: 'relacionamentos',
    intensidade: 'caotico',
    mais18: true,
    fase: 'pico',
  },
  {
    id: 're13',
    tipo: 'verdade',
    texto: 'Você foi mais honesto com alguém depois de terminar do que durante o relacionamento?',
    categoria: 'relacionamentos',
    intensidade: 'pesado',
    mais18: false,
    fase: 'release',
  },

  // ─── GRUPO (10 cartas) ────────────────────────────────────────────────────
  {
    id: 'gr01',
    tipo: 'verdade',
    texto: 'Quem aqui organizaria melhor um rolê decidido de última hora?',
    categoria: 'grupo',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'gr02',
    tipo: 'verdade',
    texto: 'Quem aqui dorme mais tarde? Você apostaria dinheiro nisso?',
    categoria: 'grupo',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'gr03',
    tipo: 'verdade',
    texto: 'Quem aqui você mais admira — e nunca falou isso diretamente?',
    categoria: 'grupo',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'gr04',
    tipo: 'verdade',
    texto: 'Quem aqui você acha que ainda vai muito longe? Justifica.',
    categoria: 'grupo',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'gr05',
    tipo: 'verdade',
    texto: 'Quem aqui você acha mais difícil de ler? O que te confunde nessa pessoa?',
    categoria: 'grupo',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'gr06',
    tipo: 'verdade',
    texto: 'Tem alguém aqui que você julgou antes de conhecer — e o julgamento mudou?',
    categoria: 'grupo',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'gr07',
    tipo: 'verdade',
    texto: 'Quem aqui escolheria o encontro mais inesperado e ainda faria dar certo?',
    categoria: 'grupo',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'gr08',
    tipo: 'verdade',
    texto: 'Quem aqui manteria a calma melhor num perrengue inesperado?',
    categoria: 'grupo',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'gr09',
    tipo: 'verdade',
    texto: 'Quem aqui você escolheria para guardar uma surpresa até o final?',
    categoria: 'grupo',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'gr10',
    tipo: 'verdade',
    texto: 'Quem aqui se adapta mais rápido a qualquer grupo novo?',
    categoria: 'grupo',
    intensidade: 'pesado',
    mais18: false,
    fase: 'release',
  },

  // ─── VERGONHA (11 cartas) ─────────────────────────────────────────────────
  {
    id: 've01',
    tipo: 'verdade',
    texto: 'Qual é o filme, série ou músico que você ama mas te envergonha admitir?',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 've02',
    tipo: 'verdade',
    texto: 'Qual é o nome famoso ou personagem que você pronunciou errado por muito tempo sem perceber?',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 've03',
    tipo: 'verdade',
    texto: 'Qual é o momento mais constrangedor que você se lembra com absoluta clareza?',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 've04',
    tipo: 'verdade',
    texto: 'Qual é a coisa mais ridícula que você já pesquisou no Google?',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 've05',
    tipo: 'verdade',
    texto: 'Você já fingiu estar dormindo pra evitar alguém? Funcionou?',
    categoria: 'vergonha',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 've06',
    tipo: 'verdade',
    texto: 'Você já comentou algo num post achando que era uma mensagem privada?',
    categoria: 'vergonha',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 've07',
    tipo: 'verdade',
    texto: 'Qual foi o pior trabalho, apresentação ou performance que você já deu em público?',
    categoria: 'vergonha',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 've08',
    tipo: 'verdade',
    texto: 'Você já foi pego numa mentira que jurou de pé junto que conseguiria sustentar?',
    categoria: 'vergonha',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 've09',
    tipo: 'verdade',
    texto: 'Qual fase sua renderia o melhor episódio de comédia se fosse contada hoje?',
    categoria: 'vergonha',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 've10',
    tipo: 'verdade',
    texto: 'Você mandou áudio de bêbado pra alguém e fingiu que não foi você?',
    categoria: 'vergonha',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 've11',
    tipo: 'verdade',
    texto: 'Qual vergonha antiga hoje já virou uma história boa de contar?',
    categoria: 'vergonha',
    intensidade: 'pesado',
    mais18: false,
    fase: 'release',
  },

  // ─── CORAGEM (10 cartas) ──────────────────────────────────────────────────
  {
    id: 'co01',
    tipo: 'verdade',
    texto: 'Qual é o maior medo físico que você tem — que vai além do normal?',
    categoria: 'coragem',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'co02',
    tipo: 'verdade',
    texto: 'Você já desistiu de algo importante por medo — e se arrependeu?',
    categoria: 'coragem',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'co03',
    tipo: 'verdade',
    texto: 'Qual pequena tarefa você adia tanto que já virou piada consigo mesmo?',
    categoria: 'coragem',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'co04',
    tipo: 'verdade',
    texto: 'Você já quis sair de uma situação mas ficou por pura obrigação social?',
    categoria: 'coragem',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'co05',
    tipo: 'verdade',
    texto: 'Você já evitou uma oportunidade real por medo de falhar em público?',
    categoria: 'coragem',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'co06',
    tipo: 'verdade',
    texto: 'Qual coisa nova você gostaria de tentar se tivesse uma torcida do grupo?',
    categoria: 'coragem',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'co07',
    tipo: 'verdade',
    texto: 'O que você teria feito diferente se não tivesse medo do que as pessoas pensam?',
    categoria: 'coragem',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'co08',
    tipo: 'verdade',
    texto: 'Qual é a opinião que você sustenta em silêncio porque sabe que vai causar conflito?',
    categoria: 'coragem',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'co09',
    tipo: 'verdade',
    texto: 'Qual é a coisa que você nunca faria mesmo com muito dinheiro envolvido?',
    categoria: 'coragem',
    intensidade: 'caotico',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'co10',
    tipo: 'verdade',
    texto: 'Qual desafio bobo te assusta mais do que deveria, mas você toparia com incentivo?',
    categoria: 'coragem',
    intensidade: 'caotico',
    mais18: false,
    fase: 'release',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DESAFIOS (66 cartas)
  // ═══════════════════════════════════════════════════════════════════════════

  // ─── DESAFIO SOCIAL — improviso e interação ao vivo (22 cartas) ───────────
  {
    id: 'ds01',
    tipo: 'desafio',
    texto: 'Fale 5 palavras que te descrevem em 10 segundos. O grupo julga se concordam.',
    categoria: 'desafio_social',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'ds02',
    tipo: 'desafio',
    texto: 'Conte uma história de 30 segundos usando no máximo 10 palavras diferentes.',
    categoria: 'desafio_social',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'ds03',
    tipo: 'desafio',
    texto: 'Fale um fato verdadeiro e dois inventados. O grupo tem 30 segundos pra descobrir qual é o verdadeiro.',
    categoria: 'desafio_social',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'ds04',
    tipo: 'desafio',
    texto: 'Descreva seu dia de hoje como se fosse a sinopse de um filme de ação.',
    categoria: 'desafio_social',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'ds05',
    tipo: 'desafio',
    texto: 'Faça a pose da foto mais vergonhosa que você jamais postaria.',
    categoria: 'desafio_social',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'ds06',
    tipo: 'desafio',
    texto: 'Encene três tipos de meme sem falar; o grupo tenta identificar.',
    categoria: 'desafio_social',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'ds07',
    tipo: 'desafio',
    texto: 'Interprete como você escreve quando tenta fingir que não está ansioso por resposta.',
    categoria: 'desafio_social',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'ds08',
    tipo: 'desafio',
    texto: 'Invente uma busca absurda que combinaria com você e defenda por que pesquisaria isso.',
    categoria: 'desafio_social',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'ds09',
    tipo: 'desafio',
    texto: 'Cante um trecho de uma música que define sua semana; o grupo adivinha o clima.',
    categoria: 'desafio_social',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'ds10',
    tipo: 'desafio',
    texto: 'Dite uma mensagem absurda que você jamais teria coragem de mandar para um contato aleatório.',
    categoria: 'desafio_social',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'ds11',
    tipo: 'desafio',
    texto: 'Interprete um story sem filtro que você nunca publicaria.',
    categoria: 'desafio_social',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'ds12',
    tipo: 'desafio',
    texto: 'Interprete o reencontro mais dramático possível com alguém que sumiu.',
    categoria: 'desafio_social',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'ds13',
    tipo: 'desafio',
    texto: 'Interprete ao vivo o áudio mais dramático que alguém mandaria ao perceber que exagerou.',
    categoria: 'desafio_social',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'ds14',
    tipo: 'desafio',
    texto: 'Deixe o grupo escolher uma legenda constrangedora; você precisa posar para esse story imaginário.',
    categoria: 'desafio_social',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'ds15',
    tipo: 'desafio',
    texto: 'Cante parabéns como se estivesse numa ligação completamente errada; o grupo faz a outra ponta.',
    categoria: 'desafio_social',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'ds16',
    tipo: 'desafio',
    texto: 'Faça um discurso de "saudades" para um personagem imaginário que claramente não merece.',
    categoria: 'desafio_social',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'ds17',
    tipo: 'desafio',
    texto: 'Leia em voz alta a mensagem mais inadequada que alguém mandaria no grupo da família ou do trabalho.',
    categoria: 'desafio_social',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'ds18',
    tipo: 'desafio',
    texto: 'Faça três poses de selfie progressivamente piores; o grupo escolhe a campeã.',
    categoria: 'desafio_social',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'ds19',
    tipo: 'desafio',
    texto: 'O grupo te dá três palavras e você improvisa uma conversa suspeita usando todas.',
    categoria: 'desafio_social',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'ds20',
    tipo: 'desafio',
    texto: 'Conte uma fofoca fictícia usando apenas gestos e sons; o grupo tenta reconstruir a história.',
    categoria: 'desafio_social',
    intensidade: 'caotico',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'ds21',
    tipo: 'desafio',
    texto: 'Faça o pedido de desculpas mais exagerado por ter cometido um erro minúsculo e inventado.',
    categoria: 'desafio_social',
    intensidade: 'caotico',
    mais18: false,
    fase: 'release',
  },
  {
    id: 'ds22',
    tipo: 'desafio',
    texto: 'Peça um favor impossível a alguém do grupo como se sua vida dependesse disso.',
    categoria: 'desafio_social',
    intensidade: 'caotico',
    mais18: false,
    fase: 'release',
  },

  // ─── DESAFIO FÍSICO — ação corporal e performance (22 cartas) ─────────────
  {
    id: 'df01',
    tipo: 'desafio',
    texto: 'Imite uma celebridade conhecida até o grupo adivinhar quem é.',
    categoria: 'desafio_fisico',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'df02',
    tipo: 'desafio',
    texto: 'Fale seu nome ao contrário 3 vezes seguidas o mais rápido possível.',
    categoria: 'desafio_fisico',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'df03',
    tipo: 'desafio',
    texto: 'Interprete alguém tentando caminhar discretamente depois de fazer barulho de madrugada.',
    categoria: 'desafio_fisico',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'df04',
    tipo: 'desafio',
    texto: 'Faça 3 poses de modelo seguidas com a cara mais séria que conseguir.',
    categoria: 'desafio_fisico',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'df05',
    tipo: 'desafio',
    texto: 'Dance por 30 segundos sem música. Sem parar, sem rir.',
    categoria: 'desafio_fisico',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'df06',
    tipo: 'desafio',
    texto: 'Tente se equilibrar numa perna só por 30 segundos enquanto conta de trás pra frente.',
    categoria: 'desafio_fisico',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'df07',
    tipo: 'desafio',
    texto: 'Faça a voz mais grave possível e diga uma frase dramática de novela.',
    categoria: 'desafio_fisico',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'df08',
    tipo: 'desafio',
    texto: 'Cante o refrão da última música que você ouviu — o grupo precisa reconhecer.',
    categoria: 'desafio_fisico',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'df09',
    tipo: 'desafio',
    texto: 'Imite um animal por 30 segundos. O grupo tem que adivinhar qual é.',
    categoria: 'desafio_fisico',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'df10',
    tipo: 'desafio',
    texto: 'Narre o que está acontecendo como um repórter ao vivo em plena confusão.',
    categoria: 'desafio_fisico',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'df11',
    tipo: 'desafio',
    texto: 'Faça uma coreografia de 20 segundos usando a música que alguém do grupo escolher.',
    categoria: 'desafio_fisico',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'df12',
    tipo: 'desafio',
    texto: 'Invente um alongamento absurdo e convença o grupo a copiar por 15 segundos.',
    categoria: 'desafio_fisico',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'df13',
    tipo: 'desafio',
    texto: 'Tente tocar o nariz com a língua por 10 segundos enquanto mantém pose de capa de revista.',
    categoria: 'desafio_fisico',
    intensidade: 'leve',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'df14',
    tipo: 'desafio',
    texto: 'Faça a imitação mais convincente de alguém famoso que o grupo vai conseguir adivinhar.',
    categoria: 'desafio_fisico',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'df15',
    tipo: 'desafio',
    texto: 'Faça a última série que você viu em 45 segundos. Cenário, personagens, climão.',
    categoria: 'desafio_fisico',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'df16',
    tipo: 'desafio',
    texto: 'Faça o movimento mais estranho que você consegue por 15 segundos. Sem rir.',
    categoria: 'desafio_fisico',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'df17',
    tipo: 'desafio',
    texto: 'Tente fazer alguém do grupo rir em 20 segundos. Não pode tocar a pessoa.',
    categoria: 'desafio_fisico',
    intensidade: 'social',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'df18',
    tipo: 'desafio',
    texto: 'Feche os olhos e tente apontar de onde veio uma palma. O grupo pode fazer três tentativas.',
    categoria: 'desafio_fisico',
    intensidade: 'leve',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'df19',
    tipo: 'desafio',
    texto: 'Invente uma cena de novela de 30 segundos com dois jogadores que toparem.',
    categoria: 'desafio_fisico',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'df20',
    tipo: 'desafio',
    texto: 'Faça um discurso emocionado de premiação para dois personagens inventados pelo grupo.',
    categoria: 'desafio_fisico',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'df21',
    tipo: 'desafio',
    texto: 'Imite carinhosamente o jogador à sua direita por 20 segundos até o grupo reconhecer.',
    categoria: 'desafio_fisico',
    intensidade: 'pesado',
    mais18: false,
    fase: 'release',
  },
  {
    id: 'df22',
    tipo: 'desafio',
    texto: 'Conte uma história inventada em 30 segundos. O grupo tem 15 segundos pra apontar a mentira.',
    categoria: 'desafio_fisico',
    intensidade: 'pesado',
    mais18: false,
    fase: 'release',
  },

  // ─── DESAFIO CAÓTICO — envolvendo o grupo todo (22 cartas) ────────────────
  {
    id: 'dc01',
    tipo: 'desafio',
    texto: 'Diga um elogio genuíno pra cada pessoa do grupo. Sem repetir adjetivos.',
    categoria: 'desafio_caotico',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'dc02',
    tipo: 'desafio',
    texto: 'Invente um apelido de super-herói para alguém do grupo e explique o poder.',
    categoria: 'desafio_caotico',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'dc03',
    tipo: 'desafio',
    texto: 'Escolha a música que define cada pessoa do grupo. Canta ou tarararara a melodia.',
    categoria: 'desafio_caotico',
    intensidade: 'leve',
    mais18: false,
    fase: 'aquecimento',
  },
  {
    id: 'dc04',
    tipo: 'desafio',
    texto: 'Escolha alguém do grupo e descreva o jeito dela em exatamente 3 palavras. Não pode ser "legal", "divertida" ou "gente boa".',
    categoria: 'desafio_caotico',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'dc05',
    tipo: 'desafio',
    texto: 'Faça uma declaração pública de amizade pra alguém do grupo. Específica, não genérica.',
    categoria: 'desafio_caotico',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'dc06',
    tipo: 'desafio',
    texto: 'Recomende uma experiência divertida para a pessoa à sua esquerda. Tem que ser específica.',
    categoria: 'desafio_caotico',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'dc07',
    tipo: 'desafio',
    texto: 'Faça um brinde com palavras suas — uma frase que diga algo verdadeiro sobre o grupo agora.',
    categoria: 'desafio_caotico',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'dc08',
    tipo: 'desafio',
    texto: 'Sussurre uma mentira absurda no ouvido de alguém; a pessoa precisa defendê-la como verdade.',
    categoria: 'desafio_caotico',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'dc09',
    tipo: 'desafio',
    texto: 'Escolha um objeto imaginário que representa quem você é agora e venda essa ideia ao grupo.',
    categoria: 'desafio_caotico',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'dc10',
    tipo: 'desafio',
    texto: 'Escolha alguém que topar: façam 20 segundos de improvisação musical em dueto.',
    categoria: 'desafio_caotico',
    intensidade: 'social',
    mais18: false,
    fase: 'subida',
  },
  {
    id: 'dc11',
    tipo: 'desafio',
    texto: 'Deixe alguém do grupo dirigir sua pose para uma foto de perfil imaginária completamente fora do seu estilo.',
    categoria: 'desafio_caotico',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'dc12',
    tipo: 'desafio',
    texto: 'Escolha alguém que topar: encenem um duelo de olhares por 15 segundos, sem contato.',
    categoria: 'desafio_caotico',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'dc13',
    tipo: 'desafio',
    texto: 'Conte uma primeira impressão positiva ou engraçada de alguém do grupo.',
    categoria: 'desafio_caotico',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'dc14',
    tipo: 'desafio',
    texto: 'Escolha alguém pra dar um elogio que você nunca falou pra essa pessoa antes. Sem esquecer que o grupo está ouvindo.',
    categoria: 'desafio_caotico',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'dc15',
    tipo: 'desafio',
    texto: 'Escolha duas pessoas mais prováveis de topar uma aventura absurda e invente qual seria.',
    categoria: 'desafio_caotico',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'dc16',
    tipo: 'desafio',
    texto: 'Dê a cada pessoa do grupo um slogan de reality show que seja engraçado, sem ofender.',
    categoria: 'desafio_caotico',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'dc17',
    tipo: 'desafio',
    texto: 'Vote: quem aqui venderia melhor uma ideia absurda como se fosse genial? Explica.',
    categoria: 'desafio_caotico',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'dc18',
    tipo: 'desafio',
    texto: 'Vote: quem do grupo você apostaria que vai acordar mais cedo amanhã? E quem vai dormir mais tarde?',
    categoria: 'desafio_caotico',
    intensidade: 'leve',
    mais18: false,
    fase: 'release',
  },
  {
    id: 'dc19',
    tipo: 'desafio',
    texto: 'Escolha alguém que topar e façam uma pose de reencontro cinematográfico, sem contato obrigatório.',
    categoria: 'desafio_caotico',
    intensidade: 'pesado',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'dc20',
    tipo: 'desafio',
    texto: 'Escolha dois jogadores pra fazer um roleplay: um é o chefe, o outro acabou de chegar atrasado.',
    categoria: 'desafio_caotico',
    intensidade: 'caotico',
    mais18: false,
    fase: 'pico',
  },
  {
    id: 'dc21',
    tipo: 'desafio',
    texto: 'Vote em silêncio: quem teria a história mais inesperada de uma viagem? Todos revelam juntos.',
    categoria: 'desafio_caotico',
    intensidade: 'caotico',
    mais18: false,
    fase: 'release',
  },
  {
    id: 'dc22',
    tipo: 'desafio',
    texto: 'Faça uma previsão divertida para este grupo daqui a 5 anos. Todos podem completar.',
    categoria: 'desafio_caotico',
    intensidade: 'caotico',
    mais18: false,
    fase: 'release',
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getCategoria(id: CategoriaVDId): CategoriaVD {
  return CATEGORIAS_VD.find((c) => c.id === id) ?? CATEGORIAS_VD[0]!;
}

export function pesoIntensidade(i: IntensidadeVD): number {
  const pesos: Record<IntensidadeVD, number> = {
    leve: 1,
    social: 2,
    pesado: 3,
    caotico: 4,
  };
  return pesos[i];
}
