import type { DificuldadeSolo } from '@/games/solo/types';
import type { PuzzleShikaku } from './types';

// ⚙️ Gerado offline (scripts/gen-shikaku) com solução única verificada por solver.
// Não editar à mão — regerar caso precise de novos puzzles.

export const PUZZLES_SHIKAKU: PuzzleShikaku[] = [
  {
    id: 'facil-1',
    dificuldade: 'facil',
    linhas: 5,
    colunas: 5,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 0,
        pistaLinha: 2,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 1,
        linhaFim: 1,
        colunaFim: 3,
        pistaLinha: 0,
        pistaColuna: 3,
      },
      {
        linhaInicio: 0,
        colunaInicio: 4,
        linhaFim: 2,
        colunaFim: 4,
        pistaLinha: 2,
        pistaColuna: 4,
      },
      {
        linhaInicio: 2,
        colunaInicio: 1,
        linhaFim: 2,
        colunaFim: 2,
        pistaLinha: 2,
        pistaColuna: 1,
      },
      {
        linhaInicio: 2,
        colunaInicio: 3,
        linhaFim: 3,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 3,
      },
      {
        linhaInicio: 3,
        colunaInicio: 1,
        linhaFim: 4,
        colunaFim: 1,
        pistaLinha: 3,
        pistaColuna: 1,
      },
      {
        linhaInicio: 3,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 2,
        pistaLinha: 3,
        pistaColuna: 2,
      },
      {
        linhaInicio: 3,
        colunaInicio: 4,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 3,
        pistaColuna: 4,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 4,
        colunaFim: 0,
        pistaLinha: 4,
        pistaColuna: 0,
      },
      {
        linhaInicio: 4,
        colunaInicio: 3,
        linhaFim: 4,
        colunaFim: 3,
        pistaLinha: 4,
        pistaColuna: 3,
      },
    ],
  },
  {
    id: 'facil-2',
    dificuldade: 'facil',
    linhas: 5,
    colunas: 5,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 0,
        colunaFim: 1,
        pistaLinha: 0,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 2,
        linhaFim: 1,
        colunaFim: 4,
        pistaLinha: 0,
        pistaColuna: 2,
      },
      {
        linhaInicio: 1,
        colunaInicio: 0,
        linhaFim: 1,
        colunaFim: 1,
        pistaLinha: 1,
        pistaColuna: 0,
      },
      {
        linhaInicio: 2,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 2,
        pistaLinha: 3,
        pistaColuna: 0,
      },
      {
        linhaInicio: 2,
        colunaInicio: 3,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 3,
        pistaColuna: 3,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 4,
        colunaFim: 2,
        pistaLinha: 4,
        pistaColuna: 1,
      },
    ],
  },
  {
    id: 'facil-3',
    dificuldade: 'facil',
    linhas: 5,
    colunas: 5,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 0,
        pistaLinha: 1,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 1,
        linhaFim: 2,
        colunaFim: 2,
        pistaLinha: 1,
        pistaColuna: 1,
      },
      {
        linhaInicio: 0,
        colunaInicio: 3,
        linhaFim: 2,
        colunaFim: 4,
        pistaLinha: 1,
        pistaColuna: 4,
      },
      {
        linhaInicio: 3,
        colunaInicio: 1,
        linhaFim: 4,
        colunaFim: 1,
        pistaLinha: 3,
        pistaColuna: 1,
      },
      {
        linhaInicio: 3,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 3,
      },
      {
        linhaInicio: 3,
        colunaInicio: 4,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 4,
        pistaColuna: 4,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 4,
        colunaFim: 0,
        pistaLinha: 4,
        pistaColuna: 0,
      },
    ],
  },
  {
    id: 'facil-4',
    dificuldade: 'facil',
    linhas: 5,
    colunas: 5,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 1,
        colunaFim: 1,
        pistaLinha: 1,
        pistaColuna: 1,
      },
      {
        linhaInicio: 0,
        colunaInicio: 2,
        linhaFim: 1,
        colunaFim: 2,
        pistaLinha: 0,
        pistaColuna: 2,
      },
      {
        linhaInicio: 0,
        colunaInicio: 3,
        linhaFim: 1,
        colunaFim: 4,
        pistaLinha: 0,
        pistaColuna: 3,
      },
      {
        linhaInicio: 2,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 2,
        pistaLinha: 2,
        pistaColuna: 0,
      },
      {
        linhaInicio: 2,
        colunaInicio: 3,
        linhaFim: 3,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 3,
      },
      {
        linhaInicio: 2,
        colunaInicio: 4,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 4,
        pistaColuna: 4,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 4,
        colunaFim: 1,
        pistaLinha: 4,
        pistaColuna: 0,
      },
      {
        linhaInicio: 4,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 3,
        pistaLinha: 4,
        pistaColuna: 3,
      },
    ],
  },
  {
    id: 'facil-5',
    dificuldade: 'facil',
    linhas: 5,
    colunas: 5,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 0,
        colunaFim: 3,
        pistaLinha: 0,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 4,
        linhaFim: 1,
        colunaFim: 4,
        pistaLinha: 0,
        pistaColuna: 4,
      },
      {
        linhaInicio: 1,
        colunaInicio: 0,
        linhaFim: 2,
        colunaFim: 1,
        pistaLinha: 2,
        pistaColuna: 0,
      },
      {
        linhaInicio: 1,
        colunaInicio: 2,
        linhaFim: 2,
        colunaFim: 3,
        pistaLinha: 2,
        pistaColuna: 3,
      },
      {
        linhaInicio: 2,
        colunaInicio: 4,
        linhaFim: 3,
        colunaFim: 4,
        pistaLinha: 2,
        pistaColuna: 4,
      },
      {
        linhaInicio: 3,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 1,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 4,
        colunaFim: 1,
        pistaLinha: 4,
        pistaColuna: 1,
      },
      {
        linhaInicio: 4,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 3,
        pistaLinha: 4,
        pistaColuna: 2,
      },
      {
        linhaInicio: 4,
        colunaInicio: 4,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 4,
        pistaColuna: 4,
      },
    ],
  },
  {
    id: 'facil-6',
    dificuldade: 'facil',
    linhas: 5,
    colunas: 5,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 2,
        colunaFim: 1,
        pistaLinha: 1,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 2,
        linhaFim: 1,
        colunaFim: 4,
        pistaLinha: 1,
        pistaColuna: 4,
      },
      {
        linhaInicio: 2,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 3,
        pistaLinha: 4,
        pistaColuna: 2,
      },
      {
        linhaInicio: 2,
        colunaInicio: 4,
        linhaFim: 3,
        colunaFim: 4,
        pistaLinha: 3,
        pistaColuna: 4,
      },
      {
        linhaInicio: 3,
        colunaInicio: 0,
        linhaFim: 4,
        colunaFim: 1,
        pistaLinha: 3,
        pistaColuna: 1,
      },
      {
        linhaInicio: 4,
        colunaInicio: 4,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 4,
        pistaColuna: 4,
      },
    ],
  },
  {
    id: 'facil-7',
    dificuldade: 'facil',
    linhas: 5,
    colunas: 5,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 0,
        colunaFim: 2,
        pistaLinha: 0,
        pistaColuna: 1,
      },
      {
        linhaInicio: 0,
        colunaInicio: 3,
        linhaFim: 0,
        colunaFim: 4,
        pistaLinha: 0,
        pistaColuna: 4,
      },
      {
        linhaInicio: 1,
        colunaInicio: 0,
        linhaFim: 2,
        colunaFim: 0,
        pistaLinha: 2,
        pistaColuna: 0,
      },
      {
        linhaInicio: 1,
        colunaInicio: 1,
        linhaFim: 1,
        colunaFim: 4,
        pistaLinha: 1,
        pistaColuna: 3,
      },
      {
        linhaInicio: 2,
        colunaInicio: 1,
        linhaFim: 2,
        colunaFim: 2,
        pistaLinha: 2,
        pistaColuna: 1,
      },
      {
        linhaInicio: 2,
        colunaInicio: 3,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 4,
        pistaColuna: 3,
      },
      {
        linhaInicio: 3,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 2,
        pistaLinha: 3,
        pistaColuna: 1,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 4,
        colunaFim: 2,
        pistaLinha: 4,
        pistaColuna: 2,
      },
    ],
  },
  {
    id: 'facil-8',
    dificuldade: 'facil',
    linhas: 5,
    colunas: 5,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 0,
        colunaFim: 1,
        pistaLinha: 0,
        pistaColuna: 1,
      },
      {
        linhaInicio: 0,
        colunaInicio: 2,
        linhaFim: 1,
        colunaFim: 4,
        pistaLinha: 1,
        pistaColuna: 4,
      },
      {
        linhaInicio: 1,
        colunaInicio: 0,
        linhaFim: 2,
        colunaFim: 0,
        pistaLinha: 1,
        pistaColuna: 0,
      },
      {
        linhaInicio: 1,
        colunaInicio: 1,
        linhaFim: 3,
        colunaFim: 1,
        pistaLinha: 1,
        pistaColuna: 1,
      },
      {
        linhaInicio: 2,
        colunaInicio: 2,
        linhaFim: 2,
        colunaFim: 3,
        pistaLinha: 2,
        pistaColuna: 2,
      },
      {
        linhaInicio: 2,
        colunaInicio: 4,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 3,
        pistaColuna: 4,
      },
      {
        linhaInicio: 3,
        colunaInicio: 0,
        linhaFim: 4,
        colunaFim: 0,
        pistaLinha: 3,
        pistaColuna: 0,
      },
      {
        linhaInicio: 3,
        colunaInicio: 2,
        linhaFim: 3,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 2,
      },
      {
        linhaInicio: 4,
        colunaInicio: 1,
        linhaFim: 4,
        colunaFim: 3,
        pistaLinha: 4,
        pistaColuna: 1,
      },
    ],
  },
  {
    id: 'facil-9',
    dificuldade: 'facil',
    linhas: 5,
    colunas: 5,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 0,
        pistaLinha: 1,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 1,
        linhaFim: 2,
        colunaFim: 2,
        pistaLinha: 1,
        pistaColuna: 2,
      },
      {
        linhaInicio: 0,
        colunaInicio: 3,
        linhaFim: 1,
        colunaFim: 4,
        pistaLinha: 1,
        pistaColuna: 4,
      },
      {
        linhaInicio: 2,
        colunaInicio: 3,
        linhaFim: 3,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 3,
      },
      {
        linhaInicio: 2,
        colunaInicio: 4,
        linhaFim: 3,
        colunaFim: 4,
        pistaLinha: 3,
        pistaColuna: 4,
      },
      {
        linhaInicio: 3,
        colunaInicio: 1,
        linhaFim: 3,
        colunaFim: 2,
        pistaLinha: 3,
        pistaColuna: 1,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 4,
        colunaFim: 2,
        pistaLinha: 4,
        pistaColuna: 1,
      },
      {
        linhaInicio: 4,
        colunaInicio: 3,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 4,
        pistaColuna: 4,
      },
    ],
  },
  {
    id: 'facil-10',
    dificuldade: 'facil',
    linhas: 5,
    colunas: 5,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 2,
        colunaFim: 1,
        pistaLinha: 0,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 2,
        linhaFim: 0,
        colunaFim: 4,
        pistaLinha: 0,
        pistaColuna: 3,
      },
      {
        linhaInicio: 1,
        colunaInicio: 2,
        linhaFim: 3,
        colunaFim: 2,
        pistaLinha: 3,
        pistaColuna: 2,
      },
      {
        linhaInicio: 1,
        colunaInicio: 3,
        linhaFim: 3,
        colunaFim: 3,
        pistaLinha: 1,
        pistaColuna: 3,
      },
      {
        linhaInicio: 1,
        colunaInicio: 4,
        linhaFim: 2,
        colunaFim: 4,
        pistaLinha: 2,
        pistaColuna: 4,
      },
      {
        linhaInicio: 3,
        colunaInicio: 0,
        linhaFim: 4,
        colunaFim: 0,
        pistaLinha: 3,
        pistaColuna: 0,
      },
      {
        linhaInicio: 3,
        colunaInicio: 1,
        linhaFim: 4,
        colunaFim: 1,
        pistaLinha: 3,
        pistaColuna: 1,
      },
      {
        linhaInicio: 3,
        colunaInicio: 4,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 3,
        pistaColuna: 4,
      },
      {
        linhaInicio: 4,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 3,
        pistaLinha: 4,
        pistaColuna: 2,
      },
    ],
  },
  {
    id: 'medio-1',
    dificuldade: 'medio',
    linhas: 7,
    colunas: 7,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 1,
        colunaFim: 1,
        pistaLinha: 1,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 2,
        linhaFim: 1,
        colunaFim: 5,
        pistaLinha: 1,
        pistaColuna: 2,
      },
      {
        linhaInicio: 0,
        colunaInicio: 6,
        linhaFim: 4,
        colunaFim: 6,
        pistaLinha: 2,
        pistaColuna: 6,
      },
      {
        linhaInicio: 2,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 1,
        pistaLinha: 2,
        pistaColuna: 0,
      },
      {
        linhaInicio: 2,
        colunaInicio: 2,
        linhaFim: 5,
        colunaFim: 2,
        pistaLinha: 2,
        pistaColuna: 2,
      },
      {
        linhaInicio: 2,
        colunaInicio: 3,
        linhaFim: 2,
        colunaFim: 4,
        pistaLinha: 2,
        pistaColuna: 3,
      },
      {
        linhaInicio: 2,
        colunaInicio: 5,
        linhaFim: 2,
        colunaFim: 5,
        pistaLinha: 2,
        pistaColuna: 5,
      },
      {
        linhaInicio: 3,
        colunaInicio: 3,
        linhaFim: 5,
        colunaFim: 3,
        pistaLinha: 5,
        pistaColuna: 3,
      },
      {
        linhaInicio: 3,
        colunaInicio: 4,
        linhaFim: 4,
        colunaFim: 5,
        pistaLinha: 4,
        pistaColuna: 5,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 5,
        colunaFim: 1,
        pistaLinha: 5,
        pistaColuna: 0,
      },
      {
        linhaInicio: 5,
        colunaInicio: 4,
        linhaFim: 5,
        colunaFim: 6,
        pistaLinha: 5,
        pistaColuna: 4,
      },
      {
        linhaInicio: 6,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 1,
        pistaLinha: 6,
        pistaColuna: 0,
      },
      {
        linhaInicio: 6,
        colunaInicio: 2,
        linhaFim: 6,
        colunaFim: 6,
        pistaLinha: 6,
        pistaColuna: 6,
      },
    ],
  },
  {
    id: 'medio-2',
    dificuldade: 'medio',
    linhas: 7,
    colunas: 7,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 0,
        colunaFim: 3,
        pistaLinha: 0,
        pistaColuna: 3,
      },
      {
        linhaInicio: 0,
        colunaInicio: 4,
        linhaFim: 1,
        colunaFim: 5,
        pistaLinha: 0,
        pistaColuna: 4,
      },
      {
        linhaInicio: 0,
        colunaInicio: 6,
        linhaFim: 4,
        colunaFim: 6,
        pistaLinha: 1,
        pistaColuna: 6,
      },
      {
        linhaInicio: 1,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 0,
        pistaLinha: 1,
        pistaColuna: 0,
      },
      {
        linhaInicio: 1,
        colunaInicio: 1,
        linhaFim: 5,
        colunaFim: 1,
        pistaLinha: 3,
        pistaColuna: 1,
      },
      {
        linhaInicio: 1,
        colunaInicio: 2,
        linhaFim: 3,
        colunaFim: 2,
        pistaLinha: 2,
        pistaColuna: 2,
      },
      {
        linhaInicio: 1,
        colunaInicio: 3,
        linhaFim: 3,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 3,
      },
      {
        linhaInicio: 2,
        colunaInicio: 4,
        linhaFim: 5,
        colunaFim: 5,
        pistaLinha: 5,
        pistaColuna: 5,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 5,
        colunaFim: 0,
        pistaLinha: 5,
        pistaColuna: 0,
      },
      {
        linhaInicio: 4,
        colunaInicio: 2,
        linhaFim: 5,
        colunaFim: 3,
        pistaLinha: 5,
        pistaColuna: 2,
      },
      {
        linhaInicio: 5,
        colunaInicio: 6,
        linhaFim: 6,
        colunaFim: 6,
        pistaLinha: 6,
        pistaColuna: 6,
      },
      {
        linhaInicio: 6,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 1,
        pistaLinha: 6,
        pistaColuna: 1,
      },
      {
        linhaInicio: 6,
        colunaInicio: 2,
        linhaFim: 6,
        colunaFim: 3,
        pistaLinha: 6,
        pistaColuna: 2,
      },
      {
        linhaInicio: 6,
        colunaInicio: 4,
        linhaFim: 6,
        colunaFim: 5,
        pistaLinha: 6,
        pistaColuna: 5,
      },
    ],
  },
  {
    id: 'medio-3',
    dificuldade: 'medio',
    linhas: 7,
    colunas: 7,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 1,
        pistaLinha: 3,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 2,
        linhaFim: 0,
        colunaFim: 4,
        pistaLinha: 0,
        pistaColuna: 4,
      },
      {
        linhaInicio: 0,
        colunaInicio: 5,
        linhaFim: 3,
        colunaFim: 6,
        pistaLinha: 3,
        pistaColuna: 5,
      },
      {
        linhaInicio: 1,
        colunaInicio: 2,
        linhaFim: 1,
        colunaFim: 3,
        pistaLinha: 1,
        pistaColuna: 3,
      },
      {
        linhaInicio: 1,
        colunaInicio: 4,
        linhaFim: 3,
        colunaFim: 4,
        pistaLinha: 3,
        pistaColuna: 4,
      },
      {
        linhaInicio: 2,
        colunaInicio: 2,
        linhaFim: 5,
        colunaFim: 3,
        pistaLinha: 5,
        pistaColuna: 2,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 1,
        pistaLinha: 6,
        pistaColuna: 1,
      },
      {
        linhaInicio: 4,
        colunaInicio: 4,
        linhaFim: 4,
        colunaFim: 6,
        pistaLinha: 4,
        pistaColuna: 4,
      },
      {
        linhaInicio: 5,
        colunaInicio: 4,
        linhaFim: 5,
        colunaFim: 6,
        pistaLinha: 5,
        pistaColuna: 4,
      },
      {
        linhaInicio: 6,
        colunaInicio: 2,
        linhaFim: 6,
        colunaFim: 5,
        pistaLinha: 6,
        pistaColuna: 4,
      },
      {
        linhaInicio: 6,
        colunaInicio: 6,
        linhaFim: 6,
        colunaFim: 6,
        pistaLinha: 6,
        pistaColuna: 6,
      },
    ],
  },
  {
    id: 'medio-4',
    dificuldade: 'medio',
    linhas: 7,
    colunas: 7,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 1,
        colunaFim: 3,
        pistaLinha: 1,
        pistaColuna: 2,
      },
      {
        linhaInicio: 0,
        colunaInicio: 4,
        linhaFim: 2,
        colunaFim: 4,
        pistaLinha: 1,
        pistaColuna: 4,
      },
      {
        linhaInicio: 0,
        colunaInicio: 5,
        linhaFim: 1,
        colunaFim: 6,
        pistaLinha: 0,
        pistaColuna: 6,
      },
      {
        linhaInicio: 2,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 0,
        pistaLinha: 6,
        pistaColuna: 0,
      },
      {
        linhaInicio: 2,
        colunaInicio: 1,
        linhaFim: 4,
        colunaFim: 2,
        pistaLinha: 4,
        pistaColuna: 2,
      },
      {
        linhaInicio: 2,
        colunaInicio: 3,
        linhaFim: 3,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 3,
      },
      {
        linhaInicio: 2,
        colunaInicio: 5,
        linhaFim: 2,
        colunaFim: 5,
        pistaLinha: 2,
        pistaColuna: 5,
      },
      {
        linhaInicio: 2,
        colunaInicio: 6,
        linhaFim: 4,
        colunaFim: 6,
        pistaLinha: 2,
        pistaColuna: 6,
      },
      {
        linhaInicio: 3,
        colunaInicio: 4,
        linhaFim: 5,
        colunaFim: 4,
        pistaLinha: 4,
        pistaColuna: 4,
      },
      {
        linhaInicio: 3,
        colunaInicio: 5,
        linhaFim: 5,
        colunaFim: 5,
        pistaLinha: 5,
        pistaColuna: 5,
      },
      {
        linhaInicio: 4,
        colunaInicio: 3,
        linhaFim: 5,
        colunaFim: 3,
        pistaLinha: 4,
        pistaColuna: 3,
      },
      {
        linhaInicio: 5,
        colunaInicio: 1,
        linhaFim: 6,
        colunaFim: 2,
        pistaLinha: 5,
        pistaColuna: 1,
      },
      {
        linhaInicio: 5,
        colunaInicio: 6,
        linhaFim: 6,
        colunaFim: 6,
        pistaLinha: 5,
        pistaColuna: 6,
      },
      {
        linhaInicio: 6,
        colunaInicio: 3,
        linhaFim: 6,
        colunaFim: 4,
        pistaLinha: 6,
        pistaColuna: 3,
      },
      {
        linhaInicio: 6,
        colunaInicio: 5,
        linhaFim: 6,
        colunaFim: 5,
        pistaLinha: 6,
        pistaColuna: 5,
      },
    ],
  },
  {
    id: 'medio-5',
    dificuldade: 'medio',
    linhas: 7,
    colunas: 7,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 0,
        colunaFim: 1,
        pistaLinha: 0,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 2,
        linhaFim: 0,
        colunaFim: 5,
        pistaLinha: 0,
        pistaColuna: 5,
      },
      {
        linhaInicio: 0,
        colunaInicio: 6,
        linhaFim: 4,
        colunaFim: 6,
        pistaLinha: 1,
        pistaColuna: 6,
      },
      {
        linhaInicio: 1,
        colunaInicio: 0,
        linhaFim: 4,
        colunaFim: 1,
        pistaLinha: 3,
        pistaColuna: 0,
      },
      {
        linhaInicio: 1,
        colunaInicio: 2,
        linhaFim: 2,
        colunaFim: 2,
        pistaLinha: 1,
        pistaColuna: 2,
      },
      {
        linhaInicio: 1,
        colunaInicio: 3,
        linhaFim: 2,
        colunaFim: 4,
        pistaLinha: 2,
        pistaColuna: 4,
      },
      {
        linhaInicio: 1,
        colunaInicio: 5,
        linhaFim: 3,
        colunaFim: 5,
        pistaLinha: 3,
        pistaColuna: 5,
      },
      {
        linhaInicio: 3,
        colunaInicio: 2,
        linhaFim: 3,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 2,
      },
      {
        linhaInicio: 3,
        colunaInicio: 4,
        linhaFim: 6,
        colunaFim: 4,
        pistaLinha: 5,
        pistaColuna: 4,
      },
      {
        linhaInicio: 4,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 2,
        pistaLinha: 4,
        pistaColuna: 2,
      },
      {
        linhaInicio: 4,
        colunaInicio: 3,
        linhaFim: 6,
        colunaFim: 3,
        pistaLinha: 5,
        pistaColuna: 3,
      },
      {
        linhaInicio: 4,
        colunaInicio: 5,
        linhaFim: 6,
        colunaFim: 5,
        pistaLinha: 4,
        pistaColuna: 5,
      },
      {
        linhaInicio: 5,
        colunaInicio: 0,
        linhaFim: 5,
        colunaFim: 2,
        pistaLinha: 5,
        pistaColuna: 2,
      },
      {
        linhaInicio: 5,
        colunaInicio: 6,
        linhaFim: 6,
        colunaFim: 6,
        pistaLinha: 5,
        pistaColuna: 6,
      },
      {
        linhaInicio: 6,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 0,
        pistaLinha: 6,
        pistaColuna: 0,
      },
      {
        linhaInicio: 6,
        colunaInicio: 1,
        linhaFim: 6,
        colunaFim: 1,
        pistaLinha: 6,
        pistaColuna: 1,
      },
      {
        linhaInicio: 6,
        colunaInicio: 2,
        linhaFim: 6,
        colunaFim: 2,
        pistaLinha: 6,
        pistaColuna: 2,
      },
    ],
  },
  {
    id: 'medio-6',
    dificuldade: 'medio',
    linhas: 7,
    colunas: 7,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 1,
        pistaLinha: 1,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 2,
        linhaFim: 3,
        colunaFim: 2,
        pistaLinha: 3,
        pistaColuna: 2,
      },
      {
        linhaInicio: 0,
        colunaInicio: 3,
        linhaFim: 2,
        colunaFim: 3,
        pistaLinha: 1,
        pistaColuna: 3,
      },
      {
        linhaInicio: 0,
        colunaInicio: 4,
        linhaFim: 1,
        colunaFim: 6,
        pistaLinha: 1,
        pistaColuna: 4,
      },
      {
        linhaInicio: 2,
        colunaInicio: 4,
        linhaFim: 5,
        colunaFim: 5,
        pistaLinha: 2,
        pistaColuna: 5,
      },
      {
        linhaInicio: 2,
        colunaInicio: 6,
        linhaFim: 3,
        colunaFim: 6,
        pistaLinha: 2,
        pistaColuna: 6,
      },
      {
        linhaInicio: 3,
        colunaInicio: 3,
        linhaFim: 4,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 3,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 0,
        pistaLinha: 6,
        pistaColuna: 0,
      },
      {
        linhaInicio: 4,
        colunaInicio: 1,
        linhaFim: 6,
        colunaFim: 2,
        pistaLinha: 6,
        pistaColuna: 2,
      },
      {
        linhaInicio: 4,
        colunaInicio: 6,
        linhaFim: 5,
        colunaFim: 6,
        pistaLinha: 5,
        pistaColuna: 6,
      },
      {
        linhaInicio: 5,
        colunaInicio: 3,
        linhaFim: 6,
        colunaFim: 3,
        pistaLinha: 6,
        pistaColuna: 3,
      },
      {
        linhaInicio: 6,
        colunaInicio: 4,
        linhaFim: 6,
        colunaFim: 6,
        pistaLinha: 6,
        pistaColuna: 5,
      },
    ],
  },
  {
    id: 'medio-7',
    dificuldade: 'medio',
    linhas: 7,
    colunas: 7,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 0,
        colunaFim: 2,
        pistaLinha: 0,
        pistaColuna: 1,
      },
      {
        linhaInicio: 0,
        colunaInicio: 3,
        linhaFim: 2,
        colunaFim: 4,
        pistaLinha: 2,
        pistaColuna: 4,
      },
      {
        linhaInicio: 0,
        colunaInicio: 5,
        linhaFim: 0,
        colunaFim: 6,
        pistaLinha: 0,
        pistaColuna: 6,
      },
      {
        linhaInicio: 1,
        colunaInicio: 0,
        linhaFim: 1,
        colunaFim: 1,
        pistaLinha: 1,
        pistaColuna: 1,
      },
      {
        linhaInicio: 1,
        colunaInicio: 2,
        linhaFim: 2,
        colunaFim: 2,
        pistaLinha: 2,
        pistaColuna: 2,
      },
      {
        linhaInicio: 1,
        colunaInicio: 5,
        linhaFim: 5,
        colunaFim: 5,
        pistaLinha: 5,
        pistaColuna: 5,
      },
      {
        linhaInicio: 1,
        colunaInicio: 6,
        linhaFim: 3,
        colunaFim: 6,
        pistaLinha: 3,
        pistaColuna: 6,
      },
      {
        linhaInicio: 2,
        colunaInicio: 0,
        linhaFim: 5,
        colunaFim: 1,
        pistaLinha: 4,
        pistaColuna: 0,
      },
      {
        linhaInicio: 3,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 4,
        pistaColuna: 2,
      },
      {
        linhaInicio: 4,
        colunaInicio: 6,
        linhaFim: 6,
        colunaFim: 6,
        pistaLinha: 6,
        pistaColuna: 6,
      },
      {
        linhaInicio: 5,
        colunaInicio: 2,
        linhaFim: 5,
        colunaFim: 4,
        pistaLinha: 5,
        pistaColuna: 2,
      },
      {
        linhaInicio: 6,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 1,
        pistaLinha: 6,
        pistaColuna: 0,
      },
      {
        linhaInicio: 6,
        colunaInicio: 2,
        linhaFim: 6,
        colunaFim: 4,
        pistaLinha: 6,
        pistaColuna: 3,
      },
      {
        linhaInicio: 6,
        colunaInicio: 5,
        linhaFim: 6,
        colunaFim: 5,
        pistaLinha: 6,
        pistaColuna: 5,
      },
    ],
  },
  {
    id: 'medio-8',
    dificuldade: 'medio',
    linhas: 7,
    colunas: 7,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 2,
        colunaFim: 1,
        pistaLinha: 1,
        pistaColuna: 1,
      },
      {
        linhaInicio: 0,
        colunaInicio: 2,
        linhaFim: 1,
        colunaFim: 4,
        pistaLinha: 0,
        pistaColuna: 4,
      },
      {
        linhaInicio: 0,
        colunaInicio: 5,
        linhaFim: 4,
        colunaFim: 5,
        pistaLinha: 3,
        pistaColuna: 5,
      },
      {
        linhaInicio: 0,
        colunaInicio: 6,
        linhaFim: 3,
        colunaFim: 6,
        pistaLinha: 2,
        pistaColuna: 6,
      },
      {
        linhaInicio: 2,
        colunaInicio: 2,
        linhaFim: 3,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 2,
      },
      {
        linhaInicio: 2,
        colunaInicio: 4,
        linhaFim: 3,
        colunaFim: 4,
        pistaLinha: 2,
        pistaColuna: 4,
      },
      {
        linhaInicio: 3,
        colunaInicio: 0,
        linhaFim: 5,
        colunaFim: 0,
        pistaLinha: 4,
        pistaColuna: 0,
      },
      {
        linhaInicio: 3,
        colunaInicio: 1,
        linhaFim: 6,
        colunaFim: 1,
        pistaLinha: 5,
        pistaColuna: 1,
      },
      {
        linhaInicio: 4,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 4,
        pistaColuna: 4,
      },
      {
        linhaInicio: 4,
        colunaInicio: 6,
        linhaFim: 6,
        colunaFim: 6,
        pistaLinha: 6,
        pistaColuna: 6,
      },
      {
        linhaInicio: 5,
        colunaInicio: 2,
        linhaFim: 6,
        colunaFim: 5,
        pistaLinha: 5,
        pistaColuna: 3,
      },
      {
        linhaInicio: 6,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 0,
        pistaLinha: 6,
        pistaColuna: 0,
      },
    ],
  },
  {
    id: 'medio-9',
    dificuldade: 'medio',
    linhas: 7,
    colunas: 7,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 0,
        pistaLinha: 3,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 1,
        linhaFim: 1,
        colunaFim: 2,
        pistaLinha: 0,
        pistaColuna: 1,
      },
      {
        linhaInicio: 0,
        colunaInicio: 3,
        linhaFim: 3,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 3,
      },
      {
        linhaInicio: 0,
        colunaInicio: 4,
        linhaFim: 0,
        colunaFim: 6,
        pistaLinha: 0,
        pistaColuna: 4,
      },
      {
        linhaInicio: 1,
        colunaInicio: 4,
        linhaFim: 4,
        colunaFim: 5,
        pistaLinha: 2,
        pistaColuna: 5,
      },
      {
        linhaInicio: 1,
        colunaInicio: 6,
        linhaFim: 3,
        colunaFim: 6,
        pistaLinha: 2,
        pistaColuna: 6,
      },
      {
        linhaInicio: 2,
        colunaInicio: 1,
        linhaFim: 5,
        colunaFim: 1,
        pistaLinha: 4,
        pistaColuna: 1,
      },
      {
        linhaInicio: 2,
        colunaInicio: 2,
        linhaFim: 3,
        colunaFim: 2,
        pistaLinha: 3,
        pistaColuna: 2,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 0,
        pistaLinha: 6,
        pistaColuna: 0,
      },
      {
        linhaInicio: 4,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 3,
        pistaLinha: 4,
        pistaColuna: 2,
      },
      {
        linhaInicio: 4,
        colunaInicio: 6,
        linhaFim: 5,
        colunaFim: 6,
        pistaLinha: 4,
        pistaColuna: 6,
      },
      {
        linhaInicio: 5,
        colunaInicio: 2,
        linhaFim: 6,
        colunaFim: 4,
        pistaLinha: 6,
        pistaColuna: 4,
      },
      {
        linhaInicio: 5,
        colunaInicio: 5,
        linhaFim: 5,
        colunaFim: 5,
        pistaLinha: 5,
        pistaColuna: 5,
      },
      {
        linhaInicio: 6,
        colunaInicio: 1,
        linhaFim: 6,
        colunaFim: 1,
        pistaLinha: 6,
        pistaColuna: 1,
      },
      {
        linhaInicio: 6,
        colunaInicio: 5,
        linhaFim: 6,
        colunaFim: 6,
        pistaLinha: 6,
        pistaColuna: 5,
      },
    ],
  },
  {
    id: 'medio-10',
    dificuldade: 'medio',
    linhas: 7,
    colunas: 7,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 0,
        pistaLinha: 1,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 1,
        linhaFim: 1,
        colunaFim: 3,
        pistaLinha: 1,
        pistaColuna: 2,
      },
      {
        linhaInicio: 0,
        colunaInicio: 4,
        linhaFim: 3,
        colunaFim: 4,
        pistaLinha: 1,
        pistaColuna: 4,
      },
      {
        linhaInicio: 0,
        colunaInicio: 5,
        linhaFim: 3,
        colunaFim: 5,
        pistaLinha: 0,
        pistaColuna: 5,
      },
      {
        linhaInicio: 0,
        colunaInicio: 6,
        linhaFim: 3,
        colunaFim: 6,
        pistaLinha: 1,
        pistaColuna: 6,
      },
      {
        linhaInicio: 2,
        colunaInicio: 1,
        linhaFim: 4,
        colunaFim: 1,
        pistaLinha: 3,
        pistaColuna: 1,
      },
      {
        linhaInicio: 2,
        colunaInicio: 2,
        linhaFim: 5,
        colunaFim: 3,
        pistaLinha: 4,
        pistaColuna: 2,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 0,
        pistaLinha: 4,
        pistaColuna: 0,
      },
      {
        linhaInicio: 4,
        colunaInicio: 4,
        linhaFim: 6,
        colunaFim: 4,
        pistaLinha: 5,
        pistaColuna: 4,
      },
      {
        linhaInicio: 4,
        colunaInicio: 5,
        linhaFim: 5,
        colunaFim: 6,
        pistaLinha: 5,
        pistaColuna: 6,
      },
      {
        linhaInicio: 5,
        colunaInicio: 1,
        linhaFim: 6,
        colunaFim: 1,
        pistaLinha: 5,
        pistaColuna: 1,
      },
      {
        linhaInicio: 6,
        colunaInicio: 2,
        linhaFim: 6,
        colunaFim: 3,
        pistaLinha: 6,
        pistaColuna: 3,
      },
      {
        linhaInicio: 6,
        colunaInicio: 5,
        linhaFim: 6,
        colunaFim: 6,
        pistaLinha: 6,
        pistaColuna: 6,
      },
    ],
  },
  {
    id: 'dificil-1',
    dificuldade: 'dificil',
    linhas: 9,
    colunas: 9,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 1,
        colunaFim: 3,
        pistaLinha: 1,
        pistaColuna: 2,
      },
      {
        linhaInicio: 0,
        colunaInicio: 4,
        linhaFim: 1,
        colunaFim: 4,
        pistaLinha: 0,
        pistaColuna: 4,
      },
      {
        linhaInicio: 0,
        colunaInicio: 5,
        linhaFim: 1,
        colunaFim: 5,
        pistaLinha: 0,
        pistaColuna: 5,
      },
      {
        linhaInicio: 0,
        colunaInicio: 6,
        linhaFim: 0,
        colunaFim: 7,
        pistaLinha: 0,
        pistaColuna: 7,
      },
      {
        linhaInicio: 0,
        colunaInicio: 8,
        linhaFim: 4,
        colunaFim: 8,
        pistaLinha: 4,
        pistaColuna: 8,
      },
      {
        linhaInicio: 1,
        colunaInicio: 6,
        linhaFim: 5,
        colunaFim: 6,
        pistaLinha: 3,
        pistaColuna: 6,
      },
      {
        linhaInicio: 1,
        colunaInicio: 7,
        linhaFim: 3,
        colunaFim: 7,
        pistaLinha: 1,
        pistaColuna: 7,
      },
      {
        linhaInicio: 2,
        colunaInicio: 0,
        linhaFim: 2,
        colunaFim: 3,
        pistaLinha: 2,
        pistaColuna: 3,
      },
      {
        linhaInicio: 2,
        colunaInicio: 4,
        linhaFim: 3,
        colunaFim: 4,
        pistaLinha: 3,
        pistaColuna: 4,
      },
      {
        linhaInicio: 2,
        colunaInicio: 5,
        linhaFim: 4,
        colunaFim: 5,
        pistaLinha: 3,
        pistaColuna: 5,
      },
      {
        linhaInicio: 3,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 1,
        pistaLinha: 3,
        pistaColuna: 1,
      },
      {
        linhaInicio: 3,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 2,
        pistaLinha: 4,
        pistaColuna: 2,
      },
      {
        linhaInicio: 3,
        colunaInicio: 3,
        linhaFim: 5,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 3,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 1,
        pistaLinha: 5,
        pistaColuna: 0,
      },
      {
        linhaInicio: 4,
        colunaInicio: 4,
        linhaFim: 8,
        colunaFim: 4,
        pistaLinha: 5,
        pistaColuna: 4,
      },
      {
        linhaInicio: 4,
        colunaInicio: 7,
        linhaFim: 5,
        colunaFim: 7,
        pistaLinha: 5,
        pistaColuna: 7,
      },
      {
        linhaInicio: 5,
        colunaInicio: 2,
        linhaFim: 7,
        colunaFim: 2,
        pistaLinha: 5,
        pistaColuna: 2,
      },
      {
        linhaInicio: 5,
        colunaInicio: 5,
        linhaFim: 8,
        colunaFim: 5,
        pistaLinha: 7,
        pistaColuna: 5,
      },
      {
        linhaInicio: 5,
        colunaInicio: 8,
        linhaFim: 6,
        colunaFim: 8,
        pistaLinha: 6,
        pistaColuna: 8,
      },
      {
        linhaInicio: 6,
        colunaInicio: 3,
        linhaFim: 7,
        colunaFim: 3,
        pistaLinha: 7,
        pistaColuna: 3,
      },
      {
        linhaInicio: 6,
        colunaInicio: 6,
        linhaFim: 8,
        colunaFim: 6,
        pistaLinha: 7,
        pistaColuna: 6,
      },
      {
        linhaInicio: 6,
        colunaInicio: 7,
        linhaFim: 8,
        colunaFim: 7,
        pistaLinha: 6,
        pistaColuna: 7,
      },
      {
        linhaInicio: 7,
        colunaInicio: 0,
        linhaFim: 8,
        colunaFim: 0,
        pistaLinha: 7,
        pistaColuna: 0,
      },
      {
        linhaInicio: 7,
        colunaInicio: 1,
        linhaFim: 8,
        colunaFim: 1,
        pistaLinha: 7,
        pistaColuna: 1,
      },
      {
        linhaInicio: 7,
        colunaInicio: 8,
        linhaFim: 8,
        colunaFim: 8,
        pistaLinha: 7,
        pistaColuna: 8,
      },
      {
        linhaInicio: 8,
        colunaInicio: 2,
        linhaFim: 8,
        colunaFim: 3,
        pistaLinha: 8,
        pistaColuna: 2,
      },
    ],
  },
  {
    id: 'dificil-2',
    dificuldade: 'dificil',
    linhas: 9,
    colunas: 9,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 2,
        colunaFim: 2,
        pistaLinha: 0,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 3,
        linhaFim: 4,
        colunaFim: 3,
        pistaLinha: 1,
        pistaColuna: 3,
      },
      {
        linhaInicio: 0,
        colunaInicio: 4,
        linhaFim: 2,
        colunaFim: 5,
        pistaLinha: 0,
        pistaColuna: 4,
      },
      {
        linhaInicio: 0,
        colunaInicio: 6,
        linhaFim: 1,
        colunaFim: 6,
        pistaLinha: 0,
        pistaColuna: 6,
      },
      {
        linhaInicio: 0,
        colunaInicio: 7,
        linhaFim: 3,
        colunaFim: 8,
        pistaLinha: 2,
        pistaColuna: 8,
      },
      {
        linhaInicio: 2,
        colunaInicio: 6,
        linhaFim: 5,
        colunaFim: 6,
        pistaLinha: 5,
        pistaColuna: 6,
      },
      {
        linhaInicio: 3,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 2,
        pistaLinha: 3,
        pistaColuna: 1,
      },
      {
        linhaInicio: 3,
        colunaInicio: 4,
        linhaFim: 6,
        colunaFim: 5,
        pistaLinha: 4,
        pistaColuna: 4,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 2,
        pistaLinha: 5,
        pistaColuna: 0,
      },
      {
        linhaInicio: 4,
        colunaInicio: 7,
        linhaFim: 6,
        colunaFim: 7,
        pistaLinha: 5,
        pistaColuna: 7,
      },
      {
        linhaInicio: 4,
        colunaInicio: 8,
        linhaFim: 6,
        colunaFim: 8,
        pistaLinha: 5,
        pistaColuna: 8,
      },
      {
        linhaInicio: 5,
        colunaInicio: 3,
        linhaFim: 7,
        colunaFim: 3,
        pistaLinha: 5,
        pistaColuna: 3,
      },
      {
        linhaInicio: 6,
        colunaInicio: 6,
        linhaFim: 8,
        colunaFim: 6,
        pistaLinha: 6,
        pistaColuna: 6,
      },
      {
        linhaInicio: 7,
        colunaInicio: 0,
        linhaFim: 7,
        colunaFim: 2,
        pistaLinha: 7,
        pistaColuna: 0,
      },
      {
        linhaInicio: 7,
        colunaInicio: 4,
        linhaFim: 8,
        colunaFim: 4,
        pistaLinha: 8,
        pistaColuna: 4,
      },
      {
        linhaInicio: 7,
        colunaInicio: 5,
        linhaFim: 7,
        colunaFim: 5,
        pistaLinha: 7,
        pistaColuna: 5,
      },
      {
        linhaInicio: 7,
        colunaInicio: 7,
        linhaFim: 8,
        colunaFim: 7,
        pistaLinha: 8,
        pistaColuna: 7,
      },
      {
        linhaInicio: 7,
        colunaInicio: 8,
        linhaFim: 8,
        colunaFim: 8,
        pistaLinha: 8,
        pistaColuna: 8,
      },
      {
        linhaInicio: 8,
        colunaInicio: 0,
        linhaFim: 8,
        colunaFim: 2,
        pistaLinha: 8,
        pistaColuna: 2,
      },
      {
        linhaInicio: 8,
        colunaInicio: 3,
        linhaFim: 8,
        colunaFim: 3,
        pistaLinha: 8,
        pistaColuna: 3,
      },
      {
        linhaInicio: 8,
        colunaInicio: 5,
        linhaFim: 8,
        colunaFim: 5,
        pistaLinha: 8,
        pistaColuna: 5,
      },
    ],
  },
  {
    id: 'dificil-3',
    dificuldade: 'dificil',
    linhas: 9,
    colunas: 9,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 1,
        colunaFim: 3,
        pistaLinha: 0,
        pistaColuna: 2,
      },
      {
        linhaInicio: 0,
        colunaInicio: 4,
        linhaFim: 0,
        colunaFim: 7,
        pistaLinha: 0,
        pistaColuna: 6,
      },
      {
        linhaInicio: 0,
        colunaInicio: 8,
        linhaFim: 4,
        colunaFim: 8,
        pistaLinha: 0,
        pistaColuna: 8,
      },
      {
        linhaInicio: 1,
        colunaInicio: 4,
        linhaFim: 1,
        colunaFim: 6,
        pistaLinha: 1,
        pistaColuna: 4,
      },
      {
        linhaInicio: 1,
        colunaInicio: 7,
        linhaFim: 3,
        colunaFim: 7,
        pistaLinha: 3,
        pistaColuna: 7,
      },
      {
        linhaInicio: 2,
        colunaInicio: 0,
        linhaFim: 4,
        colunaFim: 1,
        pistaLinha: 2,
        pistaColuna: 0,
      },
      {
        linhaInicio: 2,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 3,
        pistaLinha: 4,
        pistaColuna: 2,
      },
      {
        linhaInicio: 2,
        colunaInicio: 4,
        linhaFim: 2,
        colunaFim: 6,
        pistaLinha: 2,
        pistaColuna: 5,
      },
      {
        linhaInicio: 3,
        colunaInicio: 4,
        linhaFim: 4,
        colunaFim: 6,
        pistaLinha: 3,
        pistaColuna: 6,
      },
      {
        linhaInicio: 4,
        colunaInicio: 7,
        linhaFim: 7,
        colunaFim: 7,
        pistaLinha: 5,
        pistaColuna: 7,
      },
      {
        linhaInicio: 5,
        colunaInicio: 0,
        linhaFim: 8,
        colunaFim: 1,
        pistaLinha: 7,
        pistaColuna: 1,
      },
      {
        linhaInicio: 5,
        colunaInicio: 2,
        linhaFim: 7,
        colunaFim: 3,
        pistaLinha: 6,
        pistaColuna: 2,
      },
      {
        linhaInicio: 5,
        colunaInicio: 4,
        linhaFim: 5,
        colunaFim: 6,
        pistaLinha: 5,
        pistaColuna: 6,
      },
      {
        linhaInicio: 5,
        colunaInicio: 8,
        linhaFim: 6,
        colunaFim: 8,
        pistaLinha: 6,
        pistaColuna: 8,
      },
      {
        linhaInicio: 6,
        colunaInicio: 4,
        linhaFim: 7,
        colunaFim: 6,
        pistaLinha: 6,
        pistaColuna: 6,
      },
      {
        linhaInicio: 7,
        colunaInicio: 8,
        linhaFim: 8,
        colunaFim: 8,
        pistaLinha: 7,
        pistaColuna: 8,
      },
      {
        linhaInicio: 8,
        colunaInicio: 2,
        linhaFim: 8,
        colunaFim: 3,
        pistaLinha: 8,
        pistaColuna: 3,
      },
      {
        linhaInicio: 8,
        colunaInicio: 4,
        linhaFim: 8,
        colunaFim: 7,
        pistaLinha: 8,
        pistaColuna: 6,
      },
    ],
  },
  {
    id: 'dificil-4',
    dificuldade: 'dificil',
    linhas: 9,
    colunas: 9,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 1,
        colunaFim: 0,
        pistaLinha: 0,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 1,
        linhaFim: 1,
        colunaFim: 1,
        pistaLinha: 0,
        pistaColuna: 1,
      },
      {
        linhaInicio: 0,
        colunaInicio: 2,
        linhaFim: 2,
        colunaFim: 2,
        pistaLinha: 0,
        pistaColuna: 2,
      },
      {
        linhaInicio: 0,
        colunaInicio: 3,
        linhaFim: 0,
        colunaFim: 4,
        pistaLinha: 0,
        pistaColuna: 4,
      },
      {
        linhaInicio: 0,
        colunaInicio: 5,
        linhaFim: 2,
        colunaFim: 6,
        pistaLinha: 1,
        pistaColuna: 5,
      },
      {
        linhaInicio: 0,
        colunaInicio: 7,
        linhaFim: 2,
        colunaFim: 8,
        pistaLinha: 0,
        pistaColuna: 7,
      },
      {
        linhaInicio: 1,
        colunaInicio: 3,
        linhaFim: 1,
        colunaFim: 3,
        pistaLinha: 1,
        pistaColuna: 3,
      },
      {
        linhaInicio: 1,
        colunaInicio: 4,
        linhaFim: 3,
        colunaFim: 4,
        pistaLinha: 1,
        pistaColuna: 4,
      },
      {
        linhaInicio: 2,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 0,
        pistaLinha: 2,
        pistaColuna: 0,
      },
      {
        linhaInicio: 2,
        colunaInicio: 1,
        linhaFim: 5,
        colunaFim: 1,
        pistaLinha: 5,
        pistaColuna: 1,
      },
      {
        linhaInicio: 2,
        colunaInicio: 3,
        linhaFim: 4,
        colunaFim: 3,
        pistaLinha: 4,
        pistaColuna: 3,
      },
      {
        linhaInicio: 3,
        colunaInicio: 2,
        linhaFim: 7,
        colunaFim: 2,
        pistaLinha: 4,
        pistaColuna: 2,
      },
      {
        linhaInicio: 3,
        colunaInicio: 5,
        linhaFim: 4,
        colunaFim: 8,
        pistaLinha: 3,
        pistaColuna: 6,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 7,
        colunaFim: 0,
        pistaLinha: 7,
        pistaColuna: 0,
      },
      {
        linhaInicio: 4,
        colunaInicio: 4,
        linhaFim: 5,
        colunaFim: 4,
        pistaLinha: 5,
        pistaColuna: 4,
      },
      {
        linhaInicio: 5,
        colunaInicio: 3,
        linhaFim: 6,
        colunaFim: 3,
        pistaLinha: 6,
        pistaColuna: 3,
      },
      {
        linhaInicio: 5,
        colunaInicio: 5,
        linhaFim: 7,
        colunaFim: 5,
        pistaLinha: 6,
        pistaColuna: 5,
      },
      {
        linhaInicio: 5,
        colunaInicio: 6,
        linhaFim: 7,
        colunaFim: 7,
        pistaLinha: 6,
        pistaColuna: 7,
      },
      {
        linhaInicio: 5,
        colunaInicio: 8,
        linhaFim: 6,
        colunaFim: 8,
        pistaLinha: 6,
        pistaColuna: 8,
      },
      {
        linhaInicio: 6,
        colunaInicio: 1,
        linhaFim: 7,
        colunaFim: 1,
        pistaLinha: 7,
        pistaColuna: 1,
      },
      {
        linhaInicio: 6,
        colunaInicio: 4,
        linhaFim: 7,
        colunaFim: 4,
        pistaLinha: 6,
        pistaColuna: 4,
      },
      {
        linhaInicio: 7,
        colunaInicio: 3,
        linhaFim: 8,
        colunaFim: 3,
        pistaLinha: 8,
        pistaColuna: 3,
      },
      {
        linhaInicio: 7,
        colunaInicio: 8,
        linhaFim: 8,
        colunaFim: 8,
        pistaLinha: 8,
        pistaColuna: 8,
      },
      {
        linhaInicio: 8,
        colunaInicio: 0,
        linhaFim: 8,
        colunaFim: 2,
        pistaLinha: 8,
        pistaColuna: 1,
      },
      {
        linhaInicio: 8,
        colunaInicio: 4,
        linhaFim: 8,
        colunaFim: 7,
        pistaLinha: 8,
        pistaColuna: 7,
      },
    ],
  },
  {
    id: 'dificil-5',
    dificuldade: 'dificil',
    linhas: 9,
    colunas: 9,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 2,
        colunaFim: 0,
        pistaLinha: 0,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 1,
        linhaFim: 0,
        colunaFim: 4,
        pistaLinha: 0,
        pistaColuna: 3,
      },
      {
        linhaInicio: 0,
        colunaInicio: 5,
        linhaFim: 1,
        colunaFim: 6,
        pistaLinha: 0,
        pistaColuna: 6,
      },
      {
        linhaInicio: 0,
        colunaInicio: 7,
        linhaFim: 1,
        colunaFim: 8,
        pistaLinha: 0,
        pistaColuna: 8,
      },
      {
        linhaInicio: 1,
        colunaInicio: 1,
        linhaFim: 2,
        colunaFim: 1,
        pistaLinha: 1,
        pistaColuna: 1,
      },
      {
        linhaInicio: 1,
        colunaInicio: 2,
        linhaFim: 3,
        colunaFim: 3,
        pistaLinha: 1,
        pistaColuna: 2,
      },
      {
        linhaInicio: 1,
        colunaInicio: 4,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 4,
        pistaColuna: 4,
      },
      {
        linhaInicio: 2,
        colunaInicio: 5,
        linhaFim: 3,
        colunaFim: 5,
        pistaLinha: 2,
        pistaColuna: 5,
      },
      {
        linhaInicio: 2,
        colunaInicio: 6,
        linhaFim: 5,
        colunaFim: 7,
        pistaLinha: 5,
        pistaColuna: 6,
      },
      {
        linhaInicio: 2,
        colunaInicio: 8,
        linhaFim: 4,
        colunaFim: 8,
        pistaLinha: 4,
        pistaColuna: 8,
      },
      {
        linhaInicio: 3,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 1,
        pistaLinha: 3,
        pistaColuna: 0,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 5,
        colunaFim: 3,
        pistaLinha: 4,
        pistaColuna: 0,
      },
      {
        linhaInicio: 4,
        colunaInicio: 5,
        linhaFim: 8,
        colunaFim: 5,
        pistaLinha: 4,
        pistaColuna: 5,
      },
      {
        linhaInicio: 5,
        colunaInicio: 4,
        linhaFim: 6,
        colunaFim: 4,
        pistaLinha: 5,
        pistaColuna: 4,
      },
      {
        linhaInicio: 5,
        colunaInicio: 8,
        linhaFim: 6,
        colunaFim: 8,
        pistaLinha: 5,
        pistaColuna: 8,
      },
      {
        linhaInicio: 6,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 3,
        pistaLinha: 6,
        pistaColuna: 2,
      },
      {
        linhaInicio: 6,
        colunaInicio: 6,
        linhaFim: 6,
        colunaFim: 7,
        pistaLinha: 6,
        pistaColuna: 7,
      },
      {
        linhaInicio: 7,
        colunaInicio: 0,
        linhaFim: 8,
        colunaFim: 0,
        pistaLinha: 8,
        pistaColuna: 0,
      },
      {
        linhaInicio: 7,
        colunaInicio: 1,
        linhaFim: 7,
        colunaFim: 3,
        pistaLinha: 7,
        pistaColuna: 2,
      },
      {
        linhaInicio: 7,
        colunaInicio: 4,
        linhaFim: 8,
        colunaFim: 4,
        pistaLinha: 7,
        pistaColuna: 4,
      },
      {
        linhaInicio: 7,
        colunaInicio: 6,
        linhaFim: 7,
        colunaFim: 8,
        pistaLinha: 7,
        pistaColuna: 8,
      },
      {
        linhaInicio: 8,
        colunaInicio: 1,
        linhaFim: 8,
        colunaFim: 1,
        pistaLinha: 8,
        pistaColuna: 1,
      },
      {
        linhaInicio: 8,
        colunaInicio: 2,
        linhaFim: 8,
        colunaFim: 3,
        pistaLinha: 8,
        pistaColuna: 3,
      },
      {
        linhaInicio: 8,
        colunaInicio: 6,
        linhaFim: 8,
        colunaFim: 7,
        pistaLinha: 8,
        pistaColuna: 6,
      },
      {
        linhaInicio: 8,
        colunaInicio: 8,
        linhaFim: 8,
        colunaFim: 8,
        pistaLinha: 8,
        pistaColuna: 8,
      },
    ],
  },
  {
    id: 'dificil-6',
    dificuldade: 'dificil',
    linhas: 9,
    colunas: 9,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 0,
        colunaFim: 4,
        pistaLinha: 0,
        pistaColuna: 1,
      },
      {
        linhaInicio: 0,
        colunaInicio: 5,
        linhaFim: 0,
        colunaFim: 7,
        pistaLinha: 0,
        pistaColuna: 6,
      },
      {
        linhaInicio: 0,
        colunaInicio: 8,
        linhaFim: 3,
        colunaFim: 8,
        pistaLinha: 2,
        pistaColuna: 8,
      },
      {
        linhaInicio: 1,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 2,
        pistaLinha: 2,
        pistaColuna: 1,
      },
      {
        linhaInicio: 1,
        colunaInicio: 3,
        linhaFim: 2,
        colunaFim: 3,
        pistaLinha: 2,
        pistaColuna: 3,
      },
      {
        linhaInicio: 1,
        colunaInicio: 4,
        linhaFim: 2,
        colunaFim: 7,
        pistaLinha: 1,
        pistaColuna: 6,
      },
      {
        linhaInicio: 3,
        colunaInicio: 3,
        linhaFim: 5,
        colunaFim: 4,
        pistaLinha: 3,
        pistaColuna: 3,
      },
      {
        linhaInicio: 3,
        colunaInicio: 5,
        linhaFim: 4,
        colunaFim: 5,
        pistaLinha: 4,
        pistaColuna: 5,
      },
      {
        linhaInicio: 3,
        colunaInicio: 6,
        linhaFim: 4,
        colunaFim: 6,
        pistaLinha: 4,
        pistaColuna: 6,
      },
      {
        linhaInicio: 3,
        colunaInicio: 7,
        linhaFim: 7,
        colunaFim: 7,
        pistaLinha: 7,
        pistaColuna: 7,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 4,
        colunaFim: 2,
        pistaLinha: 4,
        pistaColuna: 2,
      },
      {
        linhaInicio: 4,
        colunaInicio: 8,
        linhaFim: 8,
        colunaFim: 8,
        pistaLinha: 5,
        pistaColuna: 8,
      },
      {
        linhaInicio: 5,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 0,
        pistaLinha: 5,
        pistaColuna: 0,
      },
      {
        linhaInicio: 5,
        colunaInicio: 1,
        linhaFim: 8,
        colunaFim: 2,
        pistaLinha: 6,
        pistaColuna: 1,
      },
      {
        linhaInicio: 5,
        colunaInicio: 5,
        linhaFim: 5,
        colunaFim: 6,
        pistaLinha: 5,
        pistaColuna: 6,
      },
      {
        linhaInicio: 6,
        colunaInicio: 3,
        linhaFim: 7,
        colunaFim: 6,
        pistaLinha: 7,
        pistaColuna: 4,
      },
      {
        linhaInicio: 7,
        colunaInicio: 0,
        linhaFim: 8,
        colunaFim: 0,
        pistaLinha: 8,
        pistaColuna: 0,
      },
      {
        linhaInicio: 8,
        colunaInicio: 3,
        linhaFim: 8,
        colunaFim: 7,
        pistaLinha: 8,
        pistaColuna: 3,
      },
    ],
  },
  {
    id: 'dificil-7',
    dificuldade: 'dificil',
    linhas: 9,
    colunas: 9,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 0,
        colunaFim: 2,
        pistaLinha: 0,
        pistaColuna: 1,
      },
      {
        linhaInicio: 0,
        colunaInicio: 3,
        linhaFim: 1,
        colunaFim: 4,
        pistaLinha: 0,
        pistaColuna: 3,
      },
      {
        linhaInicio: 0,
        colunaInicio: 5,
        linhaFim: 0,
        colunaFim: 8,
        pistaLinha: 0,
        pistaColuna: 8,
      },
      {
        linhaInicio: 1,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 0,
        pistaLinha: 1,
        pistaColuna: 0,
      },
      {
        linhaInicio: 1,
        colunaInicio: 1,
        linhaFim: 3,
        colunaFim: 2,
        pistaLinha: 1,
        pistaColuna: 1,
      },
      {
        linhaInicio: 1,
        colunaInicio: 5,
        linhaFim: 4,
        colunaFim: 5,
        pistaLinha: 4,
        pistaColuna: 5,
      },
      {
        linhaInicio: 1,
        colunaInicio: 6,
        linhaFim: 3,
        colunaFim: 8,
        pistaLinha: 3,
        pistaColuna: 6,
      },
      {
        linhaInicio: 2,
        colunaInicio: 3,
        linhaFim: 5,
        colunaFim: 4,
        pistaLinha: 3,
        pistaColuna: 3,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 5,
        colunaFim: 1,
        pistaLinha: 4,
        pistaColuna: 1,
      },
      {
        linhaInicio: 4,
        colunaInicio: 2,
        linhaFim: 6,
        colunaFim: 2,
        pistaLinha: 5,
        pistaColuna: 2,
      },
      {
        linhaInicio: 4,
        colunaInicio: 6,
        linhaFim: 7,
        colunaFim: 6,
        pistaLinha: 7,
        pistaColuna: 6,
      },
      {
        linhaInicio: 4,
        colunaInicio: 7,
        linhaFim: 8,
        colunaFim: 7,
        pistaLinha: 6,
        pistaColuna: 7,
      },
      {
        linhaInicio: 4,
        colunaInicio: 8,
        linhaFim: 6,
        colunaFim: 8,
        pistaLinha: 4,
        pistaColuna: 8,
      },
      {
        linhaInicio: 5,
        colunaInicio: 5,
        linhaFim: 8,
        colunaFim: 5,
        pistaLinha: 6,
        pistaColuna: 5,
      },
      {
        linhaInicio: 6,
        colunaInicio: 0,
        linhaFim: 8,
        colunaFim: 0,
        pistaLinha: 7,
        pistaColuna: 0,
      },
      {
        linhaInicio: 6,
        colunaInicio: 1,
        linhaFim: 7,
        colunaFim: 1,
        pistaLinha: 6,
        pistaColuna: 1,
      },
      {
        linhaInicio: 6,
        colunaInicio: 3,
        linhaFim: 7,
        colunaFim: 3,
        pistaLinha: 6,
        pistaColuna: 3,
      },
      {
        linhaInicio: 6,
        colunaInicio: 4,
        linhaFim: 8,
        colunaFim: 4,
        pistaLinha: 8,
        pistaColuna: 4,
      },
      {
        linhaInicio: 7,
        colunaInicio: 2,
        linhaFim: 8,
        colunaFim: 2,
        pistaLinha: 8,
        pistaColuna: 2,
      },
      {
        linhaInicio: 7,
        colunaInicio: 8,
        linhaFim: 8,
        colunaFim: 8,
        pistaLinha: 8,
        pistaColuna: 8,
      },
      {
        linhaInicio: 8,
        colunaInicio: 1,
        linhaFim: 8,
        colunaFim: 1,
        pistaLinha: 8,
        pistaColuna: 1,
      },
      {
        linhaInicio: 8,
        colunaInicio: 3,
        linhaFim: 8,
        colunaFim: 3,
        pistaLinha: 8,
        pistaColuna: 3,
      },
      {
        linhaInicio: 8,
        colunaInicio: 6,
        linhaFim: 8,
        colunaFim: 6,
        pistaLinha: 8,
        pistaColuna: 6,
      },
    ],
  },
  {
    id: 'dificil-8',
    dificuldade: 'dificil',
    linhas: 9,
    colunas: 9,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 0,
        colunaFim: 3,
        pistaLinha: 0,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 4,
        linhaFim: 3,
        colunaFim: 4,
        pistaLinha: 1,
        pistaColuna: 4,
      },
      {
        linhaInicio: 0,
        colunaInicio: 5,
        linhaFim: 4,
        colunaFim: 5,
        pistaLinha: 1,
        pistaColuna: 5,
      },
      {
        linhaInicio: 0,
        colunaInicio: 6,
        linhaFim: 3,
        colunaFim: 7,
        pistaLinha: 2,
        pistaColuna: 6,
      },
      {
        linhaInicio: 0,
        colunaInicio: 8,
        linhaFim: 4,
        colunaFim: 8,
        pistaLinha: 2,
        pistaColuna: 8,
      },
      {
        linhaInicio: 1,
        colunaInicio: 0,
        linhaFim: 2,
        colunaFim: 1,
        pistaLinha: 1,
        pistaColuna: 0,
      },
      {
        linhaInicio: 1,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 3,
        pistaLinha: 3,
        pistaColuna: 3,
      },
      {
        linhaInicio: 3,
        colunaInicio: 0,
        linhaFim: 5,
        colunaFim: 1,
        pistaLinha: 4,
        pistaColuna: 0,
      },
      {
        linhaInicio: 4,
        colunaInicio: 4,
        linhaFim: 7,
        colunaFim: 4,
        pistaLinha: 4,
        pistaColuna: 4,
      },
      {
        linhaInicio: 4,
        colunaInicio: 6,
        linhaFim: 8,
        colunaFim: 6,
        pistaLinha: 6,
        pistaColuna: 6,
      },
      {
        linhaInicio: 4,
        colunaInicio: 7,
        linhaFim: 6,
        colunaFim: 7,
        pistaLinha: 4,
        pistaColuna: 7,
      },
      {
        linhaInicio: 5,
        colunaInicio: 2,
        linhaFim: 6,
        colunaFim: 3,
        pistaLinha: 5,
        pistaColuna: 2,
      },
      {
        linhaInicio: 5,
        colunaInicio: 5,
        linhaFim: 8,
        colunaFim: 5,
        pistaLinha: 6,
        pistaColuna: 5,
      },
      {
        linhaInicio: 5,
        colunaInicio: 8,
        linhaFim: 7,
        colunaFim: 8,
        pistaLinha: 7,
        pistaColuna: 8,
      },
      {
        linhaInicio: 6,
        colunaInicio: 0,
        linhaFim: 6,
        colunaFim: 1,
        pistaLinha: 6,
        pistaColuna: 1,
      },
      {
        linhaInicio: 7,
        colunaInicio: 0,
        linhaFim: 8,
        colunaFim: 2,
        pistaLinha: 7,
        pistaColuna: 1,
      },
      {
        linhaInicio: 7,
        colunaInicio: 3,
        linhaFim: 8,
        colunaFim: 3,
        pistaLinha: 8,
        pistaColuna: 3,
      },
      {
        linhaInicio: 7,
        colunaInicio: 7,
        linhaFim: 8,
        colunaFim: 7,
        pistaLinha: 8,
        pistaColuna: 7,
      },
      {
        linhaInicio: 8,
        colunaInicio: 4,
        linhaFim: 8,
        colunaFim: 4,
        pistaLinha: 8,
        pistaColuna: 4,
      },
      {
        linhaInicio: 8,
        colunaInicio: 8,
        linhaFim: 8,
        colunaFim: 8,
        pistaLinha: 8,
        pistaColuna: 8,
      },
    ],
  },
  {
    id: 'dificil-9',
    dificuldade: 'dificil',
    linhas: 9,
    colunas: 9,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 0,
        colunaFim: 1,
        pistaLinha: 0,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 2,
        linhaFim: 3,
        colunaFim: 2,
        pistaLinha: 1,
        pistaColuna: 2,
      },
      {
        linhaInicio: 0,
        colunaInicio: 3,
        linhaFim: 2,
        colunaFim: 4,
        pistaLinha: 2,
        pistaColuna: 4,
      },
      {
        linhaInicio: 0,
        colunaInicio: 5,
        linhaFim: 1,
        colunaFim: 8,
        pistaLinha: 0,
        pistaColuna: 7,
      },
      {
        linhaInicio: 1,
        colunaInicio: 0,
        linhaFim: 3,
        colunaFim: 0,
        pistaLinha: 3,
        pistaColuna: 0,
      },
      {
        linhaInicio: 1,
        colunaInicio: 1,
        linhaFim: 4,
        colunaFim: 1,
        pistaLinha: 1,
        pistaColuna: 1,
      },
      {
        linhaInicio: 2,
        colunaInicio: 5,
        linhaFim: 5,
        colunaFim: 6,
        pistaLinha: 2,
        pistaColuna: 6,
      },
      {
        linhaInicio: 2,
        colunaInicio: 7,
        linhaFim: 4,
        colunaFim: 7,
        pistaLinha: 4,
        pistaColuna: 7,
      },
      {
        linhaInicio: 2,
        colunaInicio: 8,
        linhaFim: 6,
        colunaFim: 8,
        pistaLinha: 5,
        pistaColuna: 8,
      },
      {
        linhaInicio: 3,
        colunaInicio: 3,
        linhaFim: 5,
        colunaFim: 3,
        pistaLinha: 5,
        pistaColuna: 3,
      },
      {
        linhaInicio: 3,
        colunaInicio: 4,
        linhaFim: 6,
        colunaFim: 4,
        pistaLinha: 5,
        pistaColuna: 4,
      },
      {
        linhaInicio: 4,
        colunaInicio: 0,
        linhaFim: 7,
        colunaFim: 0,
        pistaLinha: 5,
        pistaColuna: 0,
      },
      {
        linhaInicio: 4,
        colunaInicio: 2,
        linhaFim: 7,
        colunaFim: 2,
        pistaLinha: 6,
        pistaColuna: 2,
      },
      {
        linhaInicio: 5,
        colunaInicio: 1,
        linhaFim: 6,
        colunaFim: 1,
        pistaLinha: 5,
        pistaColuna: 1,
      },
      {
        linhaInicio: 5,
        colunaInicio: 7,
        linhaFim: 7,
        colunaFim: 7,
        pistaLinha: 5,
        pistaColuna: 7,
      },
      {
        linhaInicio: 6,
        colunaInicio: 3,
        linhaFim: 8,
        colunaFim: 3,
        pistaLinha: 8,
        pistaColuna: 3,
      },
      {
        linhaInicio: 6,
        colunaInicio: 5,
        linhaFim: 7,
        colunaFim: 5,
        pistaLinha: 7,
        pistaColuna: 5,
      },
      {
        linhaInicio: 6,
        colunaInicio: 6,
        linhaFim: 7,
        colunaFim: 6,
        pistaLinha: 7,
        pistaColuna: 6,
      },
      {
        linhaInicio: 7,
        colunaInicio: 1,
        linhaFim: 8,
        colunaFim: 1,
        pistaLinha: 8,
        pistaColuna: 1,
      },
      {
        linhaInicio: 7,
        colunaInicio: 4,
        linhaFim: 8,
        colunaFim: 4,
        pistaLinha: 8,
        pistaColuna: 4,
      },
      {
        linhaInicio: 7,
        colunaInicio: 8,
        linhaFim: 8,
        colunaFim: 8,
        pistaLinha: 8,
        pistaColuna: 8,
      },
      {
        linhaInicio: 8,
        colunaInicio: 0,
        linhaFim: 8,
        colunaFim: 0,
        pistaLinha: 8,
        pistaColuna: 0,
      },
      {
        linhaInicio: 8,
        colunaInicio: 2,
        linhaFim: 8,
        colunaFim: 2,
        pistaLinha: 8,
        pistaColuna: 2,
      },
      {
        linhaInicio: 8,
        colunaInicio: 5,
        linhaFim: 8,
        colunaFim: 6,
        pistaLinha: 8,
        pistaColuna: 6,
      },
      {
        linhaInicio: 8,
        colunaInicio: 7,
        linhaFim: 8,
        colunaFim: 7,
        pistaLinha: 8,
        pistaColuna: 7,
      },
    ],
  },
  {
    id: 'dificil-10',
    dificuldade: 'dificil',
    linhas: 9,
    colunas: 9,
    solucao: [
      {
        linhaInicio: 0,
        colunaInicio: 0,
        linhaFim: 0,
        colunaFim: 3,
        pistaLinha: 0,
        pistaColuna: 0,
      },
      {
        linhaInicio: 0,
        colunaInicio: 4,
        linhaFim: 2,
        colunaFim: 5,
        pistaLinha: 2,
        pistaColuna: 5,
      },
      {
        linhaInicio: 0,
        colunaInicio: 6,
        linhaFim: 3,
        colunaFim: 7,
        pistaLinha: 2,
        pistaColuna: 6,
      },
      {
        linhaInicio: 0,
        colunaInicio: 8,
        linhaFim: 4,
        colunaFim: 8,
        pistaLinha: 3,
        pistaColuna: 8,
      },
      {
        linhaInicio: 1,
        colunaInicio: 0,
        linhaFim: 5,
        colunaFim: 0,
        pistaLinha: 5,
        pistaColuna: 0,
      },
      {
        linhaInicio: 1,
        colunaInicio: 1,
        linhaFim: 3,
        colunaFim: 1,
        pistaLinha: 1,
        pistaColuna: 1,
      },
      {
        linhaInicio: 1,
        colunaInicio: 2,
        linhaFim: 1,
        colunaFim: 3,
        pistaLinha: 1,
        pistaColuna: 3,
      },
      {
        linhaInicio: 2,
        colunaInicio: 2,
        linhaFim: 4,
        colunaFim: 2,
        pistaLinha: 3,
        pistaColuna: 2,
      },
      {
        linhaInicio: 2,
        colunaInicio: 3,
        linhaFim: 6,
        colunaFim: 3,
        pistaLinha: 2,
        pistaColuna: 3,
      },
      {
        linhaInicio: 3,
        colunaInicio: 4,
        linhaFim: 4,
        colunaFim: 4,
        pistaLinha: 3,
        pistaColuna: 4,
      },
      {
        linhaInicio: 3,
        colunaInicio: 5,
        linhaFim: 7,
        colunaFim: 5,
        pistaLinha: 6,
        pistaColuna: 5,
      },
      {
        linhaInicio: 4,
        colunaInicio: 1,
        linhaFim: 7,
        colunaFim: 1,
        pistaLinha: 6,
        pistaColuna: 1,
      },
      {
        linhaInicio: 4,
        colunaInicio: 6,
        linhaFim: 7,
        colunaFim: 6,
        pistaLinha: 5,
        pistaColuna: 6,
      },
      {
        linhaInicio: 4,
        colunaInicio: 7,
        linhaFim: 5,
        colunaFim: 7,
        pistaLinha: 5,
        pistaColuna: 7,
      },
      {
        linhaInicio: 5,
        colunaInicio: 2,
        linhaFim: 6,
        colunaFim: 2,
        pistaLinha: 6,
        pistaColuna: 2,
      },
      {
        linhaInicio: 5,
        colunaInicio: 4,
        linhaFim: 7,
        colunaFim: 4,
        pistaLinha: 6,
        pistaColuna: 4,
      },
      {
        linhaInicio: 5,
        colunaInicio: 8,
        linhaFim: 6,
        colunaFim: 8,
        pistaLinha: 5,
        pistaColuna: 8,
      },
      {
        linhaInicio: 6,
        colunaInicio: 0,
        linhaFim: 7,
        colunaFim: 0,
        pistaLinha: 6,
        pistaColuna: 0,
      },
      {
        linhaInicio: 6,
        colunaInicio: 7,
        linhaFim: 8,
        colunaFim: 7,
        pistaLinha: 8,
        pistaColuna: 7,
      },
      {
        linhaInicio: 7,
        colunaInicio: 2,
        linhaFim: 8,
        colunaFim: 2,
        pistaLinha: 8,
        pistaColuna: 2,
      },
      {
        linhaInicio: 7,
        colunaInicio: 3,
        linhaFim: 8,
        colunaFim: 3,
        pistaLinha: 8,
        pistaColuna: 3,
      },
      {
        linhaInicio: 7,
        colunaInicio: 8,
        linhaFim: 8,
        colunaFim: 8,
        pistaLinha: 8,
        pistaColuna: 8,
      },
      {
        linhaInicio: 8,
        colunaInicio: 0,
        linhaFim: 8,
        colunaFim: 1,
        pistaLinha: 8,
        pistaColuna: 1,
      },
      {
        linhaInicio: 8,
        colunaInicio: 4,
        linhaFim: 8,
        colunaFim: 5,
        pistaLinha: 8,
        pistaColuna: 5,
      },
      {
        linhaInicio: 8,
        colunaInicio: 6,
        linhaFim: 8,
        colunaFim: 6,
        pistaLinha: 8,
        pistaColuna: 6,
      },
    ],
  },
];

// ─── Acesso ─────────────────────────────────────────────────────────────────

export function puzzlesPorDificuldade(
  dificuldade: DificuldadeSolo,
): PuzzleShikaku[] {
  return PUZZLES_SHIKAKU.filter((p) => p.dificuldade === dificuldade);
}

export function buscarPuzzle(id: string): PuzzleShikaku | null {
  return PUZZLES_SHIKAKU.find((p) => p.id === id) ?? null;
}
